### ISSUE TITLE
Toolsets are always looked for in msbuild.exe.config, even for non-MSBuild tools

### ISSUE THREAD

**Issue by mjrousos** [microsoft/msbuild#114]
### Summary

Tools using Microsoft.Build libraries that specify toolsets in their config file are having those config settings ignored unless the tool _also_ has a MSBuild.exe.config file next to it with a 'toolsVersion' attribute.
### Cause

The root of the issue seems to be in `FileUtilities.GetTestExecutionInfo()`. The method checks whether the current executing assembly is a unit test, but the following code is incorrect and will always believe it is running in the context of a unit test:

``` C#
            // Get the executable we are running
            var program = Path.GetFileNameWithoutExtension(Environment.GetCommandLineArgs()[0]);

            // Check if it matches the pattern
            s_runningTests = program != null &&
                           s_testRunners.Any(s => program.IndexOf(s, StringComparison.InvariantCultureIgnoreCase) == -1);
```

If running in the context of a unit test, "msbuild" is substituted for the actual executable's name when checking for the existence of toolsets in config files (see a few lines later in `FileUtilities.GetTestExecutionInfo()`).

The end result is that when `TooksetConfigurationReaderHelpers.ConfigurationFileMayHaveToolsets()` checks whether the config file has toolsets or not, it errantly looks in msbuild.exe.config, regardless of the actual tool's config file name or contents.

**Comment by rainersigwald** [comment]
@AndyGerlicher Didn't you fix this recently? Or intentionally change this behavior?

**Comment by AndyGerlicher** [comment]
This issue should be closed, but I'm not entirely sure the behavior is exactly what you want? I made changes to that runningTests flag to be more accurate (it was always returning true before), but also made MSBuild read from msbuild.exe.config in any context (VS or otherwise). Can you reevaluate if this is the behavior you expect? And if you have a scenario not covered please re-open and give details on that. Thanks!

**Comment by radical** [comment]
> I made changes to that runningTests flag to be more accurate (it was always returning true before),

I hit this issue too, while doing a "builder" host for Xamarin Studio which uses the OSS msbuild for building projects. I see your fix in the `master` branch. I guess, I will wait for the merge.

> but also made MSBuild read from msbuild.exe.config in any context (VS or otherwise). 

What is the reason for this behavior? In my case, I have a custom "host" which references `Microsoft.Build.*` assemblies and then uses them to build projects (on behalf of XS). I expect MSBuild to read this host's config file instead of reading `msbuild.exe.config`.

**Comment by rainersigwald** [comment]
I think that qualifies as a request for "more discussion" @AndyGerlicher.

**Comment by jeffkl** [comment]
@AndyGerlicher was this issue resolved by the latest BuildEnvironmentHelper changes?

**Comment by rainersigwald** [comment]
Team triage: hoping this was fixed.
