### ISSUE TITLE
CLP Help parameters misleading

### ISSUE THREAD

**Issue by NTaylorMullen** [Microsoft/msbuild#1223]
The CLP help states that one can provide the following arguments: `/clp:NoSummary;NoItemAndPropertyList;verbosity=minimal`

The problem with this approach is the msbuild command then doesn't recognize `NoItemAndPropertyList` or the `verbosity` modifier.

**Comment by jeffkl** [comment]
@NTaylorMullen I just tested this by running `MSBuild.exe` from our latest code and everything works as expected.

`Verbosity` can override some of the other properties such as if `Verbosity=Minimal` then `NoSummary` has no effect since the summary wouldn't be shown anyway.  `NoItemAndPropertyList` only works if `Verbosity=Diag`.

> The problem with this approach is the msbuild command then doesn't recognize `NoItemAndPropertyList` or the `verbosity` modifier.

Did you get an error that the values weren't recognized?  Where you running MSBuild via `dotnet msbuild` ?

**Comment by NTaylorMullen** [comment]
@jeffkl Yup, got an error stating that the values weren't recognized. And yes, was running via `dotnet msbuild`

**Comment by jeffkl** [comment]
I just downloaded the latest CLI and ran the following:

```
C:\Users\jeffkl\Downloads\dotnet\dotnet.exe msbuild C:\Users\jeffkl\Desktop\Stuff\a.proj /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal
Microsoft (R) Build Engine version 15.1.454.57113
Copyright (C) Microsoft Corporation. All rights reserved.

  Hello World
```

My project:
``` xml
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Build">
    <Message Text="Hello World" Importance="High" />
  </Target>
</Project>
```

```
.NET Command Line Tools (1.0.0-preview5-004223)

Product Information:
 Version:            1.0.0-preview5-004223
 Commit SHA-1 hash:  86272a8812

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\jeffkl\Downloads\dotnet\sdk\1.0.0-preview5-004223
```

Please re-open if you can provide a repro.
