### ISSUE TITLE
[error MSB3491]Wired build error when integrated with Jenkins

### ISSUE THREAD

**Issue by zilongshanren** [Microsoft/msbuild#123]
Here is the error message:

```
 C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(308,5): error MSB3491: Could not write lines to file 

"Release.win32\MyLuaGam.B7C2A162.tlog\MyLuaGame/frameworks/runtime-src/proj.win32/MyLuaGame.sln.lastbuildstate". Could not find a part of the path 

'd:\win32_slave\workspace\tp-daily-lua\node\win32\MyLuaGame\frameworks\cocos2d-x\cocos\editor-support\spine\proj.win32\Release.win32\MyLuaGam.B7C2A162.tlog\MyLuaGame\frameworks\runtime

-src\proj.win32\MyLuaGame.sln.lastbuildstate'. [d:\win32_slave\workspace\tp-daily-lua\node\win32\MyLuaGame\frameworks\cocos2d-x\cocos\editor-

support\spine\proj.win32\libSpine.vcxproj]
```

But if I login into the local machine and run msbuild, it won't failed.

Another similar issue:

http://jenkins-ci.361315.n4.nabble.com/MSBuild-Fails-in-Hudson-but-not-when-executed-from-cmd-line-td3175039.html

Any suggestions will be appreciated. 
Thanks.

**Comment by zilongshanren** [comment]
I found some links, but I still can't figure it out.

http://bartwullems.blogspot.com/2009/11/msbuild-error-msb3491-could-not-write.html

https://ujjavalsuthar.wordpress.com/2012/09/06/260-characters-limitation-for-tfs-build-path/

**Comment by sarajoiner** [comment]
By my count 'd:\win32_slave\workspace\tp-daily-lua\node\win32\MyLuaGame\frameworks\cocos2d-x\cocos\editor-support\spine\proj.win32\Release.win32\MyLuaGam.B7C2A162.tlog\MyLuaGame\frameworks\runtime-src\proj.win32\MyLuaGame.sln.lastbuildstate' is only 228 characters long, so I don't think you're running into the 260 character limit mentioned in a couple of the links you shared.  

I'd first recommend checking to see if that path actually exists.  

Looking at the initial error message and the way it contains both '\' and '/', I'm also wondering if there might be a cross-plat issue going on here.  If this is a cross-plat build - or if you know of some other reason that those '/' would be showing up in the path - that would be useful to mention.  (If that is the case, I'm afraid I'm not aware of whether / how well the C++ build system supports cross-plat.) 

Since you mention that a local build by logging onto the machine is successful, the next debugging step I'd recommend is getting a diagnostic build log of both a local build that succeeds and a Jenkins build that fails, and dig through the logs to see whether there are any interesting differences.  (e.g. does the local build try to write the above .lastbuildstate file somewhere else?  If so, why?) 

Also, as a general note, it's helpful to call out which version of MSBuild you're using, as that can also sometimes make a difference.  In this case, given that the error message mentions the VS 2013 C++ targets, I assume that you are using MSBuild 12?
