### ISSUE TITLE
Gitter/irc/chat channel?

### ISSUE THREAD

**Issue by radical** [Microsoft/msbuild#129]
Is there any gitter/irc/chat channel for communicating with the team, for discussing issues or approaches to fixing things? Something a little more immediate than pull requests or github issues.

**Comment by AndyGerlicher** [comment]
Sorry, no. We aren't considering doing this right now. Would like to hear if the community wants this, we can reconsider.

**Comment by AGBrown** [comment]
Since this is the top search hit for "msbuild irc", it is probably worth putting the links from the [readme.md](https://github.com/Microsoft/msbuild/blob/master/README.md) in here:

[![Join the chat at https://gitter.im/Microsoft/msbuild](https://badges.gitter.im/Microsoft/msbuild.svg)](https://gitter.im/Microsoft/msbuild?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
[![Check out what we're working on using our Waffle board!](https://badge.waffle.io/Microsoft/msbuild.svg?label=In+Progress&title=waffle+board)](http://waffle.io/Microsoft/msbuild)
