### ISSUE TITLE
CopyFilesToOutputDirectory not respected

### ISSUE THREAD

**Issue by wjk** [microsoft/msbuild#1313]
I have a snippet of MSBuild code in my C# project (private repo) that looks like this:

```xml
<PSModuleContent Include="../modules/Shared/Microsoft.PowerShell.Archive">
  <TargetPath>Modules/Microsoft.PowerShell.Archive</TargetPath>
</PSModuleContent>
```

I then have some more MSBuild code in a targets file, imported into the C# project, that processes the items defined in the above snippet. Here is the targets file, in its entirety:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="CopyPSModules" AfterTargets="Compile" Condition="'@(PSModuleContent)' != ''">
    <CreateItem Include="@(PSModuleContent -> '%(Identity)/*')" AdditionalMetadata="TargetPath=%(PSModuleContent.TargetPath)">
      <Output TaskParameter="Include" ItemName="_PSModuleContentFiles" />
    </CreateItem>

    <Message Importance="high" Text="Here is the module content: @(_PSModuleContentFiles, '&#xD;&#xA;')" />

    <ItemGroup>
      <Content Include="@(_PSModuleContentFiles)">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        <Link>%(_PSModuleContentFiles.TargetPath)/%(Filename)%(Extension)</Link>
      </Content>
    </ItemGroup>
  </Target>
</Project>
```

When I build this project, the `CopyPSModules` task runs, and I can prove as such thanks to the `<Message/>` task. However, the `<Content>` items added are not copied to the output directory as they should be. However (as far as I can tell) any `<Content>` items included in the csproj file itself are copied. The main reason I am using the `CopyPSModules` target instead of simply including the files in the csproj itself is because the `<PSModuleContent>` items reference directories, not single files. I want the contents of the entire directory copied to the output.

Also note that I am running this task after the Compile task, which is the only way I can get it to run where I really want it: Before the private `_CopyOutOfDateSourceItemsToOutputDirectoryAlways` target that actually does the copying. If I run it before the public `CopyFilesToOutputDirectory` target, the `<ItemGroup>` within the target is evaluated after the `_CopyOutOfDateSourceItemsToOutputDirectoryAlways` target is run, and therefore has no effect. However, the change in timing does not seem to do anything. Any pointers? Thanks!

**Comment by bartdkmediahuis** [comment]
*bump
Any news on this topic ? Facing a similar issue.

**Comment by rainersigwald** [comment]
This is very confusing, because the process to go from `@(Content)` items to actual file copies has many steps. The target in the OP adds `Content` items before the copy happens (in `_CopyOutOfDateSourceItemsToOutputDirectoryAlways`), but the copy doesn't look at `@(Content)`, it looks at `@(_SourceItemsToCopyToOutputDirectoryAlways)`, which is created in the target `GetCopyToOutputDirectoryItems`, using `@(ContentWithTargetPath)` which is created in `AssignTargetPaths`.

@wjk I was able to get your example to work by changing the dependencies on your target:

```diff
  <Target Name="CopyPSModules"
-         AfterTargets="Compile"
+         BeforeTargets="AssignTargetPaths" 
          Condition="'@(PSModuleContent)' != ''">
```

That way they get the full processing given to evaluation-time `Content` items, which starts at `AssignTargetPaths`.

@bartdkmediahuis If that's not enough to get your problem fixed, can you share your targets?

**Comment by livarcocc** [comment]
Closing as @rainersigwald has provided a way to get the proper behavior.
