### ISSUE TITLE
File \ New Project in Visual Studio results in extra whitespace between reference items

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#1321]
- In Visual Studio (Dev15), create a new .NET Framework Class Library
- Inspect the `.csproj` file

Expected: No blank lines between `Reference` items
Actual:

```xml
  <ItemGroup>
    <Reference Include="System"/>
    
    <Reference Include="System.Core"/>
    <Reference Include="System.Xml.Linq"/>
    <Reference Include="System.Data.DataSetExtensions"/>
    
    
    <Reference Include="Microsoft.CSharp"/>
    
    <Reference Include="System.Data"/>
    
    <Reference Include="System.Net.Http"/>
    
    <Reference Include="System.Xml"/>
  </ItemGroup>
```

This is probably related to the whitespace preserving functionality, though I'm not sure if the actual bug is in MSBuild or somewhere in VS.

**Comment by cdmihai** [comment]
Is it using the latest version of MSBuild? If it is, then it sounds like VS may be inserting spurious white spaces, because:

- the first child overwrites any initial empty space in the parent, and adds the proper whitespace for the next element (in this case the closing tag of the parent): https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeBuildEngine/UnitTestsPublicOM/Construction/WhiteSpacePreservation_Tests.cs#L229-L254
- subsequent children mirror the trailing whitespace of the first child: https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeBuildEngine/Construction/ProjectElementContainer.cs#L489-L498

Just in case though, I'm going to add unit tests for adding children to parents with existing siblings and assert for whitespace. :)

Do you know who owns the bit of code in VS that adds the references?

**Comment by dsplaisted** [comment]
> Do you know who owns the bit of code in VS that adds the references?

No, I filed the bug here because I wasn't sure

**Comment by cdmihai** [comment]
@dsplaisted 
I added some tests in #1326 to show what happens on MSBuild's side. What would be really helpful here is to learn what MSBuild APIs the bit of VS code that's adding reference items is using. The tests suggest that VS might be adding some spurious new lines, and then msbuild's logic is "preserving it"

**Comment by dsplaisted** [comment]
Turns out this also happens in VS 2015, so it's not related to MSBuild preserving whitespace, and not a regression in Dev15.
