### ISSUE TITLE
Additional properties no longer populated with items property

### ISSUE THREAD

**Issue by miloush** [Microsoft/msbuild#1359]
```xml
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <MyItem Include="1" />
    <MyItem Include="2" />
  </ItemGroup>
  <PropertyGroup>
    <ItemsProperty>@(MyItem)</ItemsProperty>
  </PropertyGroup>
  <ItemGroup>
    <PostMyItem Include="P">
      <AdditionalProperties>
         AdditionalProperty=$(ItemsProperty)
      </AdditionalProperties>
    </PostMyItem>
  </ItemGroup>
  <Target Name="Build">
    <Message Text="Done!" />
  </Target>
</Project>
```

Expected (14.0.25420.1) output:
```
Initial Items:
MyItem
    1
    2
PostMyItem
    P
        AdditionalProperties =
         AdditionalProperty=1;2
```

Actual (15.1.371.0) output:
```
Initial Items:
MyItem
    1
    2
PostMyItem
    P
        AdditionalProperties =
         AdditionalProperty=
```

**Comment by rainersigwald** [comment]
I didn't understand how this was ever working, but it definitely regressed.

From the MSBuild book:

>  You should note that if you create a property that references an item, the value of the property is evaluated when it is used. What this means is that at the time you reference the property, the item reference is evaluated and expanded. Therefore, if the item changes, so can the property.

@cdmihai said he'd tracked that down in the code once--maybe we can find it again?

**Comment by cdmihai** [comment]
This is the part that does it when metadata is evaluated: https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/Expander.cs#L254-L256 (hopefully other parts that evaluate properties use the same method)

`AdditionalProperty=$(ItemsProperty)` gets expanded to `AdditionalProperty=@(MyItem)` [here ](https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/Expander.cs#L254) and then gets expanded to `AdditionalProperty=1;2` at the next line.

The lazy evaluator regressed this scenario. When it is [processing a project item element](https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/LazyItemEvaluator.cs#L461) it [scans all metadata for referenced items](https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/LazyItemEvaluator.cs#L516). Then later on, when that item element is actually evaluated, it only has access to the items the element builder found. But since the item reference to `@(MyItem)` is hidden behind a property, this line never sees the indirect reference of the item: https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/LazyItemEvaluator.cs#L530

So what regressed is not the entire feature of properties referencing items, just metadata indirectly referencing items via properties. I'll have to audit the code more thoroughly to see if this indirect item reference issue can appear in other places.

Potential fixes:
- fix the current item reference scrapers to recursively follow properties and metadata in the search for referenced item expressions
- since the above fix can make evaluation much more expensive, we can grant individual item expressions visibility of the entire item evaluation state, not just the subset of items the operation said it would reference. (@dsplaisted was there a specific reason to restrict item operations to only what they reference?)

**Comment by dsplaisted** [comment]
> @dsplaisted was there a specific reason to restrict item operations to only what they reference?

It's mostly because that's how the data is structured.  There are lazy snapshots of the current state of each item name.  There isn't a single object that represents a snapshot of all of the items.

I think in principle there wouldn't be a problem with snapshotting the state of all the item types.  The main issue I can think of is that it would end up taking up more memory, both to keep the extra references, as well as because it might prevent pieces of the lazy evaluation tree from being discarded.
