### ISSUE TITLE
Newline behavior change in ItemGroup's Include

### ISSUE THREAD

**Issue by yuehuang010** [Microsoft/msbuild#1375]
This snippet demonstrate a change of behavior between between MSBuild 14 and 15.  See the new line in MSBuild 14 is missing from MSBuild 15.  PropertyGroup doesn't appear to be effected.

[test2.proj.txt](https://github.com/Microsoft/msbuild/files/605253/test2.proj.txt)

MSBuild 15
>   {
>   }
>   ASDF{
>   }FDSA;QWER REWQ

MSBuild 14
>   {
>   }
>   ASDF{
>   }FDSA;QWER
>   REWQ

Thanks

**Comment by rainersigwald** [comment]
@AndyGerlicher maybe related to #1340?

**Comment by yuehuang010** [comment]
Could be, but do note that property group doesn't have the same issue.

**Comment by AndyGerlicher** [comment]
Thanks for reporting this! Turns out I did fix this in my recent change (#1378), but only for Full Framework (and in Visual Studio). The fix will be included in the next preview release of VS and I verified the output matches MSBuild 14 in this example.

Closing this in favor of #1401 and mentioning it as the problem could still exist in .NET Core and I want to make sure we don't regress.
