### ISSUE TITLE
Expose verbosity as Build Property

### ISSUE THREAD

**Issue by MartinSGill** [Microsoft/msbuild#1398]
When running external tools, I'd really like those tools to respect the /verbosity switch in MSBuild. The problem is the every external tool has a different mechanism for increasing verbosity. I would therefore need an easy way to access the /verbosity switch.

I'd like to be able to do something like this:

```xml
<ItemGroup>
    <MyParams Include="path/to/some/file" />
    <MyParams Include="-abc" />
    <MyParams Include="--debug" Condition="'$(Verbosity)'=='diagnostic'" />
    <MyParams Include="--verbose" Condition="'$(Verbosity)'=='detailed'" />
    <MyParams Include="--silent" Condition="'$(Verbosity)'=='minimal' || '$(Verbosity)'=='quiet'" />
</ItemGroup>
<Exec Command="mytool.exe @(MyParams -> '%(Identity)', ' ')" />
```

I realise that this may cause issues when running different loggers at different verbosities, but I've not yet managed to think of a good solution for that. The easiest option would be to provide the verbosity level of the logger with the highest value.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
As you pointed out, all loggers can have different logging verbosity. You can work around this by passing the verbosity value as a Property into MSBuild and your logger.

**Comment by S-Luiten** [comment]
Please reconsider this, I'm working on a project with a lot of batch files containing `xcopy` as PreBuildEvent, which produce a lot of noise but can be useful for debugging. But now it is causing issues with copilot agent mode, because the context is not large enough for the entire build output, so I'd like to pass the verbosity level configured in visual studio to the batch files to suppress output from xcopy unless the verbosity is detailed or diagnostic.

**Comment by S-Luiten** [comment]
@KalleOlaviNiemitalo 
I converted my `<PreBuildEvent>call "file.bat"</PreBuildEvent>` to an `Exec` task:
```xml
<Target Name="CopyFiles" BeforeTargets="PreBuildEvent">
	<Exec Command="call &quot;file.bat&quot;" StandardOutputImportance="Low" />
</Target>
```
It'd be nice if the `StandardOutputImportance` could be configured automatically based on the MSBuild verbosity, but for now this solution works well for my use case, thank you.
