### ISSUE TITLE
Predefined Property/ItemGroup elements

### ISSUE THREAD

**Issue by aL3891** [microsoft/msbuild#1453]
Today a property or item is marked as such by being placed in a `<PropertyGroup>` or `<ItemGroup>` element. But what if there was a way to specify in advance what type of element is?
consider this:

Before:

```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>
</Project>
```

After:

```
(Inside a props file)
...
<UsingProperty Name="OutputType" />
<UsingItem Name="Compile " />
...
```

```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">
  <OutputType>Exe</OutputType>
  <Compile Include="**\*.cs" />
</Project>
```

I havent dug super deep into the msbuild code but my understanding is that there is a processing step in there where the project file is expanded and things like default imports are added, perhaps this is something that could be done there as well? I think it really cuts down on the verbosity

**Comment by cdmihai** [comment]
MSBuild is already a hard to understand language, and I'm afraid a feature like this would make it even harder to understand. :)

It would make the msbuild code harder to understand because the type of a name would be spread out throughout the top import closure, thus making the question "what type is this element?" harder to answer. 

With today's element groups the type definition is local and the user only has to look a few lines up in the same file to understand the type. Implicit typing forces the user to understand the entire import closure in order to understand the type. For example, this comes up when trying to understand whether to reference the name via `@()` or `$()`. One "organic" solution to this is to adopt the dynamic language convention of blending the type somehow in the name, like `FooProperty`, but I honestly don't like that since it is not a machine enforced convention and at some point somebody will misuse / abuse it somehow :)

In addition, nuget packages can bring in arbitrary build logic. What happens if one package in the dependency graph introduces `<UsingProperty Name="Foo" />` and another package introduces `<UsingItem Name="Foo" />`? MSBuild would have to issue an "ambiguous variable type" error, which is not that hard. However, the user would have a hard time fixing this issue, she'd have to abandon one of the dependencies.

**Comment by aL3891** [comment]
That is a valid concern however I feel that this is something tooling can help out with. One of the most common complaints against msbuild syntax in my experience is exactly that it is too verbose and users do not see the need to have PropertyGroup /ItemGroup elements around what the consider to be obvious information.

I think there is also a lot of information about this encoded in the element names themselves. Output type is naturally a property, Compile is naturally a item. 

It is true that naming clashes can occur, but they can today as well to a degree. What's stopping one nugget package to declare a Property called foo inside a Propertygroup, and another nuget package doing the same thing? In such cases one approach would to be to have the user set the type explicitly by placing the element inside a Property/Itemgroup element. I don't see those two ways to set properties/items as mutually exclusive.

**Comment by aL3891** [comment]
Another point for this approach is toolability as well, if the types for certin properties/items are know, tools can provide intellisense for them.

**Comment by aL3891** [comment]
> One "organic" solution to this is to adopt the dynamic language convention of blending the type somehow in the name, like FooProperty, but I honestly don't like that since it is not a machine enforced convention and at some point somebody will misuse / abuse it somehow :). 

Just to add some context, the reason my mind went to the `<UsingProperty>` way of doing it is because that would mirror the `<UsingTask>` method for declaring tasks. I know its probably a lot more complicated internally but it feels nice and symmetrical :) or at least consistent with the existing design philosophy for msbuild

**Comment by aL3891** [comment]
Another addition to this, I found out today that there are already ItemDefinitions : https://msdn.microsoft.com/en-us/library/bb651788.aspx

couldn't this data be used to omit the ItemProperty element? Having a PropertyDefinition as well would feel nice and symmetrical :)

**Comment by livarcocc** [comment]
Team triage: this is not something that we had other folks asking for. As such, we are going to close this issue for now. We feel like there are other language improvements that would be more beneficial to a broader group of msbuild users.
