### ISSUE TITLE
Conditioned item removes should be ignored when ShouldEvaluateForDesignTime is true

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#1475]
With VS2017:

- Create a new .NET Core Console app (or .NET Standard Class Library)
- Add a new folder to the project, named "Folder"
- Add a new class inside the folder
- Add the following to the project file, and save:

```xml
  <ItemGroup Condition="'true' == 'false'">
    <Compile Remove="Folder\**" />
  </ItemGroup>
```

EXPECTED: Solution explorer still shows the folder and the source code file inside it
ACTUAL: The folder and source file disappear from solution explorer

This is probably because Visual Studio uses `ShouldEvaluateForDesignTime` = true when getting the `Compile` items to display in solution explorer.  When this property is true, conditions are ignored when evaluating items.  This was presumably done so that all source files would show up in solution explorer even if they were conditioned on a property such as the current configuration.

Now that we've added support for `Remove` for items during evaluation, ignoring the conditions entirely is probably not the right thing to do.  When ShouldEvaluateForDesignTime is true, we should probably ignore any Removes that could be affected by a Condition.  That preserves the original intent of gathering all the items that might be included for different property values.

**Comment by dsplaisted** [comment]
I'm no longer certain that this is related to `ShouldEvaluateForDesignTime`, but there's certainly a bug somewhere.  Item `Remove`s that should be disabled by conditions seem to always apply when Visual Studio does its project evaluation.

**Comment by cdmihai** [comment]
This problem manifests for both Remove and Update.

`Project.Items` is supposed to contain the items with conditions evaluated. It should be equal to `ProjectInstance.Items`. The issue with these items is that both Remove and Update operate on these items, even if their condition is false.

 `Project.ItemsIgnoringConditions` is supposed to contain all the items, ignoring conditions. `ProjectInstance` does not have this. This item works as expected.

The problem appears because `LazyItemList..ComputeItems` executes the item operations on one single [ImmutableList<ItemData>](https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeBuildEngine/Evaluation/LazyItemEvaluator.cs#L290) list. When the evaluator gets all the items from the LazyItemEvaluator, it constructs Items and ItemsIgnoringCondition from this list. This works fine with include operations which are additive / local, but not with remove / update which mutate other items.

**Comment by cdmihai** [comment]
+@jviau for awareness.

**Comment by jviau** [comment]
When displaying items on the solution explorer CPS uses `ProjectInstance.Items`

**Comment by cdmihai** [comment]
@davkean, @jviau , @lifengl

Here is how I think `Remove` and `Update` should act on `Project.ItemsIgnoringCondition` (`IIC`). Let me know if this would break any scenarios for you:

`Remove` operations should only apply to `IIC` if they have no Condition attribute. Otherwise, if conditions are present, Remove would take out items, thus breaking `IIC`'s contract of showing all items ignoring conditions.

`Update` should behave the same: only the `Update` operations with no Condition attributes should go into `IIC`. Otherwise you can get weird things like the following example:

```xml
< Compile Condition=”TFM == net46” Update=”Foo.cs” Metadata1=”net46” Metadata2=” net46”/>
< Compile Condition=”TFM == netstandard1.6” Update=”Foo.cs” Metadata1=” netstandard1.6” />
```

If we were to include the effect of `Update` operations that have Conditions on them (regardless whether the condition is true or false), then the above snippet would create the item `Foo.cs` with metadata {Metadata1=” netstandard1.6”, Metadata2=” net46”}.

Also, because of our new lazy item evaluation, implementing this without compromising either memory or CPU is tricky. The approach I'm going with is to deffer computation of `ItemsIgnoringCondition` until someone calls it. Right now it's filled in just in time (and thus partially causing this bug). Then, when someone calls it, I'll rerun only the item evaluation phase of the evaluator to fill `IIC` in in, and I'll parametirize item evaluation to do whatever funky processing we want for `Remove` and `Update` on `IIC`. Then I'll cache the results and invalidate the cache when the project gets dirtied.
So, if there's no calls to `Project.ItemsIgnoringCondition`, then MSBuild evaluation will be faster and consume less memory.

**Comment by cdmihai** [comment]
It turns out my proposed fix requires some changes that are too risky to do for the RTW lock-down, so I'm going to spread things out: I am going to fix `Project.Items` for RTW and leave `Project.ItemsIgnoringCondition` in a state where `Remove` and `Update` whose condition evaluates to false are not applied to it.

**Comment by cdmihai** [comment]
`Project.Items` fixed in #1617. #1616 tracks `Project.ItemsIgnoringCondition`

**Comment by Leon99** [comment]
@dsplaisted we ran into an issue that looks related: we can't use the following trick
```
	<ItemGroup Condition="'$(TargetFramework)'=='net6.0'">
		<Compile Remove="DesignTimeBase.cs" />
		...
```
because VS doesn't show the file in Solution Explorer. Can you confirm that #1616 covers that, and if it's ever going to be solved?

**Comment by dsplaisted** [comment]
I'm not sure if that's the same issue.  I don't think we have any near term plans to make changes here.

You might look at how .NET Maui projects handle files which are specific to given target frameworks and try following that pattern.

**Comment by Leon99** [comment]
> You might look at how .NET Maui projects handle files which are specific to given target frameworks and try following that pattern.

Thanks for the idea @dsplaisted!
Could you point me in the right direction? I can see a bunch of platform-specific files in the MAUI template project, but there's nothing in .csproj that would reference them:
![image](https://user-images.githubusercontent.com/6840381/185517935-ee870569-bd96-4326-86f7-804b0d38c94d.png)

**Comment by dsplaisted** [comment]
@jonathanpeppers @Redth @mattleibow Could you point to some information on how .NET Maui apps handle files which are specific to a given TargetFramework, while ensuring they all appear in solution explorer?

**Comment by jonathanpeppers** [comment]
This is the latest we ended up with: https://github.com/dotnet/maui/pull/6681

@tmeschter might also have some details.
