### ISSUE TITLE
Schemas are not being properly inserted into VS

### ISSUE THREAD

**Issue by RaulPerez1** [Microsoft/msbuild#1488]
Changes to the GitHub repo for src\XMakeCommandLine\Microsoft.Build*.xsd are not being inserted into VS with MsBuild insertion.

There's a copy of these files under the original VS sources (src/xmake/xmakecommandline) which is what setup is currently using. The insertion process should either update these files or setup should be modified to copy the ones from the insertion.

**Comment by srivatsn** [comment]
Any progress on this issue? It'll be good to get this in soon to get intellisense.

**Comment by NickCraver** [comment]
Also missing this, can we do anything to help?

**Comment by davkean** [comment]
It really is a pain to have `<PackageReference>` missing in intellisense.

**Comment by rainersigwald** [comment]
The fix to this will be in two parts:

- [ ] Update the copies of the XSDs that live in the internal VS repo that currently ship with VS.
- [ ] Update setup authoring here and in VS so that the XSDs from this repo become canonical (and delete the then-redundant copy from VS).

We got tentative buyoff to do the former, but since it's internal-only changes it'll be mostly invisible here. I'll report back about progress.

**Comment by rainersigwald** [comment]
This was mitigated by #1595 for VS15 RTW. Long-term fix is tracked by #1619, which can wait for post-RTW.
