### ISSUE TITLE
MsBuild15 copying package reference assemblies to output for .NET Standard libraries

### ISSUE THREAD

**Issue by Snipx** [Microsoft/msbuild#1515]
Hi,
I am using VS2017RC to create a .NET Standard library.
When I do that and build the binaries, the package reference assemblies (System.Linq.dll, System.Net.dll etc etc) are not copied to the output path.
When I create a UWP application, however, all the dependencies are copied.
I can't seem to find any configurations for whether or not to copy the dependencies to output naither in VS2017RC nor via the .csproj file directly.

Is there any way to achieve copying of all the package references to output?

**Comment by jeffkl** [comment]
I think this is by design at the moment.  Class libraries are not runnable so when you build it there is no point in placing dependencies in the output folder.  However, when you build a runnable application like a Windows or Console app, then you need the full closure of dependencies.  It might work if you do a publish but I'm not sure if that really gets you anything.  The biggest issue I've seen with this is for unit tests which are usually class libraries, are runnable, and need all dependencies.  The advice I've seen is to target `netcoreapp1.0` and build an executable.  

Technically MSBuild doesn't own this logic as the .NET Core team owns the SDK for building .NET Core apps, the UWP team owns their SDK, etc.  If you're trying to build a .NET Core app, I'd recommend you look over at https://github.com/dotnet/sdk.  If you can't get any more clarification on your issue, feel free to re-open and I'll see if I can track someone down.

**Comment by mnmr** [comment]
Can someone explain why this still doesn't work? What moron decided to optimize this behavior from always-copy to never-copy without providing a workaround that actually lets people get work done?

There's always been good reason to abhor all things MSBuild, but this is just unbelievable. And as a consumer, I don't care for one second how Microsoft partitions its internal development divisions and who might technically be responsible for providing a fix. The toolchain is broken, fix it already.

Please not that the above is meant for Microsoft and not any particular individuals. I apologize in advance to any voluntary contributors coming across this rant.
