### ISSUE TITLE
RemoveDuplicates task should have a "had duplicates" output

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#1541]
It'd be nice to have an easy "detect duplicates in item list" operation. There is already a core task `RemoveDuplicates`, but it returns only the deduplicated list--not an indication of whether it differs from the input. For use cases like https://github.com/dotnet/sdk/pull/624, it could also return a `bool ListHadDuplicates` that could be used to generate errors or go into a different codepath.

**Comment by chwarr** [comment]
I could use such a property. I'd be happy to implement that as well, if I can get this task assigned to me.

See my related question in the [MSBuild docs about whether RemoveDuplicates is guaranteed to return the input list in the same order](https://github.com/MicrosoftDocs/visualstudio-docs/issues/622), which was prompted by writing something like this:

```xml
<Target Name="CheckNoDuplicateFooItems"
        BeforeTargets="DoSomethingWithFoo"
        Condition="'@(Foo)' != ''">
  <RemoveDuplicates
      Inputs="@(Foo)">
    <Output
        TaskParameter="Filtered"
        ItemName="_FooFiltered"/>
  </RemoveDuplicates>

  <Error Text="The Foo item contains duplicates. Ensure that each Foo item is only included once. (Check for explicit includes and globs that also match.)"
         Condition=" '@(Foo)' != '@(_FooFiltered)' " />
</Target>
```

and needing to know whether the flattened strings were going to differ due to ordering and not just duplicateness.

**Comment by chwarr** [comment]
I've got the implemented in my fork. Let me know if you'd be amenable to a PR for this.
https://github.com/chwarr/msbuild/tree/rm-dup-haddups

**Comment by rainersigwald** [comment]
@chwarr Yes, we'd love a PR for this. Thanks!
