### ISSUE TITLE
GetItemProvenance matches items outside the project cone with globs inside

### ISSUE THREAD

**Issue by jviau** [Microsoft/msbuild#1598]
GetItemProvenance is currently matching items from outside of the project cone with globs that are purely within the project cone.

```XML
<Project>
  <ItemGroup>
    <Compile Include="**/*.cs" /> <!-- Inside the project cone -->
    <Compile Include="../shared/Class1.cs"> <!-- Outside the project cone -->
      <Link>Class1.cs</Link>
    </Compile>
  </ItemGroup>
</Project>
```

``` CSharp
var provenance = project.GetItemProvenance("../shared.Class1.cs", "Compile");
Assert.Equal(1, provenance.Count); // False! it is 2.
Assert.Equal(Provenance.StringLiteral, provenance[0].Provenance); // False! Provenance.Glob, from the "**/*.cs" glob
```

**Comment by cdmihai** [comment]
This is because regex matching does not attempt to interpret neither the glob nor the matching string as a path. For this to work, we have to change today's plain string regex matching with a path aware matching. This means parsing the strings into path-aware entities such as base directory parts, globbing parts, etc and then defining a more complex matching algorithm based on these.

Also, there might be queries that cannot be unambiguous without actually hitting the disk and expanding the glob. One example is when the glob escapes the project's cone, such as `Include="**/../../**/*.cs"`. Depending on the actual file system layout, `GetItemProvenance("a.cs")` might or might not hit the Include.

**Comment by cdmihai** [comment]
Good news, `..` after `**` are actually considered illegal by msbuild.

**Comment by cdmihai** [comment]
It appears that this bug is also the cause for another bug: 
`<I Include="..\a.foo" Exclude="**\*.foo"/>` excludes `..\a.foo` in xplat, but didn't in dev14.
