### ISSUE TITLE
Multi-core Node Process Priority

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#166]
From a customer bug:
When running msbuild with parameter /m for multicore usage with low priority, (e.g. `start "" /LOW /B /WAIT msbuild /m [target]`) only the first msbuild.exe node is running with low priority. The spawned nodes run with normal priority.

Expected behavior: All spawned msbuild nodes run with main msbuild priority, in this example LOW

Ultimately we would like to do this, or even add a /priority:low switch to MSBuild itself for scenarios when CPU usage is very high on long builds and people are still wanting to use their machine.

One "gotcha" is node reuse. If the node is already around and "Normal", this will likely complicate things (or make the scenario not work).

**Comment by informatorius** [comment]
As alternative (also to fix the node reuse gotcha), a registry or environment variable could control default msbuild process priority. 
The registry setting CpuPriorityClass=5 in
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msbuild.exe\PerfOptions
do not work for spawned msbuild nodes.

**Comment by rainersigwald** [comment]
From https://github.com/Microsoft/msbuild/issues/1055#issuecomment-248671465:

> Looks like the bug is on line 368 of src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs. Instead of setting the value to NORMAL_PRIORITY_CLASS, just set it to zero.

Thanks for finding that @phkelly.

**Comment by Fragmachine** [comment]
This issue has been causing us problems for a while when running tests on our local machines. Since it's such a simple fix I've created a custom "FrankenMSBuild" to get around it. To make it work I had to copy files such as the Tracker.exe, the numbered folders and the MSBuild.exe.config file (where I then remove the 'Microsoft.Build' entry) from the official MSBuild folder, a bit sketchy to say the least. Having an official fix would thus be ideal. What's preventing this from happening? Would it help if I offered to contribute this one line change? Seems a bit silly but if that helps to move forward on this issue I can certainly do that.

**Comment by rainersigwald** [comment]
@Fragmachine Feel free to open up a PR, especially if you've tested it locally for a while.

I don't think I'm worried enough about the `/nodereuse:true` case to block the straightforward fix. If we get complaints, we can consider later adding process priority to the node handshake.

**Comment by Fragmachine** [comment]
Great! However, I will have to wait for legal authorization from EA before I can do the PR. That might take a while ...

As an aside, what's the reason for reusing nodes? From my experience that's a source of unnecessary headaches (mainly due to persistent file handle locks but also VS upgrades etc. complaining about running MSBuild instances). Running with '/nr:false' doesn't seem to have any downsides, in fact it works much better.

**Comment by rainersigwald** [comment]
Running without node reuse can slow the incremental-build case in common circumstances, because of the overhead of starting a process and JITing code for each worker. For fast builds, that can dominate over doing-useful-work time.

**Comment by Fragmachine** [comment]
Not sure where this belong so I'll put it here. 
When building the repository according to the readme file I run into this error,

`XUnit : warning : D:\github\msbuild\artifacts\2\Debug\TestResults\Microsoft.Build.Engine.UnitTests_netcoreapp2.1_x64.log [netcoreapp2.
1|x64] [D:\github\msbuild\src\Build.UnitTests\Microsoft.Build.Engine.UnitTests.csproj]
XUnit : error : Tests failed on platforms: net46|x86, netcoreapp2.1|x64 [D:\github\msbuild\src\Build.UnitTests\Microsoft.Build.Engine.
UnitTests.csproj]`

I've attached the log if that helps. This is not a new issue, I got the same thing during my previous build a couple of weeks ago. For now I'm going to ignore it since it's not related to any changes I've made. 

[Microsoft.Build.Engine.UnitTests_netcoreapp2.1_x64.log](https://github.com/Microsoft/msbuild/files/1784559/Microsoft.Build.Engine.UnitTests_netcoreapp2.1_x64.log)

**Comment by Fragmachine** [comment]
PR requested. What happens now? How long until we might see this in a VS Preview build?

**Comment by rainersigwald** [comment]
We'll get two core-team reviews of your PR and merge it to master, which will ship with 15.7--I'm not sure if it's too late for Preview 1 or it'll be a later preview.

**Comment by Fragmachine** [comment]
Sounds great, can't wait!
