### ISSUE TITLE
Metaproj caching doesn't take change in targets into account

### ISSUE THREAD

**Issue by tmat** [microsoft/msbuild#1695]
Msbuild caches metaproj generated based on the first invocation. New targets used in subsequent invocations they are not found. 

A workaround is to change the value of Properties passed to subsequent invocations.

### Repro

[Repro.zip](https://github.com/Microsoft/msbuild/files/772095/Repro.zip)

Create a new .NET Core library App, add build.proj that runs msbuild 3 times with targets like so:

```
    <MSBuild Projects="ClassLibrary14.sln" Properties="$(Props)" Targets="Restore"/>    
    <MSBuild Projects="ClassLibrary14.sln" Properties="$(Props)" Targets="Build"/>
    <MSBuild Projects="ClassLibrary14.sln" Properties="$(Props)" Targets="Pack"/>
```

I get an error:

```
Project "build.proj" (1) is building "ClassLibrary14.sln" (2:3) on node 1 (Pack target(s)).
ClassLibrary14.sln.metaproj : error MSB4057: The target "Pack" does not exist in the project. [ClassLi
brary14.sln]
```

When running the Pack build separately everything works fine:

```
msbuild "ClassLibrary14.sln" /t:Pack
```

```
Successfully created package 'bin\Debug\ClassLibrary14.1.0.0.nupkg'
```

**Comment by tmat** [comment]
[Repro.zip](https://github.com/Microsoft/msbuild/files/772095/Repro.zip)

**Comment by jeffkl** [comment]
This is because the `SolutionProjectGenerator` does not take into account the target names when it caches the generated metaproj.  The first invocation in `build.proj` generates the metaproj with only Build, Clean, Rebuild, and Publish along with Pack from the NuGet file imported for all solutions.  Subsequent calls re-use the cached metaproj which does not contain the `Pack` target.

The workarounds are to specify all of the targets in the same `<MSBuild />` invocation:

```xml
<MSBuild Projects="ClassLibrary14.sln" Properties="$(Props)" Targets="Restore;Build;Pack"/>  
```

Which generates all of the correct targets in the metaproj.

Alternatively, you can invalidate the cached metaproj with a property:

```xml
<MSBuild Projects="ClassLibrary14.sln" Properties="$(Props)" Targets="Restore"/>    
<MSBuild Projects="ClassLibrary14.sln" Properties="$(Props)" Targets="Build"/>
<MSBuild Projects="ClassLibrary14.sln" Properties="$(Props);Packing=true" Targets="Pack"/>
```

The property is arbitrary as it just makes the metaproj be re-generated so it will contain the `Pack` target.

**Comment by rainersigwald** [comment]
I don't see a way to do this, since there's not currently a way to add a target to an already-partially-built project in memory. There's a reasonable workaround with setting properties, so I'm going to close this won't-fix.
