### ISSUE TITLE
Unable to use csc task in simple project

### ISSUE THREAD

**Issue by sbomer** [Microsoft/msbuild#1746]
I'd like to be able to use the x-plat msbuild installed with the cli to compile simple programs while controlling arguments to csc, but this doesn't seem to work. Is this a supported scenario?

**Repro steps**

build.csproj:
```
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" >
  <Target Name="Build">
    <Csc Sources="test.cs" />
  </Target>
</Project>
```

test.cs:
```
using System;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

`dotnet msbuild /v:n` 

**Output**

```
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/23/17 3:11:59 PM.
     1>Project "/home/sven/csctest/build.csproj" on node 1 (default targets).
     1>Building with tools version "15.0".
       Project file contains ToolsVersion="". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="15.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
     1>Target "Build" in project "/home/sven/csctest/build.csproj" (entry point):
       Using "Csc" task from assembly "/home/sven/bin/sdk/1.0.0-rc4-004842/Roslyn/Microsoft.Build.Tasks.CodeAnalysis.dll".
       Task "Csc"
         /home/sven/bin/sdk/1.0.0-rc4-004842/Roslyn/csc.exe /out:test.exe test.cs
     1>/home/sven/csctest/build.csproj(3,5): error MSB6003: The specified task executable "csc.exe" could not be run. Permission denied
       Done executing task "Csc" -- FAILED.
     1>Done building target "Build" in project "build.csproj" -- FAILED.
     1>Done Building Project "/home/sven/csctest/build.csproj" (default targets) -- FAILED.

Build FAILED.

       "/home/sven/csctest/build.csproj" (default target) (1) ->
       (Build target) -> 
         /home/sven/csctest/build.csproj(3,5): error MSB6003: The specified task executable "csc.exe" could not be run. Permission denied

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.08

```

****

**Comment by rainersigwald** [comment]
This is more complicated than it seems at first, due to a combination of factors:

* The Roslyn `Csc` task defaults to attempting to run `csc.exe` (which works great on Windows/full framework, but not so well on platforms where you need to specify a host)
* `dotnet` CLI sets a property when invoking MSBuild named `CscToolExe` that points to a wrapper script (`RunCsc.cmd` or a `.sh` equivalent) that will invoke `csc` under the right host
* But you have to pass that override to the task explicitly because of MSBuild's task isolation model. I could get your project to invoke the compiler by adding `ToolExe="$(CscToolExe)"` to the `<Csc>` invocation
* But that's not enough for .NET Core scenarios, because there's no longer an ambient reference to core CLR assemblies . . . so even when the compiler runs it immediately fails with, e.g., `error CS0246: The type or namespace name 'System' could not be found`
* The .NET Core SDK depends fairly deeply on NuGet package references to do the reference assembly resolution needed to explicitly get everything passed to the compiler

It's certainly possible to plumb everything through yourself, but you're likely to be swimming upstream.

**Comment by sbomer** [comment]
Thanks @rainersigwald for the clear response.
I was aware of some of these behaviors, but not others. I'll try to avoid having to do this, but now I have a good starting point if I ever need to work around this.
