### ISSUE TITLE
After upgrading a project from xproj to csproj when I build it I get "MSB4175	The task factory "CodeTaskFactory" could not be loaded from the assembly"

### ISSUE THREAD

**Issue by steve-warwick** [Microsoft/msbuild#1752]
I'm getting the following error after upgrading a xproj based project to csproj using Visual Studio 2017. Any suggestions on how to workaround this issue and what's causing it? I tried clearing out all NuGet caches, but this didn't help.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	MSB4175	The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.Tasks.v15.0.dll". Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.Tasks.v15.0.dll' or one of its dependencies. The system cannot find the file specified.	Encryption	C:\Users\SW\.nuget\packages\baseclass.contrib.nuget.output\2.1.0\build\net40\Baseclass.Contrib.Nuget.Output.targets	73	
>

**Comment by dasMulli** [comment]
This seems to be an issue with the `Basclass.Contrib.Nuget.Output` package you are using which is already filed here: https://github.com/baseclass/Contrib.Nuget/issues/32

**Comment by rainersigwald** [comment]
Long-term plan is to support inline tasks again using more portable APIs--see #304 for the tracking issue on that front. For now, to run on .NET Core MSBuild (via `dotnet build` or `dotnet msbuild`), a package must ship a managed assembly rather than source code. As mentioned in the bug linked above, that package has already done that, but it may require using a prerelease version of its package.
