### ISSUE TITLE
Warnings promoted as errors do not block the build

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#1763]
Unlike errors, warnings prompted as errors do not block the build:

Run `msbuild build.proj /warnaserror`

``` XML
<!-- build.proj -->
<Project>

  <Target Name="Build">

    <Warning Text="This should block the build." />

    <Error Text="This should never be run" />
    
  </Target>

</Project>
````

**Expected:** A single error:

```
D:\Repro\build.proj(15,5): error : This should block the build.
```
**Actual:** Two errors:

```
D:\Repro\build.proj(15,5): error : This should block the build.
D:\Repro\build.proj(9,5): error : This should never be run
```

**Comment by davkean** [comment]
I'm not sure if this behavior is expected or not, it certainty was unexpected, in our case we had "restore" before "build", we expected restore to stop the build due to warnings being promoted as error. It did not.

**Comment by davkean** [comment]
Okay, I think I understand better in my mind why I believe this warnings promoted as errors should stop the build:

When writing builds scripts that build, deploy and run tests, etc entirely in MSBuild there's two main approaches;

1) Have individual steps separated out into individual projects, ie _restore.proj_, _build.proj_, _deploy.proj_ and _test.proj_. Then individually calling MSBuild on each one, failing if MSBuild returns an error code.

2) Have individual stages separated by targets, ie _Restore_, _Build_, _Deploy_ and _Test_ targets. Then have a single call into MSBuild, and rely on MSBuild to fail the build if one of the steps fails.

In the first case, passing `warnaserror` works as expected. Any warnings coming out of one step get promoted as errors and block the build.

In the second case, passing 'warnaserror' doesn't work as expected. Any warnings that come of one step get prompted as errors, but _do not_ block the build.

**Comment by rainersigwald** [comment]
This was an intentional decision but it looks like @jeffkl and I didn't write down our discussion. Here's my recollection:

* Warnings do not stop the build.
* Errors do not *always* stop the build--you can configure `ErrorAndContinue`, and you can emit an error without failing a Task (I'll be mad at you, but it's possible).
* We expect `/WarnAsError` to be used primarily (not exclusively) in batch builds--command line full builds and CI/lab builds.

Those combine to suggest that collecting a full set of errors is better behavior for this option. The build output would then match the output of a build that didn't use the flag and just had warnings, and a CI system could report a full set of error/warnings rather than just the first, possibly reducing onion-peeling.

**Comment by rainersigwald** [comment]
Aside: 

> we had "restore" before "build",

This won't work in the same invocation of MSBuild--any build logic within newly-restored NuGet packages won't be in the "build" phase of the build, causing mysterious breakage. This is a major driver for the Sdk-acquisition work we're planning.

**Comment by jeffkl** [comment]
Here's where I sort of captured the design decision: https://github.com/Microsoft/msbuild/issues/68#issuecomment-262390696

The current logic to to simply mutate the original warning into an error and then only modify the overall build result if any warnings were mutated.  Individual tasks don't fail because of what @rainersigwald pointed out unless they `return !Log.HasLoggedErrors`.  

What do you think @davkean ?

**Comment by davkean** [comment]
I have a repro (that cannot isolate) where I'm calling the 'restore' target in an msbuild task invocation, it's producing a warning that's getting promoted to an error but this is not causing MSBuild to return a non-zero error code. Who's issue this is? I _cannot_ repro this with the following and this does the right thing (MSBuild returns 1 when I build this):

``` XML
<!-- build.proj -->
<Project>

  <Target Name="Build">

    <MSBuild BuildInParallel="true"
             Projects="project.proj"
             Targets="Warning"
             Properties="$(CommonMSBuildGlobalProperties)"
             />
    
  </Target>

  <Target Name="Warning">

	    <Warning Text="This should block the build." />
   </Target>

</Project>
```

Basically, this case - I consider these warnings as "errors" and they should block the build. I expected based on above to put the restore target into a standalone msbuild command-invocation and have that break the build due to a non-zero error code, but that did not.

**Comment by davkean** [comment]
Okay, I figured out the bug with restore - basically if you combine file logger and multi-proc build, then the error level is set to the wrong thing:
https://github.com/Microsoft/msbuild/issues/1791

I will close this issue, as you consider this behavior to be by design.
