### ISSUE TITLE
MSBuild changes console colors when logging to a file

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#1792]
We started running into build failures on Travis CI using MSBuild. It appears the logger produces thousands of unnecessary ANSI color codes.

Example:
https://travis-ci.org/aspnet/DotNetTools/jobs/206846997
The log output appears normal:
![image](https://cloud.githubusercontent.com/assets/2696087/23560811/84c65a72-fff0-11e6-91dc-be09bd25271a.png)

But if you look at the raw log file, you'll see that hundreds of color codes have been logged.
https://s3.amazonaws.com/archive.travis-ci.org/jobs/206846997/log.txt

![image](https://cloud.githubusercontent.com/assets/2696087/23560844/a76dc4f2-fff0-11e6-9d37-5be2ec017c39.png)

cc @dougbu

**Comment by natemcmaster** [comment]
Severity: this is causing builds to fail because it overflows Travis's maximum logfile size.
Example: in this [this build](https://travis-ci.org/aspnet/Mvc/jobs/207068891), MSBuild logged 306,775 ANSI color codes that were followed by another ANSI color code with no output between them.

**Comment by rainersigwald** [comment]
Possibly related to #505?

@natemcmaster can you try setting `/consoleloggerparameters:DisableConsoleColor` in your build script to see if that is a viable workaround?

**Comment by natemcmaster** [comment]
Yes, that is the workaround @dougbu is working on

**Comment by dougbu** [comment]
As long as https://github.com/aspnet/KoreBuild/archive/dev.zip wasn't lagging (definitely up-to-date now), this workaround isn't working.

For example https://api.travis-ci.org/jobs/207448561 was started about 5 minutes ago and I checked in the workaround almost half an hour ago. Despite local testing to confirm colours aren't used when `CI`, `TRAVIS`, and so on are defined, the raw log (https://api.travis-ci.org/jobs/207448561/log.txt) still contains loads of ANSI escapes. (Of course https://api.travis-ci.org/jobs/207448561/log.txt?deansi=true looks better 😈.)

Any other suggestions? If the ANSI stuff isn't coming from MsBuild, gotta wonder why we're hitting the Travis 4MB log limit.

**Comment by dougbu** [comment]
FYI the workaround relies on the environment variables Travis always sets. See https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables I'll run a test in a smaller repo to make sure that page is correct.

**Comment by dougbu** [comment]
My workaround is doing what it's designed to do. But, `/clp:DisableConsoleColor` isn't helping.

Skip to the bottom of https://travis-ci.org/aspnet/Antiforgery/jobs/207457375 to see the response files we're using when invoking MsBuild. Nonetheless https://api.travis-ci.org/jobs/207457375/log.txt and https://api.travis-ci.org/jobs/207457376/log.txt are really big. A few commands have a few ANSI codes in their output. But, the loads of colour coding happen only with the `dotnet msbuild` output.

**Comment by dougbu** [comment]
We're using the `1.0.0-rc4-004913` SDK. @rainersigwald any other suggested workarounds with this tooling?

I'm curious how #505 could be related? That PR was merged nearly a year ago.

**Comment by dougbu** [comment]
Found a workaround that actually works: Piping `dotnet msbuild` output to `tee /dev/null` cleans the raw Travis logs up completely. See https://s3.amazonaws.com/archive.travis-ci.org/jobs/207844302/log.txt for example.

What is going on here? Are the excess characters coming from something in MsBuild that `/clp:DisableConsoleColor` doesn't control?

**Comment by rainersigwald** [comment]
This is very odd. There appear to be a combination of factors at play.

* When a file logger is attached, MSBuild sets the color on stdout for every message written to the file logger, regardless of the state of `/clp:DisableConsoleColor`. This happens even on Windows and with Full Framework MSBuild--it just wasn't noticed until now.
* MSBuild does (unnecessarily) set `Console.ForegroundColor` even when it doesn't need to. [`SetColor`](https://github.com/Microsoft/msbuild/blob/be1489dc9fb0103adff65e85209f83199b5aa10a/src/Build/Logging/BaseConsoleLogger.cs#L405-L416) could easily have an "if not already that color" check.
* CoreFX attempts to detect whether an output stream is redirected and avoid emitting colors but the implementation has a comment that it's ["approximate"](https://github.com/dotnet/corefx/blob/97552c885fa462539848aa5c553cfbae522c64d0/src/System.Console/src/System/ConsolePal.Unix.cs#L439). I assume the reason it's not causing the setter to be a no-op is that it's incorrect in the Travis case for some reason. I think using `tee` lets `System.Console` understand that the output is redirected and avoid emitting the control codes.

The first one is the real problem here. Tracking the second one as #1825.

**Comment by rainersigwald** [comment]
Naturally, the reason for this ridiculous behavior is ridiculous: `FileLogger` inherits from `ConsoleLogger`. And didn't overwrite the color-setters.

**Comment by dougbu** [comment]
Naturally 😺
