### ISSUE TITLE
Build error with LINQ

### ISSUE THREAD

**Issue by stibay** [Microsoft/msbuild#1872]
Task         : MSBuild
Description  : Build with MSBuild
Version      : 1.0.54

 var a = someData.Where(m => m.SomeValue is null).ToList();

I can write this line in my code and it works perfect, but when building to production I am getting an error on the "is" statement and I have to change it to "==" instead.

Error CS1031: Type expected
Error CS1003: Syntax error, ',' expected
Process 'msbuild.exe' exited with code '1'.

Using latest version of TFS Server 2017 - Version 15.111.26117.0

The error message is pretty unclear and is this updated in a later version?

**Comment by jeffkl** [comment]
Errors prefixed with `CS` come from the compiler (csc.exe).  I would recommend you file an issue at https://github.com/dotnet/roslyn/ if you want it to be more clear.  As far as I know, you can't use the `is` statement with a null, so I'm surprised to hear that it compiles for you locally but not on your build server.  I wonder if your build server is using MSBuild 4.0 and an older version of the compiler?

I'm closing this since its not an MSBuild issue.
