### ISSUE TITLE
Meaning of RegisteredTaskObjectLifetime.Build

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#1881]
Looking at the enumeration `RegisteredTaskObjectLifetime.Build` which has the following [documentation](https://msdn.microsoft.com/en-us/library/microsoft.build.framework.registeredtaskobjectlifetime.aspx): 

> The registered object will be disposed when the build ends.

Say I run a build on a solution.  In that context build is a bit ambiguous.  I feel like it could mean either of the following: 

1. When any of the individual projects within the solution complete building
1. When the solution itself completes building

Can MSBuild clarify which is the correct interpretation?

**Comment by rainersigwald** [comment]
It's the latter--when the whole build finishes.

It cannot be the former, because MSBuild doesn't know when a project is "complete". Another request can always come along from another project that necessitates building a new target in a project that has already built some things and returned control flow.

A quick look through the code seems to confirm this--`DisposeCacheObjects(Build)` [is called](https://github.com/Microsoft/msbuild/blob/2634f05a660b14c64ae4e924d900dd200d5032e7/src/Build/BackEnd/Node/InProcNode.cs#L356) in node "shutdown" which happens in `BuildManager.EndBuild`.

Does that answer your question and make sense?

**Comment by jaredpar** [comment]
Yep that clears it up.  Thanks!
