### ISSUE TITLE
MSBuild v15.0 & Registry

### ISSUE THREAD

**Issue by manusfreedom** [Microsoft/msbuild#1920]
To be confirmed
- MSBuild 15.0 does not use registry to get information (https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0)
- Why point to registry in MSBuild.config?

To fix AspnetMergePath error:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Web\Transform\Microsoft.Web.Publishing.AspNetCompileMerge.targets(132,5): error : Can't find the valid AspnetMergePath`

We change all path in MSBuild.config to be able use MSBuild 15.0 in our build agent:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.config
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\MSBuild.exe.config
```
```
        <!-- <property name="FrameworkSDKRoot" value="$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1@InstallationFolder)" /> -->
        <property name="FrameworkSDKRoot" value="C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\" />
...
        <!-- <property name="SDK35ToolsPath" value="$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools-x86@InstallationFolder)" /> -->
        <property name="SDK35ToolsPath" value="C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\" />
        <!-- <property name="SDK40ToolsPath" value="$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86@InstallationFolder)" /> -->
        <property name="SDK40ToolsPath" value="C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.2 Tools\" />
        <!-- <property name="WindowsSDK80Path" value="$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1@InstallationFolder)" /> -->
        <property name="WindowsSDK80Path" value="C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\" />
```

**Comment by AndyGerlicher** [comment]
I'm not sure about the ASP error you're getting, would need more information. But with regards to the registry, the Toolset information/definition is no longer read from there. Previously all the data for those property names and values came from the registry. In this case only their value is still coming from the registry. And that's fine for things like global SDK paths where only a single instance can be installed on the machine and the established pattern to find that location is via the registry. We moved Toolset information because there can now be multiple copies of MSBuild installed that all have different extensions installed from Visual Studio.

Hope that help explain the reasoning.

**Comment by rtlayzell** [comment]
I'm having a similar issue, except the `SDK40ToolsPath` is used, it just points to a registry key that doesn't exist in either of my machines (Windows 10 and Windows Server 2012 R2)

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\...`

Under the above registry key I have only:

```
Windows\v7.1A
Windows\v8.0A
Windows\v8.1A
```
I have installed the Windows 10 SDK but it didn't help anything.

**Comment by livarcocc** [comment]
This issue seems like it has been addressed.
