### ISSUE TITLE
Umlauts in exec task fail

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#2187]
_From @forki on June 7, 2017 15:59_

## Steps to reproduce

```
md Präsentationen
cd Präsentationen
dotnet new -i Fable.Template.Elmish.React::*
dotnet new fable-elmish-react -n counter
cd counter
dotnet restore
```

## Expected  behavior

dotnet restore working

## Actual behavior

"file not found"

This is because ä umlaut doesn't work in the `Paket.Restore.targets` file line 17.

Even reduced call like the following would not work

```xml
    <Exec Command='"C:\Präsentationen\counter\.paket\paket.exe" restore ' ContinueOnError="false" />
```

## Environment data
`dotnet --info` output: 2.0.0-preview2-006127

/cc @davkean 

_Copied from original issue: dotnet/cli#6784_

**Comment by rainersigwald** [comment]
I get different behavior given those repro steps.

With `Fable.Template.Elmish.React 0.2.3`, the issue is that `PaketExePath` is conditioned on existence of a file referenced by a property that isn't defined (`$(PaketRootPath)`). Fixing that allows (full framework) `msbuild.exe` to correctly invoke Paket. This seems to be [fixed upstream](https://github.com/fsprojects/Paket/blob/34d9b7325359b4bacc926b6cc55e034156eea851/.paket/Paket.Restore.targets#L9-L10); I don't know what the release cycles are like for Paket.

After fixing that, I get

```
s:\work\Präsentationen\counter>dotnet restore
  The system cannot find the path specified.
s:\work\Präsentationen\counter\.paket\Paket.Restore.targets(15,5): error MSB3073: The command ""s:\work\Präsentationen\counter\.paket\paket.exe" restore --project "s:\work\Präsentationen\counter\counter.fsproj" --target-framework netstandard1.6" exited with code 3. [s:\work\Präsentationen\counter\counter.fsproj]
```

Looks like something's going wrong with the codepage specification code. Debugging.

**Comment by rainersigwald** [comment]
Works on macOS, so suspicions about cmd codepage nonsense are getting stronger.

**Comment by rainersigwald** [comment]
Ah, the issue is [here](https://github.com/Microsoft/msbuild/blob/0836664196b99b20b409757e793f42e79b7ca2a6/src/Shared/EncodingUtilities.cs#L35). On .NET Core we always assume the current codepage is UTF-8, when that should really be "if !Windows".

**Comment by forki** [comment]
Cool. Thanks a lot
