### ISSUE TITLE
Is it possible to nuget MSBuild so all build dependencies downloaded without VS/Tools install?

### ISSUE THREAD

**Issue by AnthonyLloyd** [Microsoft/msbuild#2209]
We can paket/nuget FSharp.Complier.Tools and FSharp.Core etc but we still need to install either VS or VS Build Tools for MSBuild.exe.

I see there is Microsoft.Build & Microsoft.Build.Runtime in nuget also and was thinking that these could be used to be able to make all dependencies bootstrapped from a build.cmd.

I've tried but MSBuild.exe is in a different package to Microsoft.Build.Framework.dll and fails. I can't see to get it to work.

Is what I'm trying to do possible or advisable? Seems so close. Would mean builds could be done on servers without installs.

Thanks

**Comment by rainersigwald** [comment]
It is close, but not yet. This is the idea behind the [Sdks feature](https://github.com/Microsoft/msbuild/milestone/12) that we've started rolling out with MSBuild 15, but it won't be fully possible until there's a NuGet SDK resolver (NuGet/Home#5220) and a distribution of MSBuild (NuGet package or even plain zip file) that uses it.

I'm closing this because I believe it's tracked elsewhere (for example in https://github.com/Microsoft/msbuild/issues/1493) but please give feedback if you think we've missed any of the major scenarios. The core team is definitely aware that ideally we'd have "download MSBuild thing, do no installs, invoke build, build succeeds".

**Comment by AnthonyLloyd** [comment]
Great. I look forward to it. Thanks.
