### ISSUE TITLE
Excessive memory allocation comparing paths in evaluation.

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#2348]
Based on developer community feedback:
https://developercommunity.visualstudio.com/content/problem/80371/visual-studio-becomes-unresponsive-for-a-few-minut.html

This customer reported issue is showing some extreme build behavior https://devdiv.visualstudio.com/DevDiv/_workitems/edit/464792

Here we can see his profile shows 9GB of allocations for normalizing paths during the build (profile is available in the developer community comments)

Name | Inc % | Inc
-- | -- | --
microsoft.build.ni!FileUtilities.NormalizePathForComparisonNoThrow | 83.2 | 9,816,500,224.000
microsoft.build.ni!FileUtilities.ComparePathsNoThrow | 83.2 | 9,816,500,224.000
microsoft.build.ni!Microsoft.Build.Internal.EngineFileUtilities+<>c__DisplayClass6_0.<GetFileSpecMatchTester>b__0(System.String) | 83.2 | 9,816,500,224.000
microsoft.build.ni!ItemFragment.MatchCount | 83.2 | 9,816,500,224.000
microsoft.build!Microsoft.Build.Evaluation.ItemExpressionFragment`2+<>c__DisplayClass12_0[System.__Canon,System.__Canon].<MatchCount>b__0(class Microsoft.Build.Evaluation.ValueFragment) | 83.0 | 9,786,655,744.000
system.core.ni!System.Linq.Enumerable.Count[System.__Canon](System.Collections.Generic.IEnumerable`1, System.Func`2) | 83.0 | 9,786,655,744.000
microsoft.build!Microsoft.Build.Evaluation.ItemExpressionFragment`2[System.__Canon,System.__Canon].MatchCount(class System.String) | 83.0 | 9,786,655,744.000
microsoft.build.ni!Microsoft.Build.Evaluation.ItemSpec`2+<>c__DisplayClass17_0[System.__Canon,System.__Canon].<MatchesItem>b__0(Microsoft.Build.Evaluation.ItemFragment) | 83.0 | 9,786,655,744.000
microsoft.build.ni!Microsoft.Build.Evaluation.ItemSpec`2+<>c__DisplayClass17_0[System.__Canon,System.__Canon].<MatchesItem>b__0(Microsoft.Build.Evaluation.ItemFragment) | 0.3 | 29,843,840
system.core.ni!System.Linq.Enumerable.Any[System.__Canon](System.Collections.Generic.IEnumerable`1, System.Func`2) | 0.3 | 29,843,840
microsoft.build.ni!Microsoft.Build.Evaluation.ItemSpec`2[System.__Canon,System.__Canon].MatchesItem(System.__Canon) | 0.3 | 29,843,840

The user simply added a nuget reference to a project and VS got stuck for over 5 minutes.
The profile is entirely in the in-proc build system.

**Comment by davkean** [comment]
CPU:
43% of his project is a design-time build from the legacy project system on the UI thread, of which almost all of it spent in evaluation comparing paths. He says he’s moved over to new project system, but looks like there’s still projects using the old one. I don’t see a lot of disk searching, so I’m not sure why we’re spending lots of time here.
25% is https://github.com/dotnet/corefx/issues/22771 (I filed https://github.com/Microsoft/msbuild/issues/2411 for MSBuild change)
10% is https://github.com/Microsoft/msbuild/issues/2392
10% is GC time (which resulted in about 7 seconds of UI delays)
4% is https://github.com/dotnet/corefx/issues/21105 (probably because events are turned on)
2% is throwing exceptions (!) – can’t see any stacks to get anything useful here – maybe https://github.com/Microsoft/msbuild/issues/2217?

Memory:
80.4% (8.5 GB) https://github.com/Microsoft/msbuild/issues/2348 (this is minus below)
16% (2GB) https://github.com/Microsoft/msbuild/pull/2284 (Fixed)
6% (700 MB) https://github.com/Microsoft/msbuild/pull/2378 (Fixed)

**Comment by davkean** [comment]
Besides the ones I've already called out, the majority of this looks like: https://github.com/Microsoft/msbuild/pull/2326.

**Comment by davkean** [comment]
@AndyGerlicher I think this can be resolved - this looks to be caused mainly by the underlying cause of https://github.com/Microsoft/msbuild/pull/2326 and I've filed/pointed to bugs for the rest.
