### ISSUE TITLE
Detecting operating system

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#2468]
There is a property that I'd like to give an initial value based on the operating system I'm currently running on: windows, OSX, Linux, etc ... What I'd essentially like to write is the following:

``` xml
<RoslynRuntimeIdentifier Condition="'$(RoslynRuntimeIdentifier)' == '' AND '$(OS)' == 'Windows_NT'">win7-x64</RoslynRuntimeIdentifier>
<RoslynRuntimeIdentifier Condition="'$(RoslynRuntimeIdentifier)' == '' AND '$(OS)' == 'OSX'"> osx.10.12-x64</RoslynRuntimeIdentifier>
<RoslynRuntimeIdentifier Condition="'$(RoslynRuntimeIdentifier)' == ''>linux-rid</RoslynRuntimeIdentifier>
```

The `$(OS)` flag works for windows by producing `Windows_NT`. I can't find any documentation for this property though and hence can't determine what the values would be for other operating systems. Is this property the write way to approach this and if so what are the values for other operating systems.

**Comment by rainersigwald** [comment]
If you can commit to 15.3+, you're looking for the [property function](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions) `$([MSBuild]::IsOsPlatform())`.

`$(OS)` is either `Windows_NT` or `Unix`, so you have to use trickery to distinguish between macOS and Linux if you go that route.

**Comment by jaredpar** [comment]
> $(OS) is either Windows_NT or Unix, so you have to use trickery to distinguish between macOS and Linux if you go that route.

What kind of trickery? I'm not afraid of using it but don't know what it is ;)

**Comment by akoeplinger** [comment]
One hack I've used in the past is this:

`Condition=" '$(OS)' == 'Unix' and $([System.IO.File]::Exists('/usr/lib/libc.dylib')) ">...</Condition>`

**Comment by bgavrilMS** [comment]
Thank you for posting this "workaround" @akoeplinger

**Comment by rainersigwald** [comment]
@bgavrilMS I'd recommend using `$([MSBuild]::IsOsPlatform())` instead, since it's now been available for many releases and you're unlikely to encounter a 15.0-15.2 MSBuild anywhere.

[Docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2017):

|Function signature|Description|
|------------------------|-----------------|
|bool IsOsPlatform(string platformString)|Specify whether the current OS platform is `platformString`. `platformString` must be a member of [`OSPlatform`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.osplatform?view=netstandard-2.0).|

**Comment by VladislavAntonyuk** [comment]
https://stackoverflow.com/questions/43412140/csproj-copy-files-depending-on-operating-system

**Comment by liuziangexit** [comment]
@rainersigwald 
Your solution works for me in macOS with dotnet core 2.1.505
Thanks👍
