### ISSUE TITLE
Project File and Nuget Packages

### ISSUE THREAD

**Issue by aersamkull** [Microsoft/msbuild#247]
In my Project file, I have referenced several DLLs from a Nuget Package:
```xml
<Reference Include="System.Web.Http">
      <HintPath>..\packages\Microsoft.AspNet.WebApi.Core.5.1.2\lib\net45\System.Web.Http.dll</HintPath>
    </Reference>
```

I have however configured in my nuget.config (under %AppData%\Nuget) that my Nuget Packages shall all be saved under C:\Packages (using the setting "repositoryPath". Therefore the Hint is actually not really helpful. It sometimes happens, that wrong dlls are taken (including wrong version numbers)

Is it somehow possible to do something like this:
```xml
<Reference Include="System.Web.Http">
<HintPath>$(LOCALNUGETPACKAGESPATH)\Microsoft.AspNet.WebApi.Core.5.1.2\lib\net45\System.Web.Http.dll</HintPath>
    </Reference>
```
where $(LOCALNUGETPACKAGESPATH) is defined differently for each system. For those not having configured repository path in a nuget.config, it is just ..\packages, for the others it is the repositoryPath.

Not sure if this is more of a Nuget issue

**Comment by rainersigwald** [comment]
I think this is a NuGet issue.  It's possible to do exactly as you describe using a machine-wide environment variable--MSBuild properties fall back to environment variables when no property of a given name is specified.  You could define `LocalNugetPackagesPath` and change your project files just as you were proposing, and it should work fine (in fact, this is exactly how many internal Microsoft build systems handle packages).  The problem is that NuGet's automated editing of your project file doesn't work that way.

As a heads-up, though, NuGet 3.0 has dramatically changed how references get added to projects at build time.  The new `project.json` approach doesn't change the project file at all, instead relying on a task that is run within MSBuild that reads the NuGet package configuration and dynamically creates MSBuild items.  In the new approach, there is a single, machine-wide repository, like you want.  For this reason, they may be resistant to your proposal since it's a change to the "old way" of referencing assemblies from packages.

**Comment by dsplaisted** [comment]
I think NuGet v3 with project.json as Rainer describes is the fix to this.  Right now, it's used by default by UWP apps and some Portable Class Libraries.  You can use it with other projects if you have the Windows 10 tools installed and replace packages.config with project.json.  I'm not sure if that's recommended or supported yet.
