### ISSUE TITLE
msbuild Fails to build Xamarin.Android project. 

### ISSUE THREAD

**Issue by dellis1972** [Microsoft/msbuild#2614]
We have a unit test on the xamarin-android team which builds a large android project. It has 128 projects, 127 library projects and 1 app project. 

When building from the IDE this works fine. But building from the command line on either Windows or Mac results in a build error in the App1.csproj. I have tracked this down to the fact that the project it trying to load one of the library project assemblies which it references. However this assembly has not been built by the time the App1.csproj is built, so it fails. 

So the question is why is msbuild even trying to build the App1 project when it hasn't even finished building all the dependencies yet? This is blocking us switching all our unit tests over to using msbuild rather than using mono's xbuild (it works in xbuild btw)

A copy of the test app is at [1] , but you will need to have Xamarin.Android installed to build it.

[1] https://www.dropbox.com/s/5nz1h8yvqetdwe2/BuildAMassiveApp.zip?dl=0

**Comment by dellis1972** [comment]
msbuild bindlog https://www.dropbox.com/s/ltixukf0afbbfea/msbuild.binlog?dl=0

**Comment by KirillOsenkov** [comment]
This is because each Lib* project specifies `<BuildingInsideVisualStudio>True</BuildingInsideVisualStudio>`.

ResolveProjectReferences will only build referenced projects in command line mode:
https://github.com/Microsoft/msbuild/blob/master/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1733

When BuildingInsideVisualStudio is set, it will rely on the IDE having built those already.
