### ISSUE TITLE
Can't build on macOS High Sierra (10.13)

### ISSUE THREAD

**Issue by DustinCampbell** [microsoft/msbuild#2675]
It looks like the use of `project.json` is breaking macOS High Sierra, where only .NET Core SDK 2.0 works properly. Trying to build on High Sierra seg faults when it tries to restore the build tools.

**Comment by marek-safar** [comment]
Mono has exactly same problem, due to msbuild dependency on pre-2.0 .NET Core SDK

/cc @radical

**Comment by radical** [comment]
This was fixed in 1.0.7 (https://github.com/dotnet/core/blob/master/release-notes/1.0/1.0.7.md), so we could try to move to that. But `dotnet restore` changed with that and doesn't work directly with `project.json` files now.
@AndyGerlicher Should we try to get this working with 1.0.7 or try to move to 2.0?

**Comment by AndyGerlicher** [comment]
I would accept a PR to fix it in master, but not something we will spend time to fix. We need to focus our efforts getting off of 1.X and move to SDK.

**Comment by DustinCampbell** [comment]
+ @dsplaisted, who I believe is working on this.

**Comment by radical** [comment]
And this seems to be the issue tracking that - https://github.com/Microsoft/msbuild/issues/2706

**Comment by rainersigwald** [comment]
I hope this has been looooooong fixed. I build on 10.14 and 10.15 all the time now.
