### ISSUE TITLE
MSBuid Target fires when project has been modified

### ISSUE THREAD

**Issue by samuilovaa** [Microsoft/msbuild#274]
I want do some work with compiled DLL after compilation and before build ended. I write next Test.targets:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Target Name="TrueFakeTarget" AfterTargets="AfterCompile" DependsOnTargets="$(CoreCompile)">
    <Message Text="### AfterCompile ###" Importance="high" />
    <Exec Command="calc.exe"/>
</Target>
```
And .csproj file:
```xml
 <?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{17321175-38FF-44EF-8573-82CBC0BA60D8}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>TestAfterCompile</RootNamespace>
    <AssemblyName>TestAfterCompile</AssemblyName>
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Accessibility" />
    <Reference Include="CustomMarshalers" />
    <Reference Include="ISymWrapper" />
    <Reference Include="Microsoft.Activities.Build" />
    <Reference Include="Microsoft.Build" />
    <Reference Include="Microsoft.Build.Engine" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="$(SolutionDir)\Test.targets" />
</Project>
```
After compile works perfect, but when you change project, for example, add file, add references target fires again.

How to prevent target execution if project was not compiled??

**Comment by rainersigwald** [comment]
Incremental build in MSBuild is per-target, not per project.  I'm not quite sure what you meant by "add references target fires again"--I'm assuming you mean your custom target `TrueFakeTarget`.  If you want it to only run when an input file has changed, you'll need to define `Inputs` and `Outputs` attributes.

This MSDN page has information and examples of getting incremental builds working in MSBuild: https://msdn.microsoft.com/en-us/library/ms171483.aspx.

**Comment by samuilovaa** [comment]
@rainersigwald, thank you for answer. My task is modify intermediate assembly that usually locates in "obj" folder. For this I wrote TrueFakesTarget, which runs when compilation completed. 
And target runs after compilation, but it's also runs when I modify project (add .cs or reference). Can I prevent run target when I just modify project??

**Comment by rainersigwald** [comment]
The problem you're seeing isn't that the target runs when the project is modified, it's that the target runs _anytime MSBuild runs on the project_.  It looks like it's only running when the project is modified because Visual Studio does a "fast up-to-date check" and often doesn't invoke MSBuild when things haven't changed, but always does a full build when the project file changes.

The solution is still to add `Inputs` and `Outputs` to your target to define when it should be executed.

However, I do think you'll have another problem:  adding a source file or a reference to a project will cause the project to be recompiled (with at minimum a new command line), so I'm not sure what level of incremental behavior you expect.

Both of these questions may be addressed by posting your actual target XML here.  Maybe the simplification for this example is causing me to miss something.

**Comment by samuilovaa** [comment]
@rainersigwald, I add inputs and outputs to my target. But it still runs on any change in project. Also I remove .target file and add all contents of .target file to .csproj file.
Test project: https://www.dropbox.com/s/jqfp5aneaqoyocj/TestAfterCompile.zip?dl=0

**Comment by rainersigwald** [comment]
In that zip file, there's a target defined as:

```xml
  <Target Name="TrueFakeTarget" AfterTargets="AfterCompile" Inputs="\obj\Debug\$(TargetFileName)" Outputs="$(TargetPath)">
    <Message Text="### AfterCompile ###" Importance="high" />
    <Exec Command="calc.exe" />
  </Target>
```

The leading backslash in the Inputs attribute is a path rooted at the current drive, so that's going to wind up looking for `c:\obj\Debug\TestAfterCompile.exe` or similar.

I still don't know exactly what you hope to accomplish with your target, but you might find this better:
```xml
  <Target Name="TrueFakeTarget" AfterTargets="AfterCompile" Inputs="@(IntermediateAssembly)" Outputs="$(TargetPath)">
    <Message Text="### AfterCompile ###" Importance="high" />
    <Exec Command="calc.exe" />
  </Target>
```

Note the `@(IntermediateAssembly)` item reference rather than reconstructing an intermediate path.

However, this *still* won't do what you want, because any change to the project file invalidates the output of CoreCompile.  That's because `C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets` defines the CoreCompile task like so:
```xml
  <Target
          Name="CoreCompile"
          Inputs="$(MSBuildAllProjects);
                @(Compile);
                @(_CoreCompileResourceInputs);
                $(ApplicationIcon);
                $(AssemblyOriginatorKeyFile);
                @(ReferencePath);
                @(CompiledLicenseFile);
                @(LinkResource);
                @(EmbeddedDocumentation);
                $(Win32Resource);
                $(Win32Manifest);
                @(CustomAdditionalCompileInputs);
                $(ResolvedCodeAnalysisRuleSet)"
          Outputs="@(DocFileItem);
                 @(IntermediateAssembly);
                 @(_DebugSymbolsIntermediatePath);
                 $(NonExistentFile);
                 @(CustomAdditionalCompileOutputs)"
          Returns="@(CscCommandLineArgs)"
          DependsOnTargets="$(CoreCompileDependsOn)"
    >
```
Which includes `$(MSBuildAllProjects)` as an input.

Why?  Because you could, for example, change preprocessor definitions or optimization options between builds, causing a project change but no source file changes.  In those case, you still need to recompile to get the right outputs!

When trying to debug incremental build issues, I recommend looking at a diagnostic-level log (from the command line or inside VS).  In this case, I saw these messages, pointing me to what I explained above:
```
Target "CoreCompile: (TargetId:44)" in file "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.Core.targets" from project "C:\Users\raines\Downloads\TestAfterCompile\TestAfterCompile\TestAfterCompile\TestAfterCompile.csproj" (target "Compile" depends on it):                                                                                                                                      
Building target "CoreCompile" completely.
Input file "C:\Users\raines\Downloads\TestAfterCompile\TestAfterCompile\TestAfterCompile\TestAfterCompile.csproj" is newer than output file "obj\Debug\TestAfterCompile.pdb".                           
```
```
Target "TrueFakeTarget: (TargetId:49)" in project "C:\Users\raines\Downloads\TestAfterCompile\TestAfterCompile\TestAfterCompile\TestAfterCompile.csproj" (target "Compile" depends on it):
Building target "TrueFakeTarget" completely.
Input file "obj\Debug\TestAfterCompile.exe" is newer than output file "C:\Users\raines\Downloads\TestAfterCompile\TestAfterCompile\TestAfterCompile\bin\Debug\TestAfterCompile.exe".
```

**Comment by rainersigwald** [comment]
Closing this on the assumption that the above was enough information.
