### ISSUE TITLE
Are C#7 local functions allowed in inline tasks?

### ISSUE THREAD

**Issue by ghost** [Microsoft/msbuild#2742]
Save the following in `csharp7.proj` and run `msbuild csharp7.proj`:

```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <UsingTask TaskName="Test" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <Task>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
          var x = 1;
          void MyTest(int y) {  }
        ]]>
      </Code>
    </Task>
  </UsingTask>

  <Target Name="RunTest" BeforeTargets="Build">
    <Test />
  </Target>

</Project>
```

throws:

> error MSB3758: An error has occurred during compilation
> error CS1513: } expected
>...

Why is this disallowed?

Comment out `void MyTest(int y) {  }`, and it works. This could be great feature for inline task where consumer wants some DRY'ing..

**Comment by rainersigwald** [comment]
The answer is "no, because `CodeTaskFactory` uses CodeDOM, which uses the old native `csc.exe` compiler, which supports only up to C# 5".

However, you can now use `RoslynCodeTaskFactory` which uses the version of the C# compiler that ships with MSBuild: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2017.

**Comment by SwooshyCueb** [comment]
What version of MSBuild comes with `RoslynCodeTaskFactory`? According to jeffkl/RoslynCodeTaskFactory@b512cd80e47a4725d66e3464f262f817773cff01 it's been built-in since 15.8, but when I try to use it on a machine with MSBuild 15.9.21+g9802d43bc3, I get the error `MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property.` Trying with Mono's version (16.0.0.0) on Linux yields similar results.

If it has indeed been in MSBuild since 15.8, what assembly is it in? I've thrown `$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll` at dotPeek and I didn't see it in there.

@rainersigwald

**Comment by rainersigwald** [comment]
@SwooshyCueb I don't see the same behavior on that version:

```xml
<Project>
  <UsingTask
    TaskName="HelloWorld"
    TaskFactory="RoslynCodeTaskFactory"
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
    <ParameterGroup />
    <Task>
      <Using Namespace="System"/>
      <Using Namespace="System.IO"/>
      <Code Type="Fragment" Language="cs">
<![CDATA[
Log.LogWarning("Hello, world!");
]]>
      </Code>
    </Task>
  </UsingTask>

 <Target Name="X">
  <HelloWorld />
 </Target>
</Project>
```

```
S:\work>msbuild codetaskfactory.proj
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/6/2019 11:43:40 AM.
Project "S:\work\codetaskfactory.proj" on node 1 (default targets).
S:\work\codetaskfactory.proj(19,3): warning : Hello, world!
Done Building Project "S:\work\codetaskfactory.proj" (default targets).


Build succeeded.

"S:\work\codetaskfactory.proj" (default target) (1) ->
(X target) ->
  S:\work\codetaskfactory.proj(19,3): warning : Hello, world!

    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.00
```

Can you file a new issue please, including

* The project you're trying to build (or a simplified repro that fails the same way)
* The exact command line and build output
* The output file generated by running https://github.com/Microsoft/msbuild/blob/master/scripts/EnumerateMSBuild.ps1

? That should help us figure out what's up.
