### ISSUE TITLE
SolutionDir is not resolved during dotnet restore

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#2743]
_From @bradphelan on October 2, 2017 14:16_

See the following repository that can reproduce the error

https://github.com/bradphelan/msbuildbug

first reported at

https://stackoverflow.com/questions/46526428/msbuild-solutiondir-resolves-incorrectly-to-c-when-running-msbuild-tresto

_Copied from original issue: dotnet/sdk#1623_

**Comment by livarcocc** [comment]
I believe this is an issue with the generated metaproj for the solution. I will move it to MSBuild for now.

**Comment by cdmihai** [comment]
This happens because the nuget owned restore target inside the metaproject generated from the solution does not propagate the same set of global properties (SolutionDir being one of them) as the hardcoded targets do (e.g. clean, build, etc).

Our recommendations, in order of preference:
-	Do not depend on SolutionDir, or any other sln dependent property. SolutionDir is only set when you are building a solution. It has no meaning when building the csproj directly (or a dirs.proj sln replacement). Best to consider the sln file deprecated. Instead, place a `directory.build.props` at the root of your repo and define a root property like <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
-	Nuget could change its solution targets to propagate the solution specific properties as global properties to the projects it builds via the MSBuild task. (in a similar way the other targets like build, clean, etc do)
-	MSBuild could change its solution handling code to set those properties as global properties when building the metaproj. This eliminates the need for every sln extension to manually propagate them. On the other hand, this has a higher chance to break something somewhere.

**Comment by soroshsabz** [comment]
I think Microsoft must be careful about backward compatibility and care for good feature and facilities, so something like $(solutiondir) can be built-in defined variable in build system. or can be exists in solution templates in visual studio or other IDE

**Comment by MasterMann** [comment]
This impacts my current workflow as well, including `dotnet restore/build/publish` (https://github.com/dotnet/sdk/issues/46990) and MSBuild "Copy" task, `SolutionDir` in those is completely ignored, it's only valid in "Exec" tasks (so far from what I've been trying).
