### ISSUE TITLE
Consider renaming MSBuild.exe to msbuild.exe

### ISSUE THREAD

**Issue by akoeplinger** [Microsoft/msbuild#275]
The latter is easier to work with on case-sensitive OSes.

**Comment by monoman** [comment]
:+1:

**Comment by jonpryor** [comment]
Please don't; it shouldn't matter.

The only way it would matter is if you setup your system to directly execute PE binaries. This, however, is *stupid*, because there are *lots* of PE handlers (Wine, mono, CoreCLR), and (at least on Linux) you can't have more than one handler for a given file type.

Meaning `MSBuild.exe` from a shell *won't work anyway*. Meaning the casing is *moot*; it's irrelevant.

For non-Windows support, you really want to use a [shell script][shell-script], which you can then case however you want, and skip the extension for good measure, e.g. name the script `msbuild`.

[shell-script]: http://www.mono-project.com/archived/guiderunning_mono_applications/#shell-scripts

**Comment by akoeplinger** [comment]
@jonpryor I know and fully agree with that, that wasn't my point though (should've been clearer in my first post).

I'm seeing lots of code like [this](https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeCommandLine/UnitTests/XMake_Tests.cs#L593-L594) that relies on the casing of the exe for finding stuff. People do weird things all the time and given the new xplat focus I thought it'd make life easier for everyone if we standardized on all-lowercase exe/config names (or you end up with bugs like in NuGet3 where they now look for NuGet.config instead of NuGet.Config which breaks Linux, something they're hopefully fixing soon).

I don't feel strongly about this at all, just wanted to hear the MSBuild team's opinion on this :smile:

**Comment by rainersigwald** [comment]
We should definitely standardize on casing for internal use, and that should be on the case that we produce.  @cdmihai started down that road a bit when working on some of the command-line tests.

As to changing the casing to be all lowercase, I am not strongly opposed (certainly I've never capitalized it when typing it on a command line) but I am fairly convinced by @jonpryor's case that it's irrelevant.

We'd be glad to hear more input either way from folks who live in case-sensitive worlds!
