### ISSUE TITLE
Passing a logger has large overhead even if it only monitors low frequency events

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#2769]
This is having a huge impact (400+ ms) on basic CLI scenarios

### Steps to reproduce

1. Create an empty logger that subscribes to none of the events

```C#
using Microsoft.Build.Framework;

public class EmptyLogger : ILogger
{
    public LoggerVerbosity Verbosity { get; set; }
    public string Parameters { get; set; }
    public void Initialize(IEventSource eventSource) {}
    public void Shutdown() {}
}
```

2. Measure build with and without empty logger

## .NET Core
```
> Measure-Command {dotnet 'C:\Program Files\dotnet\sdk\2.1.1\MSBuild.dll' /m /v:m}
TotalMilliseconds : 1555.4208

> Measure-Command {dotnet 'C:\Program Files\dotnet\sdk\2.1.1\MSBuild.dll' /m /v:m /logger:EmptyLogger,EmptyLogger.dll} 
TotalMilliseconds : 2012.9251
```

## .NET Framework
```
> Measure-Command {msbuild /m /v:m} | findstr TotalMil
TotalMilliseconds : 974.4459

> Measure-Command {msbuild /m /v:m /logger:EmptyLogger,EmptyLogger.dll}
TotalMilliseconds : 1083.5906
```

**Comment by mikeharder** [comment]
This appears to scale with solution size.  It accounts for 40% of the incremental build time for https://github.com/OrchardCMS/OrchardCore (127 projects):

```
> Measure-Command {dotnet 'C:\Program Files\dotnet\sdk\2.2.0-preview1-007556\MSBuild.dll' /m /v:m}
TotalSeconds : 15.6

> Measure-Command {dotnet 'C:\Program Files\dotnet\sdk\2.2.0-preview1-007556\MSBuild.dll' /m /v:m /logger:EmptyLogger,EmptyLogger.dll} 
TotalSeconds : 25.4
```

**Comment by AndyGerlicher** [comment]
https://docs.microsoft.com/en-us/visualstudio/msbuild/writing-multi-processor-aware-loggers

That article has a decent summary of what's going on here. Basically if you care about perf and don't want all events, never write an `ILogger`. If you make it a `INodeLogger` and use a forwarding logger (either your own or built-in `ConfigurableForwardingLogger`) you will get much better performance. CLI was probably worst-case scenario where it only cared about a handful of events but adding a logger with `/logger` introduced all the overhead of IPC for every message sent by the build.

See https://github.com/dotnet/cli/pull/8371 for the solution for the dotnet CLI.

What MSBuild really needs to do is make this easier to implement. Ideally record events that you subscribe to on the `EventSource` in an `ILogger` and configure a forwarding logger for you. In most cases that would let you achieve the same result without the hassle of the extra class and confusing syntax.

For something like the binary logger (@KirillOsenkov), I think we either accept the perf cost since it must have every event, or we have the individual nodes write out logging directly and aggregate together it at the end. Probably not worth it for the latter, but I think this is useful information to keep in mind.

**Comment by rainersigwald** [comment]
For the "have the individual nodes write out logging directly" there's some precedent in the `/distributedFileLogger` switch, which does just that (but doesn't aggregate back).
