### ISSUE TITLE
MSBuild treats unqualified metadata case sensitive

### ISSUE THREAD

**Issue by chm-tm** [Microsoft/msbuild#2870]
### Steps to reproduce

Project file
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" >
  <ItemGroup>
    <Foo Include="Foo">
      <SENSITIVE>X</SENSITIVE>
    </Foo>
  </ItemGroup>
  <Target Name="Build">
    
    <Message Importance="high" Text="%(Foo.FileName)=%(Foo.sensitive)"/>
    <!-- Output: Foo=X -->
    
    <Message Importance="high" Text="%(Foo.FileName)=%(sensitive)"/>
    <!-- error MSB4096: The item "Foo" in item list "Foo" does not define a value for metadata "sensitive".  
                        In order to use this metadata, either qualify it by specifying %(Foo.sensitive), or ensure that
                        all items in this list define a value for this metadata. -->
  </Target>
</Project>
```

Command line
```
msbuild
```
### Expected  behavior
Outputs `Foo=X` twice

### Actual behavior
Fails with MSB4096

### Environment data
`msbuild /version` output: 15.5.180.51428. Also tested with MSBuild from .NET 4.0.

OS info: Windows 10 1703

**Comment by rainersigwald** [comment]
Nice repro. I confirmed on 15.6.54.

**Comment by MeikTranel** [comment]
Hey, i would like to do this, if that's ok?

**Comment by rainersigwald** [comment]
That'd be great @MeikTranel. Do you have a good idea about how to get started?

**Comment by MeikTranel** [comment]
I wrote me a nice test to explore if I even feel like I can solve this before grabbing the issue. 
Lots of cool but sketchy performance shortcuts. 
I think I identified the issue already, I'm just not quite sure what's the best way to solve it.

I have 10 days of vacation in front of me, so I'm gonna have time to dive into this coming from work tomorrow. I have questions already but I'm currently not at home. 

I suggest you just check back in Saturday or Monday; I'll be able to be specific having the code in front of me not on mobile :smile:

**Comment by MeikTranel** [comment]
So i wrote down @chm-tm's spec as a test, which covers the issue perfectly like you said, @rainersigwald. See:

```csharp
[Fact]
public void ItemMetadataIsEvaluatedCaseInsensitively()
{
    var projectContents =
    @"<Project>
        <ItemGroup>
            <Foo Include=`Foo`>
                <SensitiVE>X</SensitiVE>
            </Foo>
        </ItemGroup>
        <Target Name=`AccessItemMetadata`>
            <CreateProperty Value=`%(Foo.FileName)=%(Foo.sensitive)`>  
                <Output TaskParameter=`Value` PropertyName=`Qualified` />  
            </CreateProperty>          
            <CreateProperty Value=`%(Foo.FileName)=%(sensitive)`>  
                <Output TaskParameter=`Value` PropertyName=`Unqualified` />  
            </CreateProperty>  
        </Target>
    </Project>".Cleanup();
    ProjectInstance project = new Project(
        XmlReader.Create(
            new StringReader(projectContents)
        )
    ).CreateProjectInstance();

    project.Build();

    Assert.NotNull(project.GetProperty("Qualified"));
    Assert.NotNull(project.GetProperty("Unqualified"));            
}
```

From that you can gather that the error the user is facing is thrown here:
https://github.com/Microsoft/msbuild/blob/d136a42365dba0e6fe5f96dbd0ee4ba6ca77aa8b/src/Build/BackEnd/Components/RequestBuilder/BatchingEngine.cs#L251-L272

The project verification error is thrown given ITaskItem.HasMetadata returns false.

If you step in there you'll see that this call just ends up doing a regular "Contains()" on the collection which in this case does not compare strings at all.

I'm not quite sure yet if this fixes the underlying issue yet, but the test i wrote would be satisfied with a simple OrdinalIgnoreCase search loop over _directMetadata. But i would really like to dig a little deeper, there's another bug hidden in here that haven't quite captured yet. Also adding a loop without having done any further consideration would be regression. Especially in between Big-O notated code :smile:

**Comment by rainersigwald** [comment]
@MeikTranel Nice! I believe the `CopyOnWritePropertyDictionary` should use `MSBuildNameIgnoreCaseComparer.Default` as its comparer, but maybe it's not for some reason?

**Comment by MeikTranel** [comment]
That's where i'm trying to get to, yes (mostly because of the optimized stringcomparer, which looked cool).

I'll update you tomorrow. Today -> some more sweet csgo 😄

**Comment by MeikTranel** [comment]
I pushed a branch you could look at, but it's still WIP: https://github.com/Microsoft/msbuild/compare/master...MeikTranel:UnqualifiedMetadataCaseSensitivityFix

_(I am not supposed to open a WIP PR according to dotnet contribution rules)_

I have to confirm that this doesn't just work for the specific repro @chm-tm gave us, because not all metadata is created equal.

**Comment by MeikTranel** [comment]
@rainersigwald So i tested all kinds of item metadata types (Metadata inherited through ItemDefinitionGroup, Well-known Metadata and direct metadata) and verified that all of them follow through with the expected behavior, by writing tests for each of them individually. Metadata cloned from ItemDefinitionGroup and Well-Known Metadata already worked with unqualified case insensitive metadata references.

Now the question is, should it commit those tests to the PR? Technically speaking these do not directly relate to the issue, given that it wasn't specifically asked for and they did work without my fix.

I'm specifically asking because of this particular piece of code:
https://github.com/Microsoft/msbuild/blob/33d52b4fa5b509ff4f3c50f406819e332f32eb65/src/Build/Instance/ProjectItemInstance.cs#L1528-L1538

As you can see, the different kinds of metadata go along completely different paths of evaluation before actually being tested case insensitively (each of them in another way). That's why i'd personally prefer covering the whole spec: "Unqualified & Qualified item metadata is evaluated case insensitively"

What do you think?

**Comment by rainersigwald** [comment]
We'd love to have more tests, even if they're already passing. Feel free to open up a WIP PR if you'd like -- we use wipbot, so if the title contains `WIP` we won't accidentally merge it, and you can ping me explicitly when you're ready for a detailed review.
