### ISSUE TITLE
Failing and ignored tests

### ISSUE THREAD

**Issue by RadoslavCap** [Microsoft/msbuild#30]
Steps to reproduce:

1. Clone repository
2. Build solution
3. Run unit tests
4. There are 9 failing tests, 349 ignored tests

Expected result: all tests will be green.

I can add more technical details if needed
![failingtests](https://cloud.githubusercontent.com/assets/6508800/6754344/37661ad0-cf1c-11e4-9b09-b36a61d0bf80.PNG)

**Comment by am11** [comment]
My results are varying. Only one assertion fails: [ToolLocationHelper_Tests.cs#L804](https://github.com/Microsoft/msbuild/blob/82177a50da735cc0443ac10fa490d69368403d71/src/Utilities/UnitTests/ToolLocationHelper_Tests.cs#L804).

However, there are 227 skipped tests, which is due to the `[Ignore]` attribute which explicitly disables a test case: https://msdn.microsoft.com/en-us/library/ms182457.aspx.

Ex: [ProjectRootElementCache_Tests.cs#L108](https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/UnitTests/Evaluation/ProjectRootElementCache_Tests.cs#L108):
```
[Ignore] // "This test seems to be flaky depending on when garbage collection happened"
```

**Comment by barbosatek** [comment]
Seems some of the tests are failing because of threading issues when running all the tests.

![image](https://cloud.githubusercontent.com/assets/988127/6782703/e95c7172-d132-11e4-847c-26ffa46af388.png)

After running only the 4 failing tests, only one fails:

![image](https://cloud.githubusercontent.com/assets/988127/6782740/339379b6-d133-11e4-8200-5ab9bda963fb.png)

Which actually fails because it's expecting my enviroment to be Windows 10 rather than Wondows 8.1
```
Test Name:	GetPathToDotNetFrameworkSdk
Test FullName:	Microsoft.Build.UnitTests.ToolLocationHelper_Tests.GetPathToDotNetFrameworkSdk
Test Source:	c:\Users\v-hobarb\Documents\GitHub\msbuild\src\Utilities\UnitTests\ToolLocationHelper_Tests.cs : line 750
Test Outcome:	Failed
Test Duration:	0:00:00.0298146

Result Message:	Assert.AreEqual failed. Expected:<C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\>. Actual:<C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\>.
Result StackTrace:	at Microsoft.Build.UnitTests.ToolLocationHelper_Tests.GetPathToDotNetFrameworkSdk() in c:\Users\v-hobarb\Documents\GitHub\msbuild\src\Utilities\UnitTests\ToolLocationHelper_Tests.cs:line 804
```

**Comment by AndyGerlicher** [comment]
All the tests that are not marked with [Ignore] should be working. There are quite a few I had to disable migrating it out of our internal environment though. Most of those are tagged with a comment like `// Ignore: Test requires installed toolset.`. Ideally all the tests should be enabled (or deleted if they don't apply anymore), so we are definitely open to PR for fixes there :).

The biggest difficulty was that the tests often targeted the version of MSBuild that is installed on your machine in the GAC. We had a cmd file to update the machine so that you would be (hopefully) testing what you just built and not the retail version, but this is definitely not ideal. This has been around and not changed for ages, so we couldn't get to all of them. And without doing some sort of [signing](https://github.com/Microsoft/msbuild/wiki/Microsoft.Build.Framework) that method doesn't work anyway.

If you do have specific issues I'd like to see more information and if it repros running the test by itself or not. The machine I used for the majority of the testing was Windows 10 Server (9926) and Visual Studio 2015 (CTP6).
