### ISSUE TITLE
MSBuild Mono Support

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#302]
Creating this issue to have an open discussion and get community input for our support of mono. We have made use of the `xplat` branch to support the .NET Core Framework and many features that don't work yet (or don't make sense anymore) are compiled out based on configuration. Our [roadmap](/Microsoft/msbuild/wiki/Roadmap) does not include any changes for mono, so we would like input on where to go from here. Some options:
1. Create a new `xplat-mono` branch from the LKG(@f9d8cc725ca2cd46d7e01015afba0defea95ce37) and continue to maintain a fork focused on supporting mono.
2. Continue to include support for mono in the current `xplat` branch alongside .NET Core. Currently our top priority is supporting .NET Core, so support will be somewhat limited.
3. Others options?

**Comment by migueldeicaza** [comment]
What we would l like to see for Mono is an msbuild that is able to build existing projects (this being the key feature that people want), and one that we could consume as an API from IDEs where necessary.

It is hard to tell from the roadmap if the xbuild branch is actively removing features, that information would be very useful.

I believe we can alter our IDEs and to depend on a NuGetized version of Msbuild, so that should not be a problem.

**Comment by dsplaisted** [comment]
In the xplat branch, we have removed a bunch of functionality for the .NET Core version of MSBuild.  However, the code is just `#if`'d out for the .NET Core configurations, so the Mono and .NET Framework configurations should continue with the same features.
