### ISSUE TITLE
Avoid crosstalk between same-MSBuild-but-different-SDKs nodes

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#3137]
~We should add the environment variables `DOTNET_HOST_PATH` and `DOTNET_ROOT` to the node-compatibility handshake computation.~

### Steps to reproduce

* Have two copies of the .NET Core SDK that use the same version of MSBuild but that aren't identical
* Run a build with copy A (created nodes will wait for reuse after the build completes)
* Run a build with copy B

### Expected  behavior

The build in copy B's dotnet host does not reuse nodes from copy A

### Actual behavior

This will be mostly true now, because the handshake includes `AssemblyTimestamp` which is `LastWriteTime` which will _probably_ be distinct, but isn't necessarily.

**Comment by ericstj** [comment]
@viktorhofer and I just noticed this with two clones of repositories which have a local copy of a CLI (eg: .dotnet folder).  One repo will reuse nodes from another, resulting in errors if they consume different task DLLs (or different SDKs).  I've also had to field a number of issues from various teams hitting similar problems.

Can you just use the full path to msbuild assembly rather than considering environment variables?

**Comment by japj** [comment]
I have a somewhat related situation where the mentioned MSBUILD_ISOLATION_KEY proposal might work/be useful.

MSBuild.exe A.sln with different projects
    MSBuild.exe  Node 1
    MSBuild.exe  Node 2
    MSBuild.exe  Node 3
       Cmd.exe running an external command that calls MSBuild
           MSBuild.exe for B.sln

Is it possible to have MSBuild for B.sln to connect to/reuse Node 1 and 2 for building B.sln instead of spawning its own child nodes?

Or would this break things in weird ways?

**Comment by rainersigwald** [comment]
@japj, is the `msbuild.exe` invocation for `B.sln` happening inside a task started by the `A.sln` build? If so, you should already be fine, because nodes 1, 2, and 3 should still be busy and not accepting new connections for the duration of the `A.sln` build.

**Comment by rainersigwald** [comment]
Also, I think you might be interested in microsoft/msbuild#4337 :)

**Comment by ericstj** [comment]
Interesting, I think #4337 would solve our problem.  We could use the path to the local .dotnet folder as the salt.  Seems like a reasonable arcade change.
