### ISSUE TITLE
Node reuse locks task assembly file

### ISSUE THREAD

**Issue by natemcmaster** [microsoft/msbuild#3141]
We have build scripts that produce tasks as a local assembly. These assembly files are locked by the nodes, which means we can't use nodeReuse on repos that use custom local tasks.

### Steps to reproduce

1. Git clone https://github.com/aspnet/BuildTools/tree/6e2c86240ffd0056d202eb8ede1fba1e251804b4
2. `build.cmd /p:SkipTests=true`
3. `build.cmd /p:SkipTests=true`

### Expected  behavior
It would be great if nodeReuse was savvy enough to handle changes to task assemblies on disk.

### Actual behavior
```
C:\Users\namc\.dotnet\x64\sdk\2.1.300-preview2-008396\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(137,5): warning MSB3026: Could not copy "obj\Release\netcoreapp2.0\RepoTasks.dll" to "C:\dev\aspnet\BuildTools\build\tasks\bin\publish\RepoTasks.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\dev\aspnet\BuildTools\build\tasks\bin\publish\RepoTasks.dll' because it is being used by another process.  [C:\dev\aspnet\BuildTools\build\tasks\RepoTasks.csproj]
```

The process locking the file is
```
C:\Users\namc\.dotnet\x64\dotnet.exe "C:\Users\namc\.dotnet\x64\sdk\2.1.300-preview2-008396\MSBuild.dll" C:\Users\namc\.dotnet\x64\sdk\2.1.300-preview2-008396\MSBuild.dll /nologo /nodemode:1 /nodeReuse:true
```

### Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008396
 Commit:    400e670faa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\namc\.dotnet\x64\sdk\2.1.300-preview2-008396\
```

## Workaround
```
build.cmd /nodeReuse:false
```

**Comment by rainersigwald** [comment]
This would be great but AFAIK it's impossible as .NET Core doesn't provide any way to unload an assembly.

**Comment by rainersigwald** [comment]
One way to improve the current situation would be to shut task host nodes down immediately after they run their task.

Today, you can force execution of a task into another process by specifying `TaskFactory="TaskHostFactory"` in its `UsingTask` declaration. Today, that process lives long past the initial build and may be reused, causing the task assemblies to be locked for a long time, so a subsequent build can't update them.

Related (I thought this was already the case and was wrong): https://github.com/microsoft/msbuild/issues/2916#issuecomment-360897413

If using the already-slow "isolate this task into its own process" flag also implied "and terminate that process when it's done", we could advise people who use tasks built in their own repo to use it, which would help a lot with this annoyance.

I'm going to tentatively put this in 16.6 since it keeps coming up (see also #4743).

[task-locks-task-assembly-forever.zip](https://github.com/microsoft/msbuild/files/4104717/task-locks-task-assembly-forever.zip)
