### ISSUE TITLE
Microsoft.Build.Commontypes.xsd contains PackageTargetFallback but not AssetTargetFallback

### ISSUE THREAD

**Issue by ericstj** [microsoft/msbuild#3292]
/cc @mairaw @emgarten @dsplaisted 
Related https://github.com/dotnet/docs/issues/2816

I believe we recommend using AssetTargetFallback over PackageTargetFallback since it behaves better considering the entire package's asset groups rather than just evaluating it independently.

**Comment by emgarten** [comment]
//cc @mishra14

**Comment by dsplaisted** [comment]
I'd suggest removing PackageTargetFallback from the intellisense, since it can behave in ways you wouldn't expect.

I'm not sure at this point whether we should add AssetTargetFallback to the intellisense though.  Hopefully by now it's not common to need to use it (we set it automatically to enable referencing .NET Framework projects from .NET Core / .NET Standard, but that doesn't mean people need to put it in their projects).

**Comment by rainersigwald** [comment]
It'll be required to support build-only (no reference) `ProjectReference`s, unfortunately, so I think it probably needs to go in.
