### ISSUE TITLE
TargetPath not available when multi-targeting with netstandard2.0

### ISSUE THREAD

**Issue by mcphlen** [Microsoft/msbuild#3422]
### Steps to reproduce

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net46;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```

Code line
```
var filename = "multi-target-project"
var projCollection = new ProjectCollection();
var project = _projCollection.LoadProject(filename);
var targetPathProp = msProj.GetProperty("TargetPath")
```
### Expected  behavior
targetPathProp should not be null

### Actual behavior
targetPathProp is null

### Environment data
`msbuild /version` output:
15.7.177.53362
OS info:
Windows 10 Entreprise Version 1703 
OS Build 15063.1088
If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Visual Studio 2017 
Version 15.7.1

**Comment by rainersigwald** [comment]
This is by design for multitargeting projects. There's no single `TargetPath`, because there are multiple outputs of the project. You'll have to set the appropriate properties to tell the project _which target_ you're interested in.

This is discussed in a bit more detail in https://github.com/Microsoft/msbuild/issues/3202#issuecomment-382020506.
