### ISSUE TITLE
Where can I find all available MSBuild targets?

### ISSUE THREAD

**Issue by lecoque** [Microsoft/msbuild#3456]
For example `<Target Name="CopyPackage" AfterTargets="Pack">` is there any list of all available built-in targets I can use with `AfterTargets`?

https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md#target-build-order

> Because pack and restore are MSBuild targets, you can access them to enhance your workflow.

Is there any cheatsheet or something like that where I can see all the targets I can use?

I found this: https://gist.github.com/StevenLiekens/cae70cce25344ba47b86 but it doesn't include "Pack" and "Restore".

**Comment by rainersigwald** [comment]
This is not answerable in a nice general way, because any NuGet package, SDK, project, or import can define its own custom targets. In addition, there's no requirement that projects import `Microsoft.Common.targets`, so there's not even a common base of targets that you can 100% rely on.

The best way to see what targets are available in _your specific_ project is to [preprocess](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference#preprocess) it to a file and look for `<Target` elements. There's also an outstanding request to have a command-line option to list targets (#33) that hasn't bubbled up in priority yet.
