### ISSUE TITLE
RAR logs two \0 bytes at the end of ImageRuntime = v4.0.30319\0\0

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#3466]
@dsplaisted has reported a build where the log from RAR contains two zero bytes at the end of the ImageRuntime metadata value. Example:
![image](https://user-images.githubusercontent.com/679326/42117171-119d2246-7bb0-11e8-9848-7eedb53f7973.png)

We need to investigate where those two zero bytes come from. I've seen this a few times in the logs. Present both in text logs and binlog.

**Comment by danmosemsft** [comment]
The problem is here
https://github.com/Microsoft/msbuild/blob/b2db71bebaae4f54f7236ca303e2b0a14aca1a0d/src/Tasks/AssemblyDependency/AssemblyInformation.cs#L1010-L1023

in ECMA335 it says about the length
```
Number of bytes allocated to hold version string (including
null terminator), call this x.
Call the length of the string (including the terminator) m (we
require m <= 255); the length x is m rounded up to a multiple
of four.
```
In this case the length in the header is 12 including null which we are using verbatim but it was 11 rounded to 12.
```
sr.ReadBytes(length)
{byte[12]}
    [0]: 118
    [1]: 52
    [2]: 46
    [3]: 48
    [4]: 46
    [5]: 51
    [6]: 48
    [7]: 51
    [8]: 49
    [9]: 57
    [10]: 0
    [11]: 0
```
We should simply trim `\0` here.

The code is otherwise working fine because aside from logging it is used as a `Version` which parses successfully because the last segment is consumed with `Int.Parse` and that due to compatibility reasons ignores trailing nulls.
https://github.com/dotnet/coreclr/blob/b00f12ce4457fc013efce340011b4759e78f9948/src/System.Private.CoreLib/shared/System/Number.Parsing.cs#L1876
