### ISSUE TITLE
MSBuild searches property in the wrong path

### ISSUE THREAD

**Issue by Luberen** [Microsoft/msbuild#3467]
I'm trying to use MSBuild with `.vcxproj` file.
I made sample project in my own directory, but MSBuild searches `Microsoft.Cpp.Default.props` always in `C:` instead of the sample project's path.

Attempted behavior:
In the project folder, type `MSBuild <project name>.vcxrpoj` on command prompt.

The error message:
**error MSB4019: The import project "C:\Microsoft.Cpp.Default.props" was not found.**

I attached my `.vcxproj` file.
[VisuAlgoProject.zip](https://github.com/Microsoft/msbuild/files/2151532/VisuAlgoProject.zip)

### Environment data
`msbuild /version` output: 4.7.3056.0

OS info: Windows 10

**Comment by rainersigwald** [comment]
To expand a bit: you're using MSBuild `4.7.3056.0` -- that's a very old version that shipped in the .NET Framework. The `vcxproj` includes `ToolsVersion="15.0"`, so you need to use a new version of MSBuild to understand the project (and know where to find the C++ tooling).

Launching a `Developer Command Prompt for VS 2017` window should set up `%PATH%` and some other variables appropriately so you get the right MSBuild.

I'm going to close this, because I have pretty high confidence that this is the problem. If you try these suggestions and think otherwise please comment and we can reopen this issue.
