### ISSUE TITLE
Copy task should log absolute file paths

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#3505]
Currently Copy task logs relative file paths, and sometimes this is ambiguous. To properly reason about double-writes we'd need the Copy task to call Path.GetFullPath() on all paths for source and destination before logging them.

See https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/180

**Comment by rainersigwald** [comment]
Seems reasonable to me. It's rare to change a project's CWD, so it's _almost_ possible to disambiguate by combining with the project path folder. But it's possible to change working directory.

**Comment by geeeyetee** [comment]
In addition to ensuring absolute path in the log, I think it makes sense to do the same in the `Identity` of `CopiedFiles` output items. If that presents too much risk of breaking existing scripts, a new metadata key (`AbsolutePath`?) could be added to `CopiedFiles` output items.

**Comment by rainersigwald** [comment]
@geeeyetee There's already an automatic `%(FullPath)` metadatum; it's computed on demand rather than added to the item directly.

I'm definitely leery of changing `%(Identity)` of the output; those are usually relative paths and it's very hard to predict what would break on such a change.

**Comment by geeeyetee** [comment]
@rainersigwald How silly of me. I had been staring myopically at output using _MSBuild Structured Log Viewer_. Your explanation of the on-demand nature of `%(FullPath)` explains why a log viewer would not be able to display it alongside other metadata.

Agreed that changing `%(Identity)` of the output would likely break stuff-- and for no real gain since during build `%(FullPath)` is available.
