### ISSUE TITLE
MSBuild won't honor suppressed code analyzer warnings

### ISSUE THREAD

**Issue by twenzel** [Microsoft/msbuild#391]
I'm using a (Roslyn) Code Analyzer in our projects (per NuGet). 
For some projects I changed the severity of the analyzer to "Hidden" by right click on the analyzer within the solution tree in Visual Studio and choose "Set Rule Set Severity -> Hidden". VS creates a new <projectname>.ruleset file for this project. Now all warnings are gone in Visual Studio.

But when I'm building this solution with MSBuild from command line the warnings still appear.
Is this a bug? Or how can I disable a particular analyzer that will be honored in VS and MSBuild command line?

**Comment by rainersigwald** [comment]
When you set that setting through VS, is there any change in the MSBuild .csproj file?  Or is the only result the creation of the .ruleset file?  It [looks like](https://github.com/dotnet/roslyn/blob/master/docs/compilers/Rule%20Set%20Format.md#msbuild-projects) there should be an addition to the .csproj file (which the Roslyn targets presumably use when calling csc).

I can see a few possibilities as to where the problem is:
* The `CodeAnalysisRuleSet` property isn't getting set in the project file (problem in VS).
* The property is getting set, but isn't honored on the command line (problem in the Roslyn C# targets).
* The property is getting set and used but something's going wrong (problem in MSBuild itself).

That last option seems pretty unlikely--property propagation is pretty stable.

**Comment by twenzel** [comment]
The `CodeAnalysisRuleSet` property was set properly in the project file.

**Comment by twenzel** [comment]
The output window in VS also shows the warnings when rebuilding the project. Only the "Error List" pane in VS suppresses the warnings.

**Comment by rainersigwald** [comment]
Ok, since the warnings are appearing in MSBuild's VS output, I think this is a behavior-of-Roslyn-analyzers question that would be best asked of the Roslyn folks at https://github.com/dotnet/roslyn.

**Comment by mavasani** [comment]
@twenzel Did you do a save your project file after setting the new severity? I have accidentally run into this many times myself. If you did do a save, then can you also verify that the ruleset property matches your build configuration? The command Set Rule Set Severity sets the CodeAnalysisRuleSet only for Debug and Release severities, and if you are building for a different config, then the ruleset will not be honored. See the discussion here: https://github.com/dotnet/roslyn/issues/6774#issuecomment-156587979

**Comment by twenzel** [comment]
I checked out that the problem occurs on our build server only. 
On another "clean" machine with MS Build Tools installed this problem does not occur.
So I guess there is a corrupt MSBuild installation or a misconfiguration done by myself.
