### ISSUE TITLE
Auto restore packages before build in vs2017 

### ISSUE THREAD

**Issue by moh-hassan** [Microsoft/msbuild#3920]
I use vs2017.8 project with the new style SDK with `PackageReference` 

Every time when I modify TargetFrameworks  in csproj/vs2017.8, and try to build the project from within vs2017 IDE, i get the error:

>Error	NETSDK1005	Assets file 'F:\projects\PaketDemo\PaketDemo\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.1'. Ensure that restore has run and that you have included 'netcoreapp2.1' in the TargetFrameworks for your project.	PaketDemo	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	

Also, when trying to build from Package Manager Console:

		msbuild /t:build
I get the same error.

I can build and auto restore by the command:

                dotnet build    //auto restore packages and build project but has no effect on MSBuild or vs2017

'dotnet build' has no effect on MSBuild  or vs2017 for package restore and i should restore it.

The only way to restore the packages, I run the command:		
  
		msbuild /t:restore

How to auto restore the packages before build in vs2017	 when modifying `TargetFrameworks`   without running the task `msbuild /t:restore` ?

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#7500

**Comment by WeihanLi** [comment]
I think it's maybe much more efficient if `nuget restore` executed before `msbuild`, just like `dotnet build`.

I've met the problem that when I build the project it'll failed to build in Visual Studio because some packages may not be restored, while I run `dotnet build` in the command line, it'll restore the packages firstly and then build the project.

If I set the auto restore packages true in vs nuget options, it'll cause the Visual Studio to be too busy.

So I'm wondering if it can be done in Visual Studio, should I open a issue in somewhere about Visual Studio ? @rainersigwald
