### ISSUE TITLE
Repoint SDK40ToolsPath to 4.7.2 registry location

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#4049]
_This was reported internally as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753670._

On a machine with VS installed but no .NET 4.6.1 SDK, `$(SDK40ToolsPath)` is empty, because

https://github.com/Microsoft/msbuild/blob/9781d968839ded744e18152f991d21eb6ce83862/src/MSBuild/app.config#L84

doesn't exist.

I think the 4.6.1 SDK was universally installed for dev15, but dev16 now universally installs the 4.7.2 SDK, so we should update to point to that instead.

**Comment by steffen-wilke** [comment]
I was about to open similar issue when I found this, good timing on your side :)

A related issue that I've fought with this morning was to get the creation of localized satellite assemblies running on our **Docker Based Build Servers**. I'm using the [microsoft/dotnet-framework:4.7.2-sdk-20181211-windowsservercore-ltsc2016](https://github.com/Microsoft/dotnet-framework-docker/blob/master/4.7.2/sdk/windowsservercore-ltsc2016/Dockerfile) Docker image as a base for our build containers.

And our build process resulted in the outcome:

```
> You should have .NET 4.7.2 SDK installed.
> Can't create the satellite assembly dll.
> .NET 4.7.2 framework tools not found. Make sure that .NET framework has been installed.
> "AL.exe" file does not exist.
```

Installing **Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools** from the [vs_buildtools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017) to the image fixed the issue for me. This seems to be the [Component](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017) that also installs the .NET 4.6.1 SDK to the machine.

While only building .NET 4.7.2 projects, out build servers also have to have .NET 4.6.1 SDK installed at the moment which is a bit inconvenient.

Another example of this problem is the usage of the **resgen.exe** while building our solutions which is being accessed from the path `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\resgen.exe`.

Maybe the Microsoft .NET 4.7.2 SDK Docker Images should be extended with the required .NET 4.6.1 SDK by default.

**Comment by rainersigwald** [comment]
> Maybe the Microsoft .NET 4.7.2 SDK Docker Images should be extended with the required .NET 4.6.1 SDK by default.

That sounds reasonable to me. I filed Microsoft/dotnet-framework-docker#214 to see if it seems reasonable to the Dockerfile owners.

Thanks for the report and additional details!

**Comment by kernelcoredump** [comment]
Should a similar fix to https://github.com/Microsoft/msbuild/pull/4052 be applied to the 4.8 images (but using the 4.8 registry location)?
