### ISSUE TITLE
MSBuild ignores assembly binding in web.config

### ISSUE THREAD

**Issue by twenzel** [microsoft/msbuild#420]
I've the same problem as described here: http://stackoverflow.com/questions/34271216/msbuild-step-in-teamcity-considers-app-config-instead-of-web-config-for-asp-net 
and here 
http://stackoverflow.com/questions/34292288/how-does-msbuild-finds-bindingredirect-attributes-for-asp-net-projects

When executing MSBuild on our build server it shows me the warnings. When executing MSBuild on my dev machine (Visual Studio installed) the warnings won't show up.

How should I configure our build server to retrieve the binding redirection information from the web.config instead of from the app.config?

**Comment by twenzel** [comment]
Maybe this is the same problem: https://social.msdn.microsoft.com/Forums/de-DE/70c0753c-a644-4463-a830-1637bec27cf6/visual-studio-tools-version-14-tv140-throws-microsoftcommoncurrentversiontargets-error-on

Do I need install the ```Microsoft ASP.NET and Web Tools 2015```?

**Comment by MaceWindu** [comment]
In our project we just store copy of required files in repository, because I'm not a fan to install a lot of prerequisites just for build.
We copied those two folders:
c:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\
c:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\
and changed path to c:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets to new location.

**Comment by twenzel** [comment]
Thanks. That helped me.
But this is just a workaround for this issue.

**Comment by rainersigwald** [comment]
It looks like installing the ASP.NET workload is the right fix for this problem.
