### ISSUE TITLE
T4 templates ignored when msbuild called on multi-framework project

### ISSUE THREAD

**Issue by borrrden** [Microsoft/msbuild#4225]
### Steps to reproduce

Project file
[TextTemplateFailure.zip](https://github.com/Microsoft/msbuild/files/2949137/TextTemplateFailure.zip)

Command line
```
msbuild /t:TransformAll
```
### Expected  behavior

Templates are transformed

### Actual behavior

Templates are ignored, even if specified via /p:TransformFile.  Note that change from `TargetFrameworks` to `TargetFramework` works, as well as calling TextTransform.exe directly.

### Environment data
`msbuild /version` output:

```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.21.664
```

**Comment by livarcocc** [comment]
@nguerrera @dsplaisted are you folks aware of any issues here?

**Comment by livarcocc** [comment]
@borrrden T4 is not supported for .NET Core. The fact that you got it working for a single TFM, as indicated by yourself in your project file, is a HACK.

Now, this likely does not work for multi-tfm because when the T4 target runs as part of the outer loop, there are no compile items available. You would need to make the target run as part of the inner loop for that to work. However, I haven't tried and am not sure of the details of what would need to happen for this to work.

**Comment by borrrden** [comment]
Is there a replacement that should be used instead?  I assume the issue is the lack of executable on non-Windows right? For what it’s worth if anyone else is trying it the new way I am doing it is by calling the text transform exes directly via custom target.
