### ISSUE TITLE
Inconsistency in item expansion

### ISSUE THREAD

**Issue by ltrzesniewski** [Microsoft/msbuild#4305]
I'm not really sure if it's a bug or by design, but I've found an inconsistency in how properties are expanded to items.

It looks like they don't get split on `;` if you use a property function in the expression, unless you do that manually with `string.Split`.

If this is by design, is this documented somewhere? The closest documentation I could find was [there](https://docs.microsoft.com/en-us/visualstudio/msbuild/comparing-properties-and-items?view=vs-2019#conversions-between-strings-and-item-lists) but it doesn't go into details.

### Steps to reproduce

Build this:

```xml
<Project InitialTargets="Build">
  <PropertyGroup>
    <PropA>foo;bar;baz</PropA>
    <PropB>$(PropA)</PropB>
    <PropC>$(PropA.ToLower())</PropC>
    <PropD>$(PropA.ToLower().Split(';'))</PropD>
  </PropertyGroup>

  <ItemGroup>
    <ItemA Include="$(PropA)" />
    <ItemB Include="$(PropB)" />
    <ItemC Include="$(PropC)" />
    <ItemD Include="$(PropD)" />
  </ItemGroup>

  <Target Name="Build">
    <Message Importance="High" Text="ItemA: @(ItemA, '|')" />
    <Message Importance="High" Text="ItemB: @(ItemB, '|')" />
    <Message Importance="High" Text="ItemC: @(ItemC, '|')" />
    <Message Importance="High" Text="ItemD: @(ItemD, '|')" />
  </Target>
</Project>
```

### Expected  behavior

```
  ItemA: foo|bar|baz
  ItemB: foo|bar|baz
  ItemC: foo|bar|baz
  ItemD: foo|bar|baz
```

### Actual behavior

```
  ItemA: foo|bar|baz
  ItemB: foo|bar|baz
  ItemC: foo;bar;baz
  ItemD: foo|bar|baz
```

Notice the difference in `ItemC`:

![image](https://user-images.githubusercontent.com/7913492/56100499-a0e9aa80-5f19-11e9-8553-8f3e6e2471dc.png)

despite all properties having the same value:

![image](https://user-images.githubusercontent.com/7913492/56100509-c2e32d00-5f19-11e9-9eae-fdf5f7c71c8a.png)

### Environment data

Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.0.461.62831

**Comment by rainersigwald** [comment]
I don't know if it's a bug or by design either, but it's now The Way It Is.

What's causing this is that the MSBuild engine internally has two types of string: escaped and unescaped. There's some documentaiton on [what characters get escaped](https://docs.microsoft.com/visualstudio/msbuild/msbuild-special-characters). Strings returned from property functions are escaped, so that when they're consumed in other ways you get literal semicolons instead of element-delimiting ones.

You can treat the output of a property function in the normal way by wrapping the property function `$([MSBuild]::Unescape())` around the property function you're using:

```diff
diff --git a/repro.csproj b/repro.csproj
index 0d63bbb..b323608 100644
--- a/repro.csproj
+++ b/repro.csproj
@@ -2,7 +2,7 @@
   <PropertyGroup>
     <PropA>foo;bar;baz</PropA>
     <PropB>$(PropA)</PropB>
-    <PropC>$(PropA.ToLower())</PropC>
+    <PropC>$([MSBuild]::Unescape($(PropA.ToLower())))</PropC>
     <PropD>$(PropA.ToLower().Split(';'))</PropD>
   </PropertyGroup>
 ```

We should at least add a paragraph to the property-function doc page indicating that return values are escaped strings.

**Comment by rainersigwald** [comment]
@ltrzesniewski would https://github.com/MicrosoftDocs/visualstudio-docs/pull/3082 help?

**Comment by ltrzesniewski** [comment]
Thanks for the explanation! The docs change is helpful.

I wasn't aware strings can have two different types internally, so I think adding that info to the docs would also be useful. This issue is confusing because neither MSBuild nor the Structured Log Viewer tell you that a given string is escaped.
