### ISSUE TITLE
What is the order in which props files (explicit & implicit) are imported?

### ISSUE THREAD

**Issue by msbasanth** [microsoft/msbuild#4406]
Hi,

I have both explicit import of props file(Temp.props) and implicit import(Directory.Build.props) of props file in in my CSPROJ. I have OutputPath defined in both props file. What is the order in which the props file are imported? i.e. in the below CSPROJ for a particular configuration (x64 Debug), value from which props file will be considered?

Project file:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build">
  <Import Project="..\..\..\PropertySheets\Temp.props" />
</Project>
```

Directory.Build.props file:
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
  </PropertyGroup>
</Project>
```

 **Temp.props file:**
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>SomeOtherFolder\Debug\</OutputPath>
  </PropertyGroup>
</Project>
```
### Actual behavior
I am not sure how to check which is in use.

### Environment data
`Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
15.9.21.664

OS info:
OS: Windows 10
Visual Studio: VS2017

Regards
Basanth

**Comment by japj** [comment]
Hi, if you want to know the details, you can run Msbuild with /bl to generate a binlog file that you can inspect and you should be able to inspect exact import ordering.

In your specific example though,I believe the directory.build.props will not be imported as I see no Microsoft.common.props being imported (this is done in normal project files either directly or because they use the dotnet sdk through MSBuild), see also https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets

**Comment by msbasanth** [comment]
Thanks for sharing the command @rainersigwald @japj. It works
