### ISSUE TITLE
Question: how to get number of Cores in msbuild proj.

### ISSUE THREAD

**Issue by sandreenko** [microsoft/msbuild#4410]
Hello, I need a way to run Xunit controlled by Msbuild project on different machines with different OS and number or Cores. We need to pass the number of threads that Xunit can create and we want it to be `(number_of cores_that_the_machine_has + 1) / 2`. 

So I want to write something like:
```
    <NUMBER_OF_PROCESSORS>"a magic code to get what number of cores including hyperthreading"</NUMBER_OF_PROCESSORS>
    <MaxThreads>$([MSBuild]::Divide([MSBuild]::Add($(NUMBER_OF_PROCESSORS), 1), 2))</MaxThreads>
```

Could you please help me to do that? In issue #435 I see that you referenced that it is possible, but not clear how.

**Comment by livarcocc** [comment]
Have you considered writing a simple task that returns `Environment.ProcessorCount` and using that to set the MaxThreads? I haven't read the issue you linked, but this might be enough for you.

**Comment by echesakovMSFT** [comment]
This should be enough
```xml
<Project DefaultTarget="Run">
  <Target Name="Run">
    <PropertyGroup>
      <NumberOfProcessors>$([System.Environment]::ProcessorCount)</NumberOfProcessors>
    </PropertyGroup>
    <Message Text="$(NumberOfProcessors)" Importance="High" />
  </Target>
</Project>
```

**Comment by sandreenko** [comment]
> Have you considered writing a simple task that returns Environment.ProcessorCount and using that to set the MaxThreads? I haven't read the issue you linked, but this might be enough for you.

According to the issue, it will give us the wrong result on arm64 machines with 48 cores, we will get 32 instead of 48.

also https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019 [System.Environment]::ProcessorCount is not listed as available member, is it?

**Comment by AndyGerlicher** [comment]
I think you have to do something lower level to get access to the real processor count when you're in a 32-bit process like MSBuild. I remember when we brainstormed how to fix this for msbuild.exe there wasn't an obvious choice. WMI query would probably work.

**Comment by rainersigwald** [comment]
Yeah, if anyone comes up with a good way to get "real" processor count from a 32-bit process I'd love to see it.

You might be able to exec `cmd.exe /c set NUMBER_OF_PROCESSORS` and capture the output, which should use the 64-bit cmd and thus give you a truthful result (up to 64; I think it fails in the same way for > 64 cores).

One thing to consider @sandreenko: it's often dangerous to launch child processes that run multithreaded from MSBuild, because you can get into a situation where you're trying to run NUM_PROCS (msbuild processes) * NUM_PROCS (each child process) threads, which can swamp the OS scheduler and be much slower than ideal.

**Comment by sandreenko** [comment]
Got it, we have checked that `$([System.Environment]::ProcessorCount)` is available from msbuild scripts, I think it suits us for now.
Thank you.
