### ISSUE TITLE
DesignTimeBuild produces a different hash value in CoreCompileInputs.cache than a normal build in projects that generates source files such a WPF app project

### ISSUE THREAD

**Issue by edgarrs** [microsoft/msbuild#4456]
When a DTB happens in a project that includes generated files such as xaml files in a WPF project, the  target _GenerateCompileDependencyCache doesn't include the generated files to calculate the hash value, causing a cache mismatch and consequently an unnecessarily rebuild.

To repro the issue, create a sample WPF project and take a look at the value of the CoreCompileInputs.cache file, then build the project and compare that with the new value.

Here is a sample screenshot of a DTB that doesn't include the generated files:
![image](https://user-images.githubusercontent.com/4756848/59868305-7830c780-9345-11e9-9d97-c4d771d481fc.png)

And here is a screenshot of a normal build that includes the generated files:
![image](https://user-images.githubusercontent.com/4756848/59868438-c219ad80-9345-11e9-813c-a0460b8d986c.png)

**Comment by rainersigwald** [comment]
I think I'd generalize the problem a little bit: design-time builds shouldn't update the cache file at all. They're not producing the outputs, so their inputs aren't relevant.

**Comment by livarcocc** [comment]
Hey @BenVillalobos, we believe this is a good bug to expose you to different parts of MSBuild that you haven't played around with before. So, I am assigning this bug to you. Let me know if you have questions or concerns.

**Comment by AndyGerlicher** [comment]
In the CloudBuild repo to workaround the other issue we just added a condition `'$(IsDesignTimeBuild)' != 'true'`. It might be good to couple this with some amount of #4356 since they're somewhat related? I don't know how to solve #4356 in a general way, but perhaps it's just adding an extension point to make it easier to manage what goes into the hash? Currently we re-implement the task entirely which is not ideal.
