### ISSUE TITLE
Compatibility issue with mono version of MSBuild on Mac

### ISSUE THREAD

**Issue by JohnChen0** [Microsoft/msbuild#446]
On Mac OS X, the mono version of MSBuild sets the OS property to Unix, but the CoreCLR version of MSBuild sets the OS property to OSX. This can cause build errors for some projects. For example, this is blocking build of mscorlib.dll on Mac.

**Comment by rainersigwald** [comment]
@JohnChen0 It looks like our Mono build and our .NET Core build both claim `OSX`. Mono's `xbuild`, on the other hand, does report `Unix` on OS X. It seems like the MSBuild behavior is better, since I don't know how you distinguish between OS X and Linux otherwise.

I would prefer to keep the current MSBuild behavior. Do you feel otherwise?

**Comment by JohnChen0** [comment]
CoreCLR build on Mac is currently using Microsoft.Build.Mono.Debug 14.1.0.0-prerelease from myget.org, and the MSBuild.exe included in this package sets OS to "Unix" on Mac OS X. Is this MSBuild.exe really xbuild instead of MSBuild?

I'm OK with keeping the current MSBuild behavior, and work it around in CoreCLR build. Just want to make sure we're not introducing a compatibility problem that many people will need to work around.

**Comment by akoeplinger** [comment]
AFAIK the current Mono behavior is that way for historical reasons. From http://www.mono-project.com/docs/faq/technical/#how-to-detect-the-execution-platform :

> Notice that as of Mono 2.2 the version returned on MacOS X is still 4 *(== Unix)* for legacy reasons, too much code was written between the time that the MacOSX value was introduced and the time that we wrote this text which has lead to a lot of user code in the wild to not cope with the newly introduced value.

xbuild just uses `Environment.OSVersion.Platform` that's why it ends up being `Unix` on OSX and Linux.

A lot of code out there seems to rely on this, but I guess breaking this behavior is better in the long run for MSBuild.

**Comment by rainersigwald** [comment]
I talked to @ValMenn and @cdmihai about this today, and it sounds like the packaged Mono version of MSBuild had a bug (since fixed) that caused us to always report `Unix`. I didn't see it because the code that returns the string is unchanged, but methods it calls now work right.

I don't think we have a significant compatibility concern here--if someone is moving from xbuild to MSBuild, I think it's reasonable to ask them to update conditions to the more expressive variety. Good to check though--if you're reading this and disagree, please comment with your reasoning.

**Comment by mhutch** [comment]
Given how common the use of $(Platform) is in existing cross-platform targets and project files, IMO this effectively makes MSBuild incompatible with xbuild on Mac.

Maybe it's worth the pain, but I'd be *very* wary of this.

**Comment by JohnChen0** [comment]
For CoreCLR build (dotnet/CoreCLR#1934) we will work around this. Thus I'm closing this issue.
