### ISSUE TITLE
Feature Request: look for global.json file next to sln file

### ISSUE THREAD

**Issue by schuettecarsten** [microsoft/msbuild#4564]
Currently, dotnet looks for global.json file in the current directory (ref: https://docs.microsoft.com/de-de/dotnet/core/tools/global-json). If you have the globla.json next to the sln file but call dotnet with a sln file parameter that uses a subfolder or a full qualified folder name, the global.json is not used.

I suggest that - if dotnet is called with a sln file - the system should also look for a global.json next to the sln file.

**Comment by livarcocc** [comment]
@peterhuene can you comment.

This is not really the right repo for this. At the point a global.json is picked, msbuild is not really at play. I think dotnet/cli would be a good repo for this.

**Comment by peterhuene** [comment]
I don't think the documentation is entirely accurate and I can completely understand any confusion around `global.json`.

`dotnet` itself will search for `global.json` from the current working directory up to the root of the file system.  As `global.json` affects which .NET Core SDK is selected by `dotnet`, by the time the .NET Core SDK is executed (i.e. any SDK command such as `build`) or when running MSBuild (which occurs even later) it is too late for `global.json` to be useful in the SDK selection process.

If anything, we could implement an option to `dotnet` to specify the path to the global.json to use rather than relying on a search from the CWD. Note, however, we can't rely on the interpretation of SDK options or arguments because `dotnet` doesn't know anything about solution files or SDK commands.

@schuettecarsten if you feel that might help solve the issue for you, would you mind opening a feature request for such an "use this global.json" option on the `dotnet/core-setup` repo, which is where the implementation of `dotnet` lives?  Neither the .NET Core SDK or MSBuild are involved in the respecting of `global.json`, so this isn't the right repository for that feature request.  As such, I will be closing this issue.  Please let me know if you have any additional questions or concerns.  Thanks!

**Comment by schuettecarsten** [comment]
@peterhuene thanks for explanation. I think correct repo is `dotnet/cli`....

**Comment by peterhuene** [comment]
@schuettecarsten core-setup is the correct repo as that is where `dotnet` is implemented.  `dotnet/cli` is for the .NET Core SDK, which would not be implementing an option to respect a path to global.json.  I'll move the issue you created there.

**Comment by nguerrera** [comment]
I transferred the issue to core-setup.
