### ISSUE TITLE
Display error in VS regarding build action, while build itself performs fine.

### ISSUE THREAD

**Issue by taori** [microsoft/msbuild#4610]
### Steps to reproduce

Checkout https://github.com/taori/Amusoft.AOP/commit/aee0596fa573de3629e06882c4d14a6829606a16

The problem exists in the unit test project. As pointed out [here](https://stackoverflow.com/questions/57479355/how-to-mark-files-of-a-folder-as-embedded-resource-with-wildcards-with-the-new-p/57482357#57479355) i was trying to get a wildcard applied to treat a certain folder as embedded resources. While Lance successfully resolved my build issue, there was a display error in VS which would not indicate that this is treated as an embedded resource. 

My guess is that the reason is that VS expects a Compile Remove="path" on top of the generated EmbeddedResource?

### Expected  behavior
I would expect VS to report EmbeddedResource here. Perhaps it's the case that in its current state it is both embedded + compiled?

### Actual behavior
It tells me the files in the TestContent folder are just being compiled.

### Environment data
`msbuild /version` output:
![grafik](https://user-images.githubusercontent.com/5545184/62963129-afc96680-be00-11e9-8171-df59b5a9b405.png)

OS info:
Windows 8.1
Visual Studio 2019 executing MSBuild

**Comment by rainersigwald** [comment]
This is happening because you're modifying the items in a target, while Visual Studio creates the project tree and displays "Build Action" based on a project's initial evaluation.  

Instead of adding a target to create `EmbeddedResource` items, can you use the Visual Studio UI to change the Build Action? That should apply a project change like this:

```diff
diff --git a/4610.csproj b/4610.csproj
index 50de00b..7916704 100644
--- a/4610.csproj
+++ b/4610.csproj
@@ -5,4 +5,12 @@
     <RootNamespace>_4610</RootNamespace>
   </PropertyGroup>
 
+  <ItemGroup>
+    <Compile Remove="Class1.cs" />
+  </ItemGroup>
+
+  <ItemGroup>
+    <EmbeddedResource Include="Class1.cs" />
+  </ItemGroup>
+
 </Project>
```

(you can also apply a change like this manually).

That will apply at evaluation time, so Visual Studio will see and understand the issue.
