### ISSUE TITLE
How is "Copy Local" calculated when <Private> is not set?

### ISSUE THREAD

**Issue by yaakov-h** [Microsoft/msbuild#467]
The behaviour appears to have changed between VS2013 (MSBuild 12.0) and VS2015 (MSBuild 14.0), but I can't find any documentation on exactly how this feature is supposed to work.

**Comment by AndyGerlicher** [comment]
You can read about the change in #24 

And the code for the actual method is [here](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/AssemblyDependency/Reference.cs#L1158-L1332)

**Comment by yaakov-h** [comment]
What does "If the assembly is resolved locally" mean? Does that mean that either:
* it was found in `$(OutputPath)`
* it was found via `<HintPath>`

or are there other cases that lead to a resolution?

**Comment by AndyGerlicher** [comment]
There are a number of reasons for CopyLocal to be Yes or No. See that method I mentioned for details. What I mean by resolved locally is when an assembly is [**not** resolved through the GAC](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/AssemblyDependency/Reference.cs#L489-L495) (i.e. `ResolvedFromGac = false`). So for example if you have a project reference or an explicit HintPath, your build output will not be determined by having the assembly in the GAC or not because it was resolved "locally" (`ResolvedFromGac = false`).

**Comment by AndyGerlicher** [comment]
Closing this issue, let us know if you need further clarification.
