### ISSUE TITLE
Avoid rebuilding Any CPU dependencies

### ISSUE THREAD

**Issue by RobSwDev** [microsoft/msbuild#4678]
I have a solution containing an executable that depends on numerous libraries. We build the executable in both x86 and x64, and all the libraries "Any CPU". 
Our CI msbuild script runs the MSBuild task twice against the solution, once for each target platform. This means each library dependency gets built twice, somewhat redundantly.

Is there a way I can use msbuild to build only the executable in the 2nd run, and have it pick up all the dependencies from the Any CPU folder? This works in Visual Studio, but not via msbuild from the command line. 

In detail, I created 3 solution platforms in VS: Any CPU, x86, x64. 
Any CPU marks everything for build (via the Configuration Manager)
x86 & x64 only mark the executable for build
Provided I build Any CPU first, Visual Studio will copy (but not build) dependencies from Any CPU when I build the x86/x64 platforms.

MSBuild command line respects the build/do not build settings, but fails to compile as it doesn't pass the (project) references in to csc. Visual Studio on the other hand magically knows.

I hoped something like this might work:
`    <MSBuild Projects="$(SolutionFile)" Targets="Build" Properties="Platform=Any CPU" />`
`    <MSBuild Projects="$(SolutionFile)" Targets="Build" Properties="Platform=x86;BuildProjectReferences=false" />`

Is there a neat way to achieve this? I suppose I could duplicate the executable project and have one build x86, one x64, and build everything in a single pass, but I don't really want to do this.

**Comment by rainersigwald** [comment]
Yes, you can accomplish this on the command line, but it's more complicated than it should be. I've attached an example of my preferred approach to this situation: 
[MultiPlatformApp.zip](https://github.com/microsoft/msbuild/files/3560631/MultiPlatformApp.zip)

* 2 solution platforms: x64 and x86 (no anycpu because that wouldn't produce your usable app)
* AnyCPU is the only platform for the library projects, so that gets used in the x64 and x86 _solution_ platforms
* AnyCPU library projects are still configured to build in the platform-specific configurations.
* In **addition** to that solution configuration (which is primarily for VS scenarios), tell MSBuild to always reference the AnyCPU platform of the libraries by adding `SetPlatform="Platform=AnyCPU"` to all `ProjectReference`s in your application project.

With that, you can always build the solution for either platform, and automatically bring everything up to date:

```sh-session
$ msbuild -nologo -m -v:m .\MultiPlatformApp.sln -p:Platform=x86
  AnyCPULibrary -> S:\repro\microsoft\msbuild\issues\4678\AnyCPULibrary\bin\Debug\AnyCPULibrary.dll
  MultiPlatformApp -> S:\repro\microsoft\msbuild\issues\4678\MultiPlatformApp\bin\x86\Debug\MultiPlatformApp.exe
$ msbuild -nologo -m -v:m .\MultiPlatformApp.sln -p:Platform=x64
  AnyCPULibrary -> S:\repro\microsoft\msbuild\issues\4678\AnyCPULibrary\bin\Debug\AnyCPULibrary.dll
  MultiPlatformApp -> S:\repro\microsoft\msbuild\issues\4678\MultiPlatformApp\bin\x64\Debug\MultiPlatformApp.exe
```

You can also use a small wrapper project to build both copies of the application in parallel:

```xml
<Project>
  <ItemGroup>
    <ProjectReference Include="MultiPlatformApp\MultiPlatformApp.csproj" Properties="Platform=x86" />
    <ProjectReference Include="MultiPlatformApp\MultiPlatformApp.csproj" Properties="Platform=x64" />
  </ItemGroup>

  <Target Name="Build">
    <MSBuild Projects="@(ProjectReference)"
             BuildInParallel="true"
             />
  </Target>
</Project>
```

```sh-session
$ msbuild -nologo -m -v:m .\BuildAll.proj
  AnyCPULibrary -> S:\repro\microsoft\msbuild\issues\4678\AnyCPULibrary\bin\Debug\AnyCPULibrary.dll
  MultiPlatformApp -> S:\repro\microsoft\msbuild\issues\4678\MultiPlatformApp\bin\x64\Debug\MultiPlatformApp.exe
  MultiPlatformApp -> S:\repro\microsoft\msbuild\issues\4678\MultiPlatformApp\bin\x86\Debug\MultiPlatformApp.exe
```

Note that there's only _one_ build of `AnyCPULibrary` mentioned there.

What you _can't_ do is build the _solution_ twice in parallel, because of #4680 which I just filed while writing this up.

**Comment by RobSwDev** [comment]
Excellent - thanks! I'll give that a go. 
Haven't seen "SetPlatform" in any of the documentation - e.g. it's not mentioned [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019).

**Comment by livarcocc** [comment]
@RobSwDev did this work for you?

**Comment by RobSwDev** [comment]
@livarcocc Yes, thanks, it's working for me. In fact it seems like I don't actually need to add the SetPlatform metadata to the project references, and it still works. (Both in the MultiPlatformApp sample and in my real-world case)

I had several issues stopping it working: 
- Minor differences in the properties passed in for each platform build: when only 1 project out of 100 needs that property, the project itself can work it out based on `$(Platform)`
- CopyAlways set to true on a couple of Content items
- CopyAlways set to true in targets files in nuget packages referenced my multiple projects
- Unnecessary test project references to the 5 projects that have to be built for both platforms.
