### ISSUE TITLE
Empty file called System.dll breaks the build

### ISSUE THREAD

**Issue by sharwell** [microsoft/msbuild#4687]
### Steps to reproduce

1. Create a C# CPS project targeting net472
2. Create an empty file in the project directory named **System.dll**

### Expected  behavior

The project builds successfully, and ignores the empty file which was not part of the project.

### Actual behavior

MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'System.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.

### Environment data

`msbuild /version` output:

OS info: Windows 10

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): Visual Studio 2019 Version 16.3 Preview 2

**Comment by rainersigwald** [comment]
This is happening because `None` items (which this is globbed into by default) are `CandidateAssemblyFiles`, which are considered in RAR by default (#1511 would create an easy off switch for this)

```
Primary reference "System".
    Resolved file path is "S:\repro\microsoft\msbuild\issues\4687\system.dll".
    Reference found at search path location "{CandidateAssemblyFiles}".
```

The easiest workaround is probably to remove `{CandidateAssemblyFiles}` from the list.

**Comment by dasMulli** [comment]
TBH I'd rather like for such an instance to fail, since there is an inherent expectation to files named `.dll` and historic behaviour of having `.dll` files as None/Content items in projects as @rainersigwald mentioned (though I'd like to do something like `<None Update="my.dll" ConsiderAsCandidateAssembly="False" />`).

> Create an empty file in the project directory named System.dll

... why? 😕 
Just because I **can** do it, doesn't mean I **should**...

**Comment by livarcocc** [comment]
I don't believe this is an issue that we will get to. As such, I am going to close it.
