### ISSUE TITLE
Publish and consume OptProf data under new casing

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4720]
We should 

- [x] ensure publication of OptProf profiles uses the new canonicalized `microsoft/msbuild` name
- [x] back out #4719

**Comment by BenVillalobos** [comment]
A note to my future self:

Directly related to [.vsts-dotnet.yml](https://github.com/microsoft/msbuild/blob/master/.vsts-dotnet.yml#L80). Currently, setting RepositoryName to Build.Repository.Name sets it to `Microsoft/msbuild`, which no longer works because it should be `microsoft/msbuild`

Running (internally)
`drop list --dropservice "https://devdiv.artifacts.visualstudio.com" --pathPrefixFilter "OptimizationData/Microsoft/msbuild/master" --toJsonFile "...\temp\someJsonFile.json"`

**Comment by rainersigwald** [comment]
I think I accidentally fixed this while trying to get a couple of things going last week @BenVillalobos. Can you just verify that everything is flowing well for master optprof collection and builds?

**Comment by BenVillalobos** [comment]
Both master and vs16.4 are building properly.
