### ISSUE TITLE
msbuild cannot find NetCore 3.0 preview sdk

### ISSUE THREAD

**Issue by RobSwDev** [microsoft/msbuild#4737]
My solution contains projects that target NetStandard 2.1 - requiring the NetCore 3.0 preview, which I have installed.

I can build the solution via command line msbuild on my local machine, but not on our build agents. 
The only difference I'm aware of being that I have the full Visual Studio 2019 installed on my local machine, but only the [VS2019 buildtools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16) on the build agents.

I get this error:
error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. 

Is it possible to use the .Net Core 3.0 sdk when building using msbuild tools? Obviously, without the full VS2019 installed, I'm unable to check "Use previews of the .NET Core SDK (requires restart)". Is there an equivalent for the command line tools only?

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework

`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

OS info:
Windows 2012 R2
Invoking MSBuild from the command line

**Comment by rainersigwald** [comment]
@nguerrera do you know?

**Comment by nguerrera** [comment]
In general, for command line builds, you can specify a preview version in global.json and it will be honored irrespective of the checkbox. See https://docs.microsoft.com/en-us/dotnet/core/tools/global-json

The following will allow the latest 3.0.100-* installed to bind due to the default roll forward policy.
``` js
{
  "sdk": {
    "version": "3.0.100-preview"
  }
}
```

This file must go at the level of your sln or higher in the directory tree.

Starting with 16.3, you will be able to specify the following in global.json to say "use latest preview" without specifying any version:

``` js
{
  "sdk": {
    "allowPrerelease": true
  }
}
```

See https://github.com/dotnet/core-setup/pull/6953

But obviously, that won't help without having 16.3 RTM first, at which point 3.0 RTM will be available and there would be no need to use a preview for 3.0. This would be a good option for future previews.

Please do note the latest 3.0 previews are only officially supported on 16.3 previews, and not on 16.2. We had actually intended to start blocking 16.2 already, but a mishap in infrastructure made it so that only 3.0 RTM will be blocked from use in 16.2 or earlier. However, even though it is not blocked outright, there are several things that don't work, and there is no testing of that combination. There were several VS changes made to align with SDK changes for 3.0/16.3.

My recommendation would be to do one of the following:

1. Wait a week and upgrade to VS (build tools) 16.3, with 3.0 RTM SDK
2. Use a preview installation of VS (build tools) 16.3

**Comment by RobSwDev** [comment]
@nguerrera Thanks! The global.json seems to work.

Previously I tried it and had problems with a (test) project using multiple versions of a managed dll and aliases not compiling correctly. Not sure what changed (maybe using full version 3.0.100-preview8-013656 instead of 3.0.100?), but I'm happy it works now.

**Comment by livarcocc** [comment]
Going to close this issue as the questions seem to have been addressed and a path forward provided.

**Comment by xiangzhai** [comment]
:mips-interest
