### ISSUE TITLE
EmbeddedResources sometimes get wrong names

### ISSUE THREAD

**Issue by AndreasHeisel** [microsoft/msbuild#4806]
### Background
We do not use the ResXFileCodeGenerator, because it doesn't generate what we need. Instead we manage our resources using ResourceManager ouerselves.  

Porting our code from .NET Framework to .NET Core 3.0, we see changes in the handling of *.resx files that break our code. The embedded *.resources resource streams have unexpected names.

I think it is related to #4488

### Steps to reproduce
Build attached solution
[ResX.zip](https://github.com/microsoft/msbuild/files/3715969/ResX.zip)

### Expected  behavior
Dll contains:
* ResX.Foo.resources
* ResX.Foo2.resources
* ResX.Foo3.resources

### Actual behavior
Dll contains:
* ResX.FooExtensions.resources
* ResX.Foo2.resources
* ResX.Messages.resources

### Environment data
We use VisualStudio 16.3.3 with .NET Core 3.0 on Windows 10 German.
It worked with VisualStudio 16.2.x and .NET Core 3.0 preview9

**Comment by rainersigwald** [comment]
Thanks for the report. You can opt out of the new .NET Core SDK 3 behavior by setting the property

```xml
<EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
```

in any .NET Core SDK-using project. If you have multiple projects, you may want to put it in a [`Directory.Build.props` file](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets).

This was an intentional SDK change, because it makes the "standard" path using `DependentUpon` easier to express. Since you manage the resources using "non-standard" code, the opt-out is now required.

**Comment by AndreasHeisel** [comment]
Thank you for the information. I tested it with a real live project and it built.

As being a project level switch, this leads to some questions: 
* Where is "DependsUpon" needed? 
* What will stop working when we set the switch?

Your convention would work for us, if it would use the first type declaration (class, enum, struct) instead of the first class. In my sample (Foo3), it is a nested class witch seem weird to me.

**Comment by FahaoTang** [comment]
Thanks for your temporary solution.
I tested it with my own website and it is working:
[Settings page for language and theme](https://kontext.tech/settings)

**Comment by BenVillalobos** [comment]
Okay, so it turns out this was a breaking change we wanted to take as of net core 3.0. For full context and an explanation of how resource names are chosen, see [the issue on MSBuild's side](https://github.com/microsoft/msbuild/issues/4996) and [the dotnet docs issue that explains the new rules](https://github.com/dotnet/docs/issues/16964).
