### ISSUE TITLE
[loc][Query][msbuild] Localizability of 0; "GetSDKReferenceFiles.AddingRedistFile"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/msbuild#4816]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Sources:
Adding file "{0}" from redist folder with target path "{1}".

MSB3798: The targeted architecture for the resolved sdk reference "{0}" was empty. Cannot find reference or redist files without a targeted architecture.

The redist list file "{0}" has a null or empty Redist name in the FileList element. Make sure the Redist Name is not null or empty.

File Name:
Tasks\Resources\xlf\Strings.xlf

==========================================
Query:
Is "redist" the name of the folder (unlocalizable)? Thanks.
Can we translate "redist files" as "files of a redistributable package"? 
Is a "redist list" a list of redistributable packages?
Why is "Redist" capitalized in "Redist name"? Is it localizable (like "name of the redistributable package")?

**Comment by rainersigwald** [comment]
cc @tmeschter

We haven't touched this code in quite a while so I'm not 100% confident on these answers. @dsplaisted, this is the same `FrameworkList.xml` that is used for Core targeting in the SDK now, right? Can you check these?

> Is "redist" the name of the folder (unlocalizable)? Thanks.

It is the name of a folder (the folder is actually `RedistList`) but I think that name is an internal implementation detail so it could be localizable.

> Can we translate "redist files" as "files of a redistributable package"?

I think so.

> Is a "redist list" a list of redistributable packages?

It is a list of files within a single redist package.

> Why is "Redist" capitalized in "Redist name"? Is it localizable (like "name of the redistributable package")?

I think this is because it's referring to an XML attribute name that is capitalized, as in

```xml
<FileList Redist="Microsoft-Windows-CLRCoreComp-v3.5">
```

**Comment by dsplaisted** [comment]
We have a FrameworkList.xml in the .NET Core targeting packs.  We mostly reused the format of the FrameworkList.xml files that MSBuild understands, but I don't think that there's any sharing as far as code that consumes them.

**Comment by PDostalek** [comment]
Thanks for all replies
