### ISSUE TITLE
Save in ClickOnce scenario does not update ProjectRootElement._lastWriteTimeWhenRead (regression)

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#4824]
See [AB#984122](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/984122)

More Info: 
1. The bug reproduces on master-29312.03 & Dev16.3 Pre4 d16.3-29311.1183.
2. This bug doesn't reproduce on master-29311.112 & Dev16.3 Pre3 d16.3-29230.61.
3. This bug doesn't repro when setting NuGet package management format to Packages.config.
4. This bug doesn't repro after rebuilt the project. 

Steps to reproduce:
1. Create a project, such as WPF/Winforms project.
2. Right click on Reference open Manage NuGet Packages… 
3. Click Settings and set the package management format to PackageReference .
4. Install a NuGet package such as Newtonsoft.Json.
5. Publish and install the project.
6. On Signing page uncheck the 'Sign the ClickOnce manifests'.
7. Publish and install the project.

Actual result: 
Cannot start the application

The warning information is:
Application validation did not succeed. Unable to continue.
See Details txt file in attachment.
Expect result:
The application should be add successfully.

**Comment by Forgind** [comment]
There seems to be a problem in that save (part of publish) calls https://github.com/microsoft/msbuild/blob/master/src/Build/Construction/ProjectRootElement.cs#L1573 instead of https://github.com/microsoft/msbuild/blob/master/src/Build/Construction/ProjectRootElement.cs#L1496.

The former Save does not update the timestamp during the save, whereas the latter does, instead using a shim. One possible solution is to create a native MSBuild method that saves through a temp file and call it instead, but we're still investigating as to whether that's the best solution.
