### ISSUE TITLE
Why Microsoft.Build.dll not strong-named in nupkg? 

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [Microsoft/msbuild#490]
I can't use this assembly in my project due to it not strong-named. Can you add this feature in future releases?

**Comment by rainersigwald** [comment]
What nupkg are you using? It's signed in the latest from our MyGet feed.

**Comment by MAX-POLKOVNIK** [comment]
I use this:
[https://www.nuget.org/packages/MSBuild/](url)

**Comment by rainersigwald** [comment]
Ah, I see. That's not our package--we haven't published an official NuGet package for our full-Framework assemblies.

Please reference MSBuild from its installed location (or the GAC). That should also reduce confusion at runtime, because the open-source MSBuild version is 14.1 instead of 14.0 like the official version.

I'll look into getting that package de-listed from NuGet to avoid this confusion in the future.

**Comment by MAX-POLKOVNIK** [comment]
I can't use MSBuild 14.0 version, because some classes are missing or internal (SolutionFile, ProjectInSolution) instead of 14.1.
Is there any way to get signed 14.1?

**Comment by jeffkl** [comment]
We'll be publishing official MSBuild packages to NuGet org today.

**Comment by jasonwilliams200OK** [comment]
@MAX-POLKOVNIK, see https://github.com/Microsoft/msbuild/issues/926#issuecomment-242828030 for the list of packages that has been published.
