### ISSUE TITLE
Suggestion: Create Git related tasks

### ISSUE THREAD

**Issue by deinok** [microsoft/msbuild#4946]
Using GIT is really common. So, it would be great to have Tasks that wraps GIT executable or libgit2.

In my experience, most wrappers arround git are related to:
- clone
- checkout
- fetch
- pull

**Comment by rainersigwald** [comment]
Team triage: we haven't seen a great deal of demand for building this into core MSBuild, since most projects build at a single commit coordinated either manually or by a CI/automated build system. There are various tasks that extract information from the current git repo (like [GitInfo](https://github.com/kzu/GitInfo), [Source Link](https://github.com/dotnet/sourcelink), and [Nerdbank.GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning/)).

There's probably room for a NuGet package that has tasks that offer other or more general Git operations, but we don't currently think it needs to be baked into MSBuild. We can revisit this decision if demand increases.

**Comment by deinok** [comment]
I disagree, what most people do is use <Exec />

Having a builtin git task could open a new world like been the first step to referenciate a package that is not in a nuget only by its URL, version and path
