### ISSUE TITLE
Feature Request: Enable to get MsBuild Errors and Warning as CSV format 

### ISSUE THREAD

**Issue by moh-hassan** [microsoft/msbuild#4968]
When building cs projects from within VS 2017, I get Warnings and Errors in the Pan "Error List".

I copy /paste these errors and read as CSV format for analysis.

```
Severity    Code    Description Project File    Line    Suppression State
```
I can direct errors /warning to text files as described [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2015#saving-the-log-output-to-multiple-files), but these messages are not structured and I have to parse it using Regex.

It's nice if we can get these Errors and Warning as CSV format and it can be controlled by an  option for the logger parameters, e.g: `FormatSeverity` , so we can call msbuild logger as:

 ```
/flp2:logfile=Errors.log;errorsonly;FormatSeverity
 /flp3:logfile=Warnings.log;warningsonly;FormatSeverity
```

**Comment by rainersigwald** [comment]
Team triage: There's no built-in capability for this, and since logging needs vary widely and we haven't gotten a ton of requests for this format, I don't expect us to build this in directly. 

However, you can [write a custom logger](https://docs.microsoft.com/visualstudio/msbuild/build-loggers) to capture the information in the format you desire. You might also find our [XML logger sample instructive](https://github.com/microsoft/msbuild/tree/master/src/Samples/XmlFileLogger).

Another option would be to use the [binary log API](https://github.com/microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md) to read the information you're interested in out of a `.binlog`, if you already capture one (they're useful for many things).
