### ISSUE TITLE
Question about Microsoft.Cpp.Win32.user.props for the user SYSTEM

### ISSUE THREAD

**Issue by zosrothko** [microsoft/msbuild#4990]
Hello

This is just a question: Where is the file `Microsoft.Cpp.Win32.user.props` when the user is `SYSTEM` (instead of `C:\Users\fandre\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props` for the user fandre)?

**Comment by rainersigwald** [comment]
Based on [this StackOverflow answer](https://serverfault.com/questions/9325/where-can-i-find-data-stored-by-a-windows-service-running-as-local-system-accou), I think it's `C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props`.

If you're thinking of modifying this file, though, it might be better to run your automation as a service account rather than as `SYSTEM`.

**Comment by livarcocc** [comment]
Closing as the question seems to have been answered.
