### ISSUE TITLE
Linker ignores $(Platform) and $(Configuration) if referenced project is not part of solution and contains Win32|Debug Config

### ISSUE THREAD

**Issue by markusobi** [microsoft/msbuild#5116]
### Bug description:
MSBuild ignores $(Platform) and $(Configuration) variables for linking under the following circumstances:
 - project C contains a Debug|Win32 configuration
 - project C is a project reference of project B
 - project B is built inside a solution (in this case: solution A), that does not contain project C
 
### Steps to reproduce
 - unzip attachment [link_wrong_config.zip](https://github.com/microsoft/msbuild/files/4180657/link_wrong_config.zip)
 - open A.sln
 - **select Release and x64**
 - build project B

### Expected behavior:
 - linker tries to find x64|Release build artifact of C
  (this artifact may or may not be present, depending on whether C has already been built before)

### Actual behavior:
> Error	LNK1181	cannot open input file '...\bin\Win32\Debug\C.lib'	B	...\B\LINK	1	
 - linker tries to find binary artifact of C inside folder of **C's Debug|Win32 configuration**
 - if this binary is present, it even tries to link in the Debug|Win32 binary into whatever configuration of B you are currently building.

### Environment data
`msbuild /version` output: 16.4.0.56107  
Windows 10, Microsoft Visual Studio Community 2019 Version 16.4.4

How to reproduce the attached files from scratch:
 - create new project->Dynamic-Link Library (DLL), project name C (check solution in same dir)
 - force .lib creation by exporting any symbol: append line `_declspec(dllexport) void C() {}` to dllmain.cpp
 - in property manager: right click project->add existing property sheet: dll.props (sets output dir and linker input dir to `..\bin\$(Platform)\$(Configuration)\`)

Do same again for project B:
 - create new project->Dynamic-Link Library (DLL), project name B (check solution in same dir)
 - force .lib creation by exporting any symbol: append line `_declspec(dllexport) void B() {}` to dllmain.cpp
 - in property manager: right click project->add existing property sheet: dll.props (sets output dir and linker input dir to `..\bin\$(Platform)\$(Configuration)\)`

in solution explorer:
 - right-click solution B: Add->Existing Project: select C.vcxproj
 - right-click project B: Add->Reference->Projects>Solution:Check C
	
creat new project A: Empty project (doesn't matter, just need any solution)
 - in solution explorer:
 - right-click solution A:Add->Existing Project: select B.vcxproj

### Bug mitigation:
delete the PropertyGroup of Debug|Win32 configuration from project C:
```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v142</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
```

**Comment by rainersigwald** [comment]
This is an intentional* behavior when a build goes outside of a solution. The [`AssignProjectConfiguration`](https://docs.microsoft.com/visualstudio/msbuild/assignprojectconfiguration-task) task maps `ProjectReference`s to the appropriate project-level `Configuration` and `Platform`, given the active solution-level `Configuration` and `Platform`. When the referenced project is not part of the solution, there's no such mapping, and the build has to choose between passing along the referencing project's configuration or taking the referenced project's _default_ configuration.

That choice is configured by the `ShouldUnsetParentConfigurationAndPlatform` parameter, which is (in the default targets) controlled by the `$(ShouldUnsetParentConfigurationAndPlatform)` property. This property defaults to `true` when building a solution, but is overridable by your setting the property to `false` in your project.

https://github.com/microsoft/msbuild/blob/5d872c945f2fb42a26ed67791f4bdceb458f1402/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1475-L1477

\* I'm not sure it's a _good_ behavior, but it's too late to change it now since it has behaved like this for many years and projects depend on it (mostly accidentally).

**Comment by markusobi** [comment]
> That choice is configured by the `ShouldUnsetParentConfigurationAndPlatform` parameter, which is (in the default targets) controlled by the `$(ShouldUnsetParentConfigurationAndPlatform)` property. This property defaults to `true` when building a solution, but is overridable by your setting the property to `false` in your project.

@rainersigwald I tried setting `ShouldUnsetParentConfigurationAndPlatform` inside B.vcxproj as suggested [here](https://stackoverflow.com/a/29156933/2056153)

```xml
  <ItemGroup>
    <ProjectReference Include="..\C\C.vcxproj">
      <Project>{49046638-bc62-46ee-a8f7-fad84b84176a}</Project>
      <Properties>ShouldUnsetParentConfigurationAndPlatform=false</Properties>
    </ProjectReference>
  </ItemGroup>
```
But this did not change anything. Recap: B depends on C, but C is not in solution where B is built.

**Comment by rainersigwald** [comment]
@markusobi Set it as a property in your project, in a PropertyGroup:

```xml
<PropertyGroup>
  <ShouldUnsetParentConfigurationAndPlatform>false</ShouldUnsetParentConfigurationAndPlatform>
</PropertyGroup>
```

The solution in that StackOverflow answer is different: it makes MSBuild set that property for projects C and H so that it is set when figuring out their own dependencies. I'm not sure it's a good approach for them either, but I guess it's working for them.

**Comment by Anton-V-K** [comment]
The approach with setting `ShouldUnsetParentConfigurationAndPlatform` to `false` in `PropertyGroup` for the dependend project ( proposed in https://github.com/dotnet/msbuild/issues/5116#issuecomment-624622909 ) works just fine if the solution is being built with MSBuild directly (version 17.6.3+07e294721 / VS2022 17.6.4) - all required configurations of the dependency project are built.
However the build in VS2022 still fails - only the default configuration of the dependency project is built in this case.
