### ISSUE TITLE
Do cutom tasks always run in the same process?

### ISSUE THREAD

**Issue by daveMueller** [microsoft/msbuild#5153]
This is just a question. I'm injecting two custom tasks like in the following:

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask TaskName="TaskA" ... />
  <UsingTask TaskName="TaskB" ... />
...
```

Can I be sure that both tasks run in the same process? To be precise, when I use a DI container in TaskA, can I be sure that the container is also available in TaskB?

**Comment by rainersigwald** [comment]
There are several aspects to this.

1. It's possible to specify that tasks should run out of process, for instance by specifying a [`Runtime`, `Architecture` or `TaskFactory="TaskHostFactory"`](https://docs.microsoft.com/visualstudio/msbuild/how-to-configure-targets-and-tasks?view=vs-2019#usingtask-attributes-and-task-parameters).
1. Projects can be built in different processes in a `-m` multiproc build, so if your tasks are imported into different projects they may run in different processes (at the whims of the scheduler).
1. Within a single project instance, though, the MSBuild engine guarantees a single process. So if TaskA and TaskB are called in the same project you will likely get the behavior you want.

As a rule, you should **avoid depending on process state between tasks**. It's caused pain in the past because of the above, in addition to incremental builds (what if TaskA is skipped because its direct outputs were out of date, but TaskB needed to run--does it then have the right setup?

Also be very careful about capturing state from one task execution to another (for instance in a static field). You can cause crashes if you hold onto objects that MSBuild tears down after a task--`Task.Log` is the most common cause of this.

**Comment by daveMueller** [comment]
Thanks a lot for the very detailed explanation.
