### ISSUE TITLE
MSB4252 when using /irc flag

### ISSUE THREAD

**Issue by mwelsh1118** [microsoft/msbuild#5204]
With a very simple .sln with two projects and a single project-to-project reference, the /orc & /irc flags are producing an error.

### Steps to reproduce
See https://github.com/mwelsh1118/msbuild-reference-cache

### Expected behavior
`Build succeeded`

### Actual behavior
`Build FAILED` with `MSB4252` error

### Environment data
`msbuild /version` output: `16.4.0.56107`
OS info: `Windows 10`

**Comment by rainersigwald** [comment]
@cdmihai, can you take a look at this?

**Comment by cdmihai** [comment]
Works as expected.

The full error text is:
```
MSB4252: Project "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\ConsoleApp.csproj" with global properties
    ()
    is building project "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\ClassLibrary.csproj" with global properties
    ()
    with the (GetTargetFrameworks) target(s) but the build result for the built project is not in the engine cache. In isolated builds this could mean one of the following:
    - the reference was called with a target which is not specified in the ProjectReferenceTargets item in project "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\ConsoleApp.csproj"
    - the reference was called with global properties that do not match the static graph inferred nodes
    - the reference was not explicitly specified as a ProjectReference item in project "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\ConsoleApp.csproj"
```

This means that project ConsoleApp is building project ClassLibrary with target GetTargetFrameworks, but the results for the  GetTargetFrameworks target are not in the output cache of ClassLibrary. This is because only requested targets get into output cache, so when using cache files, you have to call each project with all the targets that that project will get called with by all the other projects depending on it. So if project A calls project C with target Foo, and project B calls project C with target Bar, you'll have to call C with `/t:Foo;Bar /orc:c.cache`, otherwise when building A or B with C's cache you'll get MSB4252. To infer the targets for each project, you can use the [ProjectGraph.GetTargetLists](https://github.com/microsoft/msbuild/blob/9cebea688cc089ecba7c15acbbd35765e064e10c/src/Build/Graph/ProjectGraph.cs#L510) API which uses the static graph specific [target inference protocol](https://github.com/microsoft/msbuild/blob/master/documentation/specs/static-graph.md#inferring-which-targets-to-run-for-a-project-within-the-graph) to infer what targets to call on each node of the graph. An example usage is how `msbuild /graph` is implemented, where the BuildManager creates a static graph, calls GetTargetLists on it to find the targets for each node, then builds each node in topological order: https://github.com/microsoft/msbuild/blob/9cebea688cc089ecba7c15acbbd35765e064e10c/src/Build/BackEnd/BuildManager/BuildManager.cs#L1410

For the particular example of this issue, you can get it working from the command line with the following:
```
E:\delete\msbuild-reference-cache\ReferenceCacheExample [master ≡]> msbuild ClassLibrary /orc:ClassLibrary.cache /t:"GetTargetFrameworks;Build;GetCopyToOutputDirectoryItems;GetNativeManifest"
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/20/2020 3:24:24 PM.
Writing build results caches to: ClassLibrary.cache
Project "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\ClassLibrary.csproj" on node 1 (GetTargetFrameworks;Build;GetCopyToOutputDirectoryItems;GetNativeManifest target(s)).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /reference:"C:\Program Files (x8
  6)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll" /reference:"C:\Program Files (x86)\Refe
  rence Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (
  x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.dll" /reference:"C:\Program Files (x86)\Reference
   Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assem
  blies\Microsoft\Framework\.NETFramework\v4.8\System.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\ClassLibrary.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Stati
  c Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /utf8output /deterministic+ /langversion:7.3 Referenced.cs Properties\AssemblyInfo.cs "C:\Users\micodoba.REDMOND\AppData\Local\Temp\.
  NETFramework,Version=v4.8.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn
CopyFilesToOutputDirectory:
  Copying file from "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\obj\Debug\ClassLibrary.dll" to "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\bin\Debug\ClassLibrary.dll".
  ClassLibrary -> E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\bin\Debug\ClassLibrary.dll
  Copying file from "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\obj\Debug\ClassLibrary.pdb" to "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\bin\Debug\ClassLibrary.pdb".
Done Building Project "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\ClassLibrary.csproj" (GetTargetFrameworks;Build;GetCopyToOutputDirectoryItems;GetNativeManifest target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.28
E:\delete\msbuild-reference-cache\ReferenceCacheExample [master ≡]> msbuild ConsoleApp /irc:ClassLibrary.cache
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/20/2020 3:24:53 PM.
Using input build results caches: ClassLibrary.cache
Project "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\ConsoleApp.csproj" on node 1 (default targets).
GenerateBindingRedirects:
  No suggested binding redirects from ResolveAssemblyReferences.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bitpreferred /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /
  reference:E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\bin\Debug\ClassLibrary.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\Microsoft.CSharp.dll" /reference
  :"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Core.dll" /reference:"C:\Program
   Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Data.dll" /reference:"C
  :\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Net.Http.dll" /reference:"C:\Program
  Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Xml.Linq.dll" /debug+ /debug:full /filealig
  n:512 /optimize- /out:obj\Debug\ConsoleApp.exe /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:exe /
  utf8output /deterministic+ /langversion:7.3 Program.cs Properties\AssemblyInfo.cs "C:\Users\micodoba.REDMOND\AppData\Local\Temp\.NETFramework,Version=v4.8.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn
_CopyFilesMarkedCopyLocal:
  Copying file from "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\bin\Debug\ClassLibrary.dll" to "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\bin\Debug\ClassLibrary.dll".
  Copying file from "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\bin\Debug\ClassLibrary.pdb" to "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\bin\Debug\ClassLibrary.pdb".
  Touching "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\obj\Debug\ConsoleApp.csproj.CopyComplete".
_CopyAppConfigFile:
Skipping target "_CopyAppConfigFile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  Copying file from "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\obj\Debug\ConsoleApp.exe" to "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\bin\Debug\ConsoleApp.exe".
  ConsoleApp -> E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\bin\Debug\ConsoleApp.exe
  Copying file from "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\obj\Debug\ConsoleApp.pdb" to "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\bin\Debug\ConsoleApp.pdb".
Done Building Project "E:\delete\msbuild-reference-cache\ReferenceCacheExample\ConsoleApp\ConsoleApp.csproj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.08
```

**Comment by mwelsh1118** [comment]
@cdmihai Thanks! This is very informative!

A related question I had: is there any way to make the .cache path information relative (or update paths after-the-fact)? We use a pool of Git repositories per server to compile in parallel. So a cache may be generated on one server in one repository and consumed on a different server with a different repository path.

**Comment by cdmihai** [comment]
Sadly no. We do not have an issue with this because our build machines are setup with the same file system layout, so a path is valid across all of them.

BuildXL on the other hand detours file accesses and rebases paths on the fly. I think this is the class which remaps paths: https://github.com/microsoft/BuildXL/blob/master/Public/Src/Utilities/Configuration/Mutable/PathRemapper.cs

**Comment by mwelsh1118** [comment]
Even with relative paths in the project file, the cache files seem to get looked up via absolute path.  So to use the example above, if I run these:

```
msbuild msbuild-reference-cache\ReferenceCacheExample\ClassLibrary /orc:msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\ClassLibrary.cache /t:GetTargetFrameworks;Build;GetCopyToOutputDirectoryItems;GetNativeManifest
msbuild msbuild-reference-cache\ReferenceCacheExample\ConsoleApp /irc:msbuild-reference-cache\ReferenceCacheExample\ClassLibrary\ClassLibrary.cache
```

All is well; it compiles.  If I then rename msbuild-reference-cache to msbuild-reference-cache2 and run:

```
msbuild msbuild-reference-cache2\ReferenceCacheExample\ConsoleApp /irc:msbuild-reference-cache2\ReferenceCacheExample\ClassLibrary\ClassLibrary.cache
```

It fails with the original error.  So it seems like the cache lookup is done via the absolute path to the csproj.

Just out of curiosity, when you say all your build machines use the same layout, are you running msbuild inside containers? We're planning to explore that. How do you handle the local developer case (where I assume it's not so easy to force a specific layout)? Is the assumption that developers would always compile via Visual Studio locally and not use msbuild?

**Comment by cdmihai** [comment]
>It fails with the original error. So it seems like the cache lookup is done via the absolute path to the csproj.

True, and I think this happens because you are renaming the directory which contains both the projects, and the caches. If you would separate the directory holding the projects from the directory holding the caches, and then rename only the cache root directory, then I think it should work.

I think the reason your renaming example is failing is because:
- internally, msbuild's identity of a project evaluation is the tuple (full_project_path, global properties)
- when the build runs after the rename, the MSBuild task will request a build of `ClassLibrary` with `msbuild-reference-cache2` in the name, whereas the provided input cache will only have results for `ClassLibrary` with `msbuild-reference-cache` in the name, thus leading to a cache miss and the cache miss error.

Ways to workaround this:
- separate the project root dir from the cache root dir. Don't change the project root dir across machines. But you can change the name of the cache root dir
- make all machines/vms homogeneous w.r.t. file layout
- run msbuild under detours and rebase paths with the bxl path remapper. This one is probably the most complicated solution, but it would allow your machines to have different file layouts.

**Comment by mwelsh1118** [comment]
@cdmihai @rainersigwald We recently started using the PathMap msbuild property to remap the repo location on the build server, which will vary based on build server & repo number, to a standard location that's consistent across builds. So now all our build output is binary equivalent.

I was hoping that PathMap would also affect the reference cache output, but it looks like it does not. Would that be something that could be fixed? Then we'd basically get your third workaround out of the box.
