### ISSUE TITLE
.NET 4.5 System.Xml reference assembly has the wrong case in the name

### ISSUE THREAD

**Issue by agocke** [Microsoft/msbuild#522]
The reference assembly in `Reference Assemblies\Framework\.NETFramework\v4.5` is named `System.XML.dll` -- but the standard name used when referencing the dll is `System.Xml`, as far as I can tell. On case-sensitive file systems this causes MSBuild to not find the reference.

**Comment by akoeplinger** [comment]
System.XML is a bit of a weird assembly, because the actual name in the GAC is System.Xml (see also https://github.com/aspnet/Testing/issues/60).

Mono uses System.Xml.dll everywhere, and I know it has caused issues in the past when someone took a csproj with System.XML in it to Linux. It seems that recent VS versions emit System.Xml in the csproj though and the .NET 4.6 reference assemblies also use that casing.

**Comment by jeffkl** [comment]
In newer versions of .NET, the assembly has been properly cased as `System.Xml`.
