### ISSUE TITLE
Msbuild tries to build projects that it knows have broken dependencies

### ISSUE THREAD

**Issue by masonwheeler** [microsoft/msbuild#5252]
This occurs in Visual Studio, but I've been told the actual building is being (mis-)handled by msbuild, so filing it here.

### Steps to reproduce

Seen this pattern happen at least a dozen times:

* Check out solution.
* Open solution in Visual Studio.
* Build solution.
* Project `Project.Core` fails to build because NuGet shenanigans.  Fair enough.
* Project `Project.HigherLevelStuff` fails with an error that it can't find `Project.Core.dll`

### Expected behavior

When a project fails to build, the build system, which knows that other projects have this failed project as a dependency, should not even attempt to build them because it already knows that it will fail.

### Actual behavior

It tries to build it anyway, despite having all the information it needs to know that the build cannot possibly succeed.

**Comment by CyrusNajmabadi** [comment]
Note: it would be good to have this as an option, and to still be able to say that hte build can proceed if a previous built .dll is available.  I use this behavior all the time to be able to run/debug even if some parts of my entire stack aren't buildable (say because i'm in the middle of some refactoring, but want to still try things out without stashing all my changes).

**Comment by rainersigwald** [comment]
This does not repro in MSBuild with a trivial example like
[5252.zip](https://github.com/microsoft/msbuild/files/4516706/5252.zip).

Visual Studio has different behavior, because it doesn't just invoke MSBuild on the solution; instead it builds individual projects according to its own logic. As Cyrus mentions, this can be useful when trying to collect as much information as possible, for example when building up IntelliSense information. But it's not always ideal during real builds.

Please file feedback on Visual Studio at https://developercommunity.visualstudio.com/spaces/8/index.html. If you reply with a link to your issue I can help expedite routing it to the right team.

**Comment by mikenakis** [comment]
For future generations: 

There is this: https://developercommunity.visualstudio.com/t/add-option-to-stop-projects-building-if-their-depe/355793
and this: https://github.com/dotnet/project-system/issues/5352
