### ISSUE TITLE
New string with empty metadata value chooses wrong constructor

### ISSUE THREAD

**Issue by jeffkl** [microsoft/msbuild#5275]
When trying to create a new string and passing in a metadata value, MSBuild tries to bind the the constructor that takes no arguments.  Unfortunately `String` does not have a parameterless constructor and so you get an error.  MSBuild should be using `string.Empty` for these values but for some reason it goes for the wrong overload.

The workaround is to surround the expression with quotes to ensure that the correct overload is chosen.

The below hack is in place because its the only way to call instance methods on metadata values. 
(Related https://github.com/microsoft/msbuild/issues/1155)

### Steps to reproduce

Either include a project sample, attach a zipped project, or provide IDE / CLI steps to create the project and repro the behaviour. Example of a project sample:

Project file
```xml
<Project>
  <ItemGroup>
    <None Include="SomeFolder\**"
          Link="$([System.String]::new(%(RecursiveDir)).Replace(`foo`, `bar`))%(Filename)%(Extension)" />
  </ItemGroup>

  <Target Name="Build">
    <Message Text="%(None.Identity)" Importance="High" />
  </Target>
</Project>
```

Directory contents:
```
│   test.proj
│
└───SomeFolder
        test.txt
```

Command line
```
msbuild /bl
```
### Expected behavior
MSBuild creates a string and calls `.Replace()`.

### Actual behavior
```
error MSB4184: The expression "[System.String]::new()" cannot be evaluated. Attempted to access a missing method.
```

### Workaround
You can places quotes around `%(RecursiveDir)` to force MSBuild to use the overload of `new String()` that accepts a string.
```diff
- $([System.String]::new(%(RecursiveDir))
+ $([System.String]::new(`%(RecursiveDir)`)
```
### Environment data
`msbuild /version` output:

OS info:

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by ladipro** [comment]
@jeffkl technically this looks to be by design. ```RecursiveDir``` is empty so MSBuild tries to evaluate ```$([System.String]::new())``` which really does not bind to any string constructor.

> MSBuild should be using string.Empty for these values but for some reason it goes for the wrong overload.

These props/metadata references are like C macros. They're pre-processed (textually replaced with their value) and then the resulting expression is evaluated. If the parameter expands to nothing, we're not passing any parameter.

>The workaround is to surround the expression with quotes to ensure that the correct overload is chosen.

Sounds like a reasonable thing to do.

That said, it would be quite trivial to handle ```$([System.String]::new())``` internally and make it evaluate to an empty string if this is a useful pattern. I'll defer to @rainersigwald's expertise.

And if Rainer disagrees with faking the parameterless ctor, we should at least optimize calling the one-parameter version. String doesn't have a ctor taking a string (duh!) so in expressions like ```$([System.String]::new(`Hello`)``` we coerce the argument to a char array and then call ```String(char[])``` via reflection, which is pretty lame.

**Comment by rainersigwald** [comment]
I think it's reasonable to return empty string on a no-arg constructor. It'd keep users from having to guard in cases like this (`'%(RecursiveDir)' != ''` would not be obvious IMO). @jeffkl, is that where you ran into this originally?

> we should at least optimize calling the one-parameter version

I'm completely on board with this too.

**Comment by jeffkl** [comment]
A customer reported it in a round about way when adopting my static graph NuGet restore.  This was because we don't expand wildcards, which ended up making this metadata empty.  Given the workaround, I'd say its not very important to fix.  I just needed to log the issue in case anyone else ever hits it.

There's definitely confusing as to when you need to quote things and when you don't.  MSBuild doesn't enforce it so I always do as a best practice.

I'm fine with closing as Won't Fix, it's up to you!
