### ISSUE TITLE
How many CPU cores MSBuild scales up to?

### ISSUE THREAD

**Issue by nawfalhasan** [microsoft/msbuild#5389]
Not an issue, but to know.

# Question
Till how many CPU cores MSBuild scales? I read somewhere it can utilize up to 32 cores, but I am not sure if it is C# specific (or VC++).  Looking for an answer specific to building of C# projects.

# What I tried
I went through the [documention](https://docs.microsoft.com/en-us/visualstudio/msbuild/building-multiple-projects-in-parallel-with-msbuild?view=vs-2019), but it doesn't mention anything in specific.

# Purpose
Saves money. Will be helpful for users who are purchasing new machines for VS development. There are up to 64 cores available in market but we should know how much can VS (MSBuild in particular) can utilize.

**Comment by rainersigwald** [comment]
MSBuild can scale to arbitrary numbers of cores. If you have more than 32, you may need to specify a number explicitly on the command line because of #435.

Note that build speedup is not likely to be linear in number of cores, because of dependencies between projects--you'll only get anywhere near a 64x speedup from a 64-core machine if you have 64 completely independent projects (and aren't bottlenecked on I/O).

**Comment by nawfalhasan** [comment]
Thanks @rainersigwald, that helps. I understand the part about non-linear scaling.

**Comment by rainersigwald** [comment]
Yeah, it's no fun but the best guideline for speccing out a new "standard machine" for your team is probably "try your build in a few different configurations and see what works best". Remember to consider RAM and SSD size/speed in the matrix, too.

I'm going to close this--let us know if you have follow-up questions.
