### ISSUE TITLE
ItemTransformContainingSemicolon_InTaskHost test failure

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/msbuild#5423]
Mysterious failure in the test `ItemTransformContainingSemicolon_InTaskHost`

**Comment by Forgind** [comment]
It appears that this failure came about because TaskHostNodes were able to connect to other OutOfProcNodes—their handshakes came to the same value. To make this more confusing, it had to do with the file version hash sometimes having a bit that masked the bit used to indicate if a node was a task host or not, so this only appeared if the file version hash happened to have a 1 in a specific position. Additionally, it only happened if a TaskHost tried to connect to a non-TaskHost node in the first place, so this consistently succeeded in some cases and normally but not always failed in other cases.
