### ISSUE TITLE
Better Editing Experience

### ISSUE THREAD

**Issue by SamuelEnglard** [microsoft/msbuild#614]
As many issues have documented (and come up with questionable solutions) editing MSBuild files by had is hard, even with XSD which there isn't always.

While I'm not completely sure how (part of the reason for this issue) I think the editing experience needs to be improved.

An example would be that since Tasks are backed by .NET classes why not parse them and expose they type data from them and if available XML documentation?

**Comment by aolszowka** [comment]
I thought I would mention MSBuild Sidekick (http://attrice.info/msbuild/); for a long time they were a sponsor of the MSBuild Extension Pack (http://www.msbuildextensionpack.com/) which is how I believe I had originally found them.

However back when I was using it you still needed a fair understanding of how the system worked in order to make the most of it. I have not used the tool for many years and have no clue if it has been maintained or what the experience is with the tooling.

**Comment by rainersigwald** [comment]
The plan for this is #1774, which @lohitakshgupta is working on this summer. Closing this as a duplicate even though it predates that other issue (that got more traction).
