### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [Microsoft/msbuild#621]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. **msbuild** was in my list. However, I observed that the software history of when the software was developed as a proprietary software was not kept after the transition to Github.

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask **msbuild** developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the _core developers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the _newcomers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by lextm** [comment]
I am an outsider, but I'd like to share my understanding.

If you have read [the Mozilla history](http://oreil.ly/1OsMFws), it would be clear that before releasing the code, all kind of cleanup must be carried out. That means it would be very difficult to keep the internal history (as it might contain confidential information that should never be published).

In the meantime, Microsoft does not use Git internally for such projects (some of them existed before Git was born), so it would also be a pain to migrate history as it would require more efforts.

**Comment by gustavopinto** [comment]
Hi @rainersigwald. Do you have any comments?

**Comment by rainersigwald** [comment]
There were a variety of factors that went into deciding to release as we did.

* Previously, MSBuild was built as a sub-component of Visual Studio, and it had been relocated several times (though several source control systems!) over its lifecycle. Extracting just the subfolder would have been difficult, and older versions would not have built.
* Internally, the release of Visual Studio 2015 corresponded with a clean break between Team Foundation Version Control and Git, so this repo has roughly the same amount of history as we have access to in the internal Git repo.
* We did not release all of the code that makes up MSBuild internally. There are many deprecated or uninteresting components that we wanted to remain private, and excising them from one point-in-time release was easy.
* We also held back some components for licensing reasons: `tracker.exe` and `FileTracker.dll` use the [Detours](http://research.microsoft.com/en-us/projects/detours/) library, which is distributed as source but licensed commercially. To maintain license compliance, we kept that code internal.
* Legal and policy reasons created incentives to release less source.

I have definitely run into some problems related to lack of history (though again, no worse than we experience internally). I know how to manually stitch history together and often do so to get context around what looks like convoluted or confusing source code.

I also took source drops of milestone MSBuild releases, packaged them as git commits, and pushed them to a private git repo on VSTS, with instructions to the core team about how to graft history using `git replace` so that more history is available to us.

**Comment by gustavopinto** [comment]
Hi @rainersigwald, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
