### ISSUE TITLE
Support Item Metadata as Attributes

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#708]
**This issue is in the open design phase and is a part of the [project.json -> csproj ](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) conversion effort.**

Support (optional) terser syntax for specifying metadata on items. This could be useful in a scenario such as specifying a list of NuGet packages (purely as a hypothetical example):
```XML
<ItemGroup>
  <NuGetPackage Include="Newtonsoft.Json">
    <Version>9.0.1-beta1</Version>
  </NuGetPackage>
</ItemGroup>
```
Would become:
```XML
<ItemGroup>
  <NuGetPackage Include="Newtonsoft.Json" Version="9.0.1-beta1" />
</ItemGroup>
```

For compat reasons this could not be added to an existing file and only written if you opt-in to a new "schema version" (or whatever).

**Comment by dsplaisted** [comment]
In the construction APIs, metadata elements are are stored in the `Metadata` property of `ProjectItemElement`:

```C#
public ICollection<ProjectMetadataElement> Metadata { get; }
```

Metadata that comes from attributes on the item element can't really be represented as a `ProjectMetadataElement`, because they're not `XmlElements`.  So to support metadata as attributes, I suggest we add a separate property to `ProjectItemElement`, something like this:

```C#
public ICollection<KeyValuePair<string, string>> MetadataInAttributes { get; }
```

**Comment by dsplaisted** [comment]
In contrast to my previous comment, I'm now experimenting with allowing `ProjectElements` to be expressed as attributes in the Xml.  This is accomplished by having a flag on `ProjectElement` for whether it is expressed as an attribute instead of an element in the Xml, and having logic in `ProjectElementContainer` that manipulates the Xml appropriately when a child `ProjectElement` is added or removed.  You can see my work in progress in https://github.com/dsplaisted/msbuild/tree/MetadataAsAttributes.

**Comment by dsplaisted** [comment]
Today, if you miscapitalize an attribute, you'll get an error such as the following:

    Microsoft.Build.Exceptions.InvalidProjectFileException : The attribute "exclude" in element <compile> is unrecognized.

In order to prevent situations where MSBuild silently accepts miscapitalized attributes as metadata instead of giving an error, I think we should continue to generate this error for attributes which differ only in casing from an attribute we would otherwise recognize.
