### ISSUE TITLE
[DOC] Default value of IgnoreStandardErrorWarningFormat inconsistent between product & MSDN

### ISSUE THREAD

**Issue by piotrpMSFT** [Microsoft/msbuild#766]
According to [MSDN](https://msdn.microsoft.com/en-us/library/microsoft.build.tasks.exec.ignorestandarderrorwarningformat.aspx), `IgnoreStandardErrorWarningFormat` should default to `true`. [This](https://github.com/Microsoft/msbuild/blob/56a7b356b96c4d2ddbde7d268990b62a7f3bfca8/src/XMakeTasks/Exec.cs#L57) shows that it's false. They should be consistent.

**Comment by shift-evgeny** [comment]
This isn't just an inconsistency, it's a horrible, horrible hack to fail the build due to some "standard error and warning format" messages. This so-called "standard format" isn't even documented on the linked MSDN page and this is certainly unexpected behaviour for someone creating a pre-build or post-build step in Visual Studio. This hack should certainly be off by default, like the documentation says it is and if someone does want to turn it on, they should have documentation on exactly what strings it looks for.

Looks like I'm not the only one to run into it: http://stackoverflow.com/questions/39466090/why-outputting-error-in-post-build-event-breaks-my-build-in-vs2012

**Comment by jeffkl** [comment]
The property also says it defaults to `true`: https://github.com/Microsoft/msbuild/blob/56a7b356b96c4d2ddbde7d268990b62a7f3bfca8/src/XMakeTasks/Exec.cs#L106

From what I can tell, it's always been `false` by default so we'll need to determine what impact there would be, if any, if we change it.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
Thanks for the heads up on this. Looking into it now.

**Comment by rainersigwald** [comment]
I don't think this closes the issue. We need the docs site updated, too.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
[MSDN docs](https://msdn.microsoft.com/en-us/library/microsoft.build.tasks.exec.ignorestandarderrorwarningformat.aspx) has been updated to correct default value of false. 

This exact page hasn't been moved over to docs, so I added a line specifying the default value over in docs under "IgnoreStandardErrorWarningFormat": https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task
