### ISSUE TITLE
MSBuild redistribution

### ISSUE THREAD

**Issue by chrischu** [Microsoft/msbuild#771]
I'm almost entirely sure, this is not the right place to put this, but I didn't really have any better ideas so here goes:

I'm currently working on a project that uses the MSBuild DLLs to analyze sln/csproj files and I was wondering what the recommended way to redistribute them is. Is it ok if I just include them in the NuGet packages/ZIP files of my releases? Are there any licensing issues with that?

I know an alternative would be to require my users to install the MSBuild tools, but I would require MSBuild 14.0 and some of my users are worried that installing the newer MSBuild version could mess up their builds (they still use VS13/MSBuild 12.0).

Thanks in advance!

**Comment by Craig-Campbell-MS** [comment]
(with the caveat that I’m not a lawyer)

The answer depends…

IIRC both Visual Studio and the Build Tools package are governed by EULAs that do not grant redistribution rights of the binaries or packages. 

However, the open source binaries are governed by a different license; https://github.com/Microsoft/msbuild/blob/master/LICENSE.

We will soon publish official Nuget packages. @cdmihai @Sarabeth-Jaffe-Microsoft please look into what license we should use in those packages.

@chrischu you should be able to have your customers install the build tools package and it will happily live side by side. We'd be interested to hear otherwise.

**Comment by jeffkl** [comment]
@Sarabeth-Jaffe-Microsoft did we figure this out?

**Comment by shartte** [comment]
The currently published MSBuild Nuget packages do not use the MIT license either.
Can you comment on why that is the case?

**Comment by dasMulli** [comment]
Due to these licensing issues JetBrains created their own distributable bundle - https://blog.jetbrains.com/dotnet/2018/04/13/introducing-jetbrains-redistributable-msbuild/

What kind of projects are you analyzing? as long as they don't need VS-specific build tooling (Database projects, classic WPF, test projects using Microsoft Fakes) you should be fine with the .NET Core SDK installed. [Buildalyzer](https://github.com/daveaglick/Buildalyzer) can get most of that wiring set up for you.

But yeah build tooling redistribution and usage is complicated.. e.g. you can only use the Build Tools if you have a Visual Studio license. Which is fun because the node.js optionally chains in the 2017 build tools to be able to compile C++ bindings for some nom packages (libsass for example).
Sooo.. as long as you these npm packages are open source, one could theoretically argue that you would be entitled to a VS Community license for that operation.

**Comment by shartte** [comment]
Yes, we don't need any VS specific tooling. But we'd like to bundle it since we use mono as the backend and not .NET core. We might just end up building our own MSBuild packages for this purpose.

**Comment by dasMulli** [comment]
Btw the mono distribution also bundles SDKs for building SDK-style projects (`<Project Sdk="Microsoft.NET.Sdk">`) which is kind of useful.. (but I think there's also an SDK resolver in it that looks for newer .NET Core SDK installs)

**Comment by rainersigwald** [comment]
The 16.1 packages (prerelease; currently available from [the MyGet feed](https://dotnet.myget.org/gallery/msbuild)) are licensed with the MIT expression, as of #4251.
