### ISSUE TITLE
Mechanism for "magic" pickup of nuget restore logic during build

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#784]
On full framework, desktop installs, the nuget msi dropped its targets into `$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets`. This ensured that all the builds on the machine got Nuget functionality.

Problems with this approach:
- no machine wide program files directory for .net core apps. The most you can do with this approach is drop targets into the applocal extension path (xplat msbuild resolves the extension path relative to msbuild.exe)
- not friendly with other consumers. Where would each project put its special logic coming in from nuget packages?. Would they all write their files inside the CLI SDK, into MSBuild's applocal extension path? This does not scale well since a project can now potentially influence other projects

Solution:
- create a new convention for loading project specific build logic that comes from packages
- common.props imports a special file (something like `<project_name>.generated.targets`), if it is there
- the file sits in the intermediate output directory
- nuget can generate its contents inside of it.
- there should be a switch to disable this convention

**Comment by dsplaisted** [comment]
NuGet, along with MSBuild, should logically be part of the .NET CLI platform.  So the targets it needs should come together with MSBuild, and the common targets, and the C#/VB targets when you install the .NET CLI.  (Whether it actually comes from separate NuGet packages, MSIs, apt packages, etc isn't important to the user as long as there's one top-level action that gets you everything.)

The targets should be written in such a way that you can override them with your own copies by setting an MSBuild property.  I know the Roslyn targets already do this, I don't know about the NuGet targets.  That way you get the benefit of everything working out of the box, while still being extensible if you want to do something different.

As for having a feature to automatically pick up targets from the project directory, that seems fine to me (and NuGet actually already does this in order to support .props and .targets files that come from packages), but I don't think it should for the default experience.

**Comment by rainersigwald** [comment]
@dsplaisted I think you're thinking about something else. This issue is to solve only the last issue you were talking about (given that NuGet restore has already happened, how does MSBuild pull in package-delivered build logic for a project).

The proposed solution is to generalize the existing NuGet mechanism. It's currently included in the build via [a wildcard import in Microsoft.Common.CurrentVersion.targets](https://github.com/Microsoft/msbuild/blob/c1459f5cbd36f2c33eafc8f4ff087f6ee84c3640/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L5508) (and another in props) that imports a file that contains

```XML
  <Import Project="$(MSBuildProjectDirectory)\$(MSBuildProjectName).nuget.targets"
 Condition="Exists('$(MSBuildProjectDirectory)\$(MSBuildProjectName).nuget.targets') AND '$(IncludeNuGetImports)' != 'false'" />
```

We're thinking to generalize that to `$(MSBuildProjectDirectory)\$(MSBuildProjectName).generated.targets` (to avoid privileging NuGet above other package managers with similar requirements) and moving the import to core common props/targets directly. That way NuGet doesn't need to "install" its targets in every possible app-local MSBuild.

There are two other parts to the NuGet scenario that aren't affected by this change.

Packages need to be specified and restored somehow.  My understanding is that the POR for dev15 RTM is to continue on with project.json and an explicit separate restore step (either `dotnet restore` or `nuget.exe restore`). The only change required here is that we'd want the generated props/targets files to obey the new naming rule.

The other part is resolving assets out of a package for use at build time. @jasonmalinowski is thinking that all of the logic for that can be included in its own NuGet package. That would mean that the only alteration core MSBuild would need is this--to get the "resolve assets" logic included in a project at build time post-restore.

**Comment by dsplaisted** [comment]
@rainersigwald I see, that makes sense.

**Comment by mhutch** [comment]
So... instead of NuGet having to install into every MSBuild, it has to install into *every project directory*? Isn't that going to tie the projects themselves to a specific NuGet install?

That also seems to me like it would prevent NuGet supporting MSBuild-integrated restore and require it to continue being a separate, explicit command.

**Comment by mhutch** [comment]
Also, isn't this going to break if you use multiple package managers, as they'll be fighting over one file?

**Comment by jeffkl** [comment]
I'm going to start working on this, here is the proposal:

``` xml
<Import Project="$(ProjectPackageImport)" 
    Condition=" '$(ImportProjectPackages)' != 'false' and '$(ProjectPackageImport)' != '' />
```

The property `$(ProjectPackageImport)` will be set to `$(MSBuildProjectName).*.targets`.  This will allow NuGet to create a `ProjectA.nuget.targets` and another package manager could create a `ProjectA.projectMan.targets`.

The default location of the import will be in the project directory unless the intermediate output path is specified.
## How does NuGet know where to drop the file?
I'm worried people can overwrite where MSBuild looks for it but NuGet won't know.
