### ISSUE TITLE
Microsoft.Build.Evaluation.Project(string projectFile) does not reparse project file the second time a Project instance is constructed

### ISSUE THREAD

**Issue by Sarabeth-Jaffe-Microsoft** [microsoft/msbuild#795]
**This item was filed by a customer. See below for description & repro steps:**

Description: When using the Project(string projectFile) constructor two times after each other, the second time does not read the content from the file, but uses some cache of where it re-uses the content from the first time, even though the file might have changed. 

Repro Steps: I have a stand alone solution which has the minimum amount of code to reproduce the issue. It should be self-explanatory. 

Impact: Unexpected behaviour, weird issues, lost time. Work around IS available.

See Connect bug [here](https://connect.microsoft.com/VisualStudio/feedback/details/2880213/microsoft-build-evaluation-project-string-projectfile-does-not-reparse-project-file-the-second-time-a-project-instance-is-constructed). Please let us know if you want the repro zip.

**Comment by maddin2016** [comment]
Hi @Sarabeth-Jaffe-Microsoft, can you send me the repro zip. What means 

> workaround IS available?
Is this issue still fixed?

**Comment by FelixNairz** [comment]
Hi, here is the zip-file.

You can see the workaround in the code.

[ProjectConstructorBug.zip](https://github.com/Microsoft/msbuild/files/408771/ProjectConstructorBug.zip)

**Comment by maddin2016** [comment]
Hi @FelixNairz, thanks for the zip. I will see what i can do.

**Comment by maddin2016** [comment]
Hi @Sarabeth-Jaffe-Microsoft, can it be that this behavior is wanted. Because in the [constructor](https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/Definition/ProjectCollection.cs#L256) of `ProjectCollection` this bool hardcoded. Is that correct?

**Comment by maddin2016** [comment]
Ok, i see that it's easier. @FelixNairz, you have to do `p.ProjectCollection.UnloadAllProjects()`
```
public void UpgradeProject()
            {
                var p = GetProject();

                try
                {
                    UpgradeRanorexVersion(p);

                    p.Save(this.projectFile);
                }
                finally
                {
                    p.ProjectCollection.UnloadAllProjects();
                    var loadedProjects = ProjectCollection.GlobalProjectCollection.GetLoadedProjects(this.projectFile);
                    Debug.Assert(!loadedProjects.Any());
                }
            }
```
This forces to unload all projects and cleares the propertyCache.
[See here](https://github.com/Microsoft/msbuild/blob/master/src/XMakeBuildEngine/Definition/ProjectCollection.cs#L1189)

**Comment by maddin2016** [comment]
But there is still the question if user is **not** completely done and **has** to do changes on disk, that they are able to read this changes from disk instead of `PropertyCache`

**Comment by FelixNairz** [comment]
I still believe this is a bug. 
Check the line where I call ProjectCollection.GlobalProjectCollection.UnloadProject(p);

Since, in this example I only load one project anyway, there should be no difference between UnloadProject, and UnloadAllProjects, right? At the time I am done modifying, that project is NOT loaded anymore.

Then I construct the project again inside ProjectUpgrader.UpgradeProject() and it does not look at the file, but at some kind of cache.

**Comment by maddin2016** [comment]
Hi @FelixNairz. Yes it unloads the project but it doesn't clear the cache for that project. So if you load the project again it load it from the cache. Maybe tomorrow I can add some overload's that will load the file from Disk and not from cache. But to be sure @Sarabeth-Jaffe-Microsoft is my statement correct?

**Comment by cdmihai** [comment]
I poked through the code and found this comment: https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeBuildEngine/Definition/ProjectCollection.cs#L189-L197

My interpretation of that comment (and of the Project constructor that sets the cache to not reload on disk changes) is that when a build is running, multiple project root elements are opened (transitive imports) and possibly re-opened (via the msbuild task). At the same time as a build is running, other programs may change the xml files for those projects (let's say a property rename that touches all the files that use that property). You don't want your build to capture this inconsistent state (part of the build uses some files with the old property name and part of the build uses files with the new name), and therefore the cache is not flushed, and reloading on disk changes is turned off.

Considering this, I'd vote for just using `UnloadAllProjects` instead of adding the overload. Adding the overload might lead to some nasty weird bugs down the road, when most projects use the old constructor and a few the new one.

**Comment by FelixNairz** [comment]
How about a way to remove a particular project from the cache? 

In this case at least, I want to ensure this project should be reloaded, but I don't necessary want all other projects to be reloaded too (costly). 

Also, the fact that we have two constructors, with
- string filename 
-XmlReader 
as arguments, one using a cached version, and another one not using a cached version is somewhat misleading. I know why this is of course, but it just adds to the confusion.

**Comment by manoharjogi** [comment]
we want to develop an app which auto migrate lower version projects to higher version.

**Comment by manoharjogi** [comment]
please help on this

**Comment by manoharjogi** [comment]
I am not getting any value in match varialble. please suggest any more

var match = this.ranorexSolutionVersionRegex.Match(fileContent);

**Comment by livarcocc** [comment]
Team triage: After reading @cdmihai's explanation above about keeping the world view consistent and adding to that the fact that people haven't been asking us for this, we are going to go ahead and close this issue.
