### ISSUE TITLE
TaskItemComparer.Compare method has misprint in it.

### ISSUE THREAD

**Issue by serjic** [Microsoft/msbuild#81]
When comparing collection length it uses the same parameter 'x' twice:
 if (x.CloneCustomMetadata().Count != x.CloneCustomMetadata().Count)

**Comment by jasonwilliams200OK** [comment]
@akoeplinger, could this be by design:
https://github.com/Microsoft/msbuild/blob/82177a50da735cc0443ac10fa490d69368403d71/src/XMakeBuildEngine/UnitTests/BackEnd/TaskItemComparer.cs#L51?

I think @serjic alone has caught some very fundamental bugs in msbuild code base: https://github.com/Microsoft/msbuild/issues/created_by/serjic which need attention :smile:

**Comment by akoeplinger** [comment]
@jasonwilliams200OK it looks like a bug to me, I hope the msbuild team takes a look :)
