### ISSUE TITLE
Support package managers

### ISSUE THREAD

**Issue by nathanaeljones** [Microsoft/msbuild#83]
NuGet [dropped MSBuild support due to a range of design flaws](https://github.com/fsprojects/Paket/issues/417#issuecomment-66517859). 

Unlike NuGet, though, other projects don't have the luxury of shipping with visual studio. Please solve this problem in a way that can help [projects like Paket work out of the box](https://github.com/fsprojects/Paket/issues/417). 

NuGet has made very little progress over the years, and has more correctness issues than we can enumerate here. Please make it possible for the community to fix this kind of deficiency.

**Comment by AndyGerlicher** [comment]
Package support is on our long term roadmap. This is not something we want to address at this time.

**Comment by nathanaeljones** [comment]
Keep in mind, that with this you're killing F# (for which NuGet is unusable) and cross-platform C#+p/invoke (where NuGet is unusable). 

After so many promises to play fair, this is pretty much the ultimate F*** you to the OSS community.

**Comment by dsplaisted** [comment]
> Is permitting re-load after pre-build so hard?

@nathanaeljones Basically, yes.  The newly imported targets could impact everything that's already been evaluated and executed, so MSBuild would have to throw out everything and start over.

Generally what we do for package restore for CI / command line builds is to have an outer project which runs package restore and then calls MSBuild on the project files that actually build the source code.  These projects aren't evaluated until after packages are restored, so it works correctly.  Here's [an example](https://github.com/dsplaisted/strongnamer/blob/82fc3c6f85409673edf6a2088c01d737d6f9913a/build/build.proj#L57) of this.

This doesn't help in Visual Studio because VS wouldn't build the outer project which does package restore.  However, what you can do is to have the project do the package restore and then call MSBuild on itself.  I've created a proof of concept of doing this in the paket.targets file [here](https://github.com/dsplaisted/paket-restore-sample/blob/master/.paket/paket.targets).

**Comment by dhusemann** [comment]
Shouldn't this stay open?? although it isn't in the current plans it is still something to be addressed.
