### ISSUE TITLE
Xplat build script (and regular build script) should pull in required dependencies

### ISSUE THREAD

**Issue by mmitche** [Microsoft/msbuild#88]
Specifically, the unit testing framework.  It would be really nice to keep this in line with the other dotnet OSS projects.

**Comment by josteink** [comment]
Definitely agree about this one. 

Currently, I think the "biggest" hindrances to getting this done are:

* [The xplat build-script](https://github.com/Microsoft/msbuild/blob/xplat/build.pl) is perl-based, as opposed to being a regular shell-script used everywhere else in the world of dotnet.
* The xplat-branch seems to be a long-living feature-branch.

First point means we need to get write and maintain dedicated code for this project only instead of just copying something proven which works everywhere. That's probably not a show-stopper though.

What might make it so is that the xplat-branch has an uncertain future. xplat and master is diverging and needs to get merged to ensure the long-term viability of code submitted to the xplat-branch.

I mean, who wants to submit patches only to have them end up in a dead, unmaintained branch?

**Comment by jasonwilliams200OK** [comment]
@mmitche, i think this has been accomplished by @cdmihai via #501.

@josteink, not only Perl script is removed (#510), msbuild is now using [`sh` script](https://github.com/Microsoft/msbuild/blob/2fa5cfd/cibuild.sh) instead of `bash`! Ahead of all dotnet projects I must say (dotnet/home#29). :smile:

**Comment by mmitche** [comment]
Sounds good to me

**Comment by josteink** [comment]
@jasonwilliams200OK Nice work. Good to see you're making progress :)
