### ISSUE TITLE
Improper escaping during <MSBuild> task invocation

### ISSUE THREAD

**Issue by piotrpMSFT** [Microsoft/msbuild#885]
main.proj

```
...
   <MSBuild Properties="taskpath=/foo/bar/123@/do.dll" 
                    Project="zap.proj" />
...
```

zap.proj

```
  <?xml version="1.0" encoding="utf-8"?>
  <Project DefaultTarget="DoStuff" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <UsingTask TaskName="DoTheThing" AssemblyFile="$(taskpath)" />

    <Target Name="DoStuff">
      <DoTheThing />
    </Target>
  </Project>
```

With this configuration the <MSBuild> invocation fails with:

```
error MSB4062: The "DoTheThing" task could not be loaded from the assembly /foo/bar/123*%40*/do.dll. The system cannot find the file specified.
```

It looks like the valid `@` in the path was escaped to `%40` during invocation of the child MSBuild process but was not subsequently unescaped.

@rainersigwald

**Comment by piotrpMSFT** [comment]
@rainersigwald any update on this?

**Comment by cdmihai** [comment]
Might be related to #931 hopefully fixing that one fixes this as well.

**Comment by cdmihai** [comment]
It is not related to #931, the build time logic of MSBuild is separate from the Evaluation time logic :(

The MSBuild task escapes all the property values from the MSBuild task: https://github.com/Microsoft/msbuild/blob/xplat/src/Shared/PropertyParser.cs#L110

The evaluation of UsingTask elements does not unescape the attribute under `AssemblyFile`: https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeBuildEngine/Instance/TaskRegistry.cs#L272

Since this behaviour has been there forever, changing it could break existing code. The workaround would be to manually unescape the string in the UsingTask via the `[MSBuild]::Unescape` property intrinsic function.

However, the fact that the MSBuild task escapes input seems to be out of sync with the MSBuild escaping policy with items and properties where users are expected to escape msbuild specific characters (and then the engine unescapes at various points). 

@Microsoft/msbuild-maintainers, should we consider changing the legacy behaviour?

**Comment by cdmihai** [comment]
Caveat: According to #1184, the `Exists` property function silently unescapes its arguments

**Comment by cdmihai** [comment]
Another caveat: Global properties (command line properties and properties set by the MSBuild task) cannot be overwritten, and MSBuild silently does this without any warnings #1196. Make sure that in the invoked project you use a different property name to unescape the global property in.

**Comment by koczkatamas** [comment]
Any update on this issue or can you suggest a workaround?

Our Jenkins build automatically puts the project into folders with `@2`, etc in their names. Then the `$(ProjectDir)` variable used for `UsingTask` does not work anymore...

**Comment by cdmihai** [comment]
Since it's quite legacy behaviour we won't change the current behaviour to avoid breaking existing build scripts.

A workaround is to manually unescape the path in the using task:

```xml
 <UsingTask TaskName="DoTheThing" AssemblyFile="$([MSBuild]::Unescape('$(taskpath)'))" />
```
