### ISSUE TITLE
Allow Import to accept a delimited list of Project files

### ISSUE THREAD

**Issue by kingces95** [Microsoft/msbuild#890]
I'd like to build up a list of project files to import in an ItemList and import them. So, for example, this:

```
<Import Project="Foo.props" />
<Import Project="Bar.props" />
```

 would be equivalent to this:

```
<ItemGroup>
  <Projects Include="Foo.props;Bar.props"/>
</ItemGroup>
<Import Project="@(Projects)" />
```

Seems a natural construct... 

Warm regards,
Chris

**Comment by jasonwilliams200OK** [comment]
IMO, this should just accept the glob pattern and remain one item per row. The reason being, Unix allows `;` and `,` as a valid filename characters so choosing those as separator won't be a good idea. Perhaps we can use `:` instead which is a file separator on Unix and drive letter separator on Windows.

**Comment by kingces95** [comment]
Hm, isn't that a more general problem not specific to this import feature suggestion? If so, seems worthy of it's own issue. Something like 

    ItemGroup support for file names containing commas and\or semi-colons

This issue is asking for a way to import multiple files with a single import statement; It's not intending to make any suggestion about how lists of files are declared.

**Comment by rainersigwald** [comment]
Unfortunately, this is almost impossible given MSBuild's evaluation model. `<Import>` works as a textual include—“pretend the contents of that file were in this file at this position”—and the text of the to-be-imported file could contain anything. The evaluation model is:

1. Start at the top of the entry-point project and proceed downward, evaluating properties in `PropertyGroup`s **and imports** in `Import`s and `ImportGroup`s. When you see an import, detour to the top of that file and recurse—when done, come back to this point.
2. Start at the top of the now-complete-with-imports in-memory project, and proceed downward, evaluating item definitions in `ItemDefinitionGroups`.
3. Start at the top of the complete-with-imports in-memory project, and proceed downward, evaluating items in `ItemGroups`.
4. Start at the top of the complete-with-imports in-memory project, and proceed downward, evaluating `UsingTask`s.
5. Start at the top of the complete-with-imports in-memory project, and proceed downward, reading (but not executing) targets in `Target`s.

The reason you can't import using items is that 3 happens after 1—there are no items in the state of the project as we import files.

We can't just change that, because it's longstanding MSBuild behavior that all properties are fully evaluated before evaluating items, and changing that would break people.

**Comment by kingces95** [comment]
@rainersigwald Ah, I see. Thanks for drafting that. 

Well, would it be feasible to pass a delimited list of files? For example could this:

    <PropertyGroup>
        <Imports>foo.props;bar.props</Imports>
    </PropertyGroup>
    <Import Project="$(Imports)" />

be made equivalent to this:

    <Import Project="Foo.props" />
    <Import Project="Bar.props" />

Without breaking anyone?
