### ISSUE TITLE
Project.GetItemProvenance(ProjectItem) does not return Operation.Update results

### ISSUE THREAD

**Issue by jviau** [Microsoft/msbuild#919]
Have a project file with:

```
<Compile Include="**\*.cs" />
<Compile Update="foo.cs">
  <Visible>false</Visible>
</Compile>
```

`GetItemProvenance` returns the following:
``` C#
var item = project.GetItemsByEvaluatedInclude("foo.cs").First(); // Has DirectMetadata of "Visible=false"
var provenance1 = project.GetItemProvenance(item); // Contains only Glob entry
var provenance2 = project.GetItemProvenance("foo.cs", "Compile") // Contains both Glob and Update
bool provenance1.Count == provenance2.Count // false!
```

I would expect those two results to be the same.

**Comment by cdmihai** [comment]
The `Project.GetItemProvenance(ProjectItem item)` overload only looks from its location (the ProjectItemElement that produced the ProjectItem) upwards. `Project.GetItemProvenance(string item, string itemType)` looks over all.

That's why provenance1 does not include the update but provenance2 does.

This behaviour is as defined in #732. Would you want to change the behaviour of the `ProjectItem` overload?

**Comment by jviau** [comment]
Flow sensitive behavior is fine, but I would think the Update tag would be included in that flow since it does affect the production of the ProjectItem. Is it possible to change the behavior to include the Update tag?

**Comment by cdmihai** [comment]
So basically make it flow insensitive, with `GetItemProvenance(item)` just calling into `GetItemProvenance(item.EvaluatedInclude, item.ItemType)`?

**Comment by cdmihai** [comment]
After an offline discussion we decided to change the `Project.GetItemProvenance(ProjectItem)` overload to only collect project item elements that would affect that project item.

Bellow is the new behaviour. `->` marks project items that provenance is called upon. `x` marks project item elements that are captured (besides the actual include element that produced the item itself).

```
->i
  i
x u
  i
x u
```

```
  i
->i
x u
  i
x u
```

```
  i
  i
  i
  u
->i
x u
```

Removes are not shown, since by definition they will not get found (Remove deletes the project items)
